apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-router-if-empty-branches-flow-line-13-if-1.yaml
- asyncactor-start-if-empty-branches-flow.yaml
- configmap-routers.yaml
