apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-early-return-flow-if-not-valid
  namespace: default
  labels:
    asya.sh/flow: early-return-flow
    asya.sh/generated: 'true'
spec:
  actor: router-early-return-flow-if-not-valid
  image: python:3.13-slim
  handler: routers.router_early_return_flow_if_not_valid
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_ERROR
    value: if_with_early_return.handler_error
  - name: ASYA_HANDLER_ACTOR_HANDLER_FINALIZE
    value: if_with_early_return.handler_finalize
  - name: ASYA_HANDLER_ACTOR_HANDLER_PROCESS
    value: if_with_early_return.handler_process
  - name: ASYA_HANDLER_ACTOR_HANDLER_VALIDATE
    value: if_with_early_return.handler_validate
  - name: ASYA_HANDLER_ROUTER_EARLY_RETURN_FLOW_IF_NOT_VALID
    value: routers.router_early_return_flow_if_not_valid
  volumes:
  - name: routers
    configMap:
      name: early-return-flow-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
