apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-early-return-flow-line-13-if-1
  namespace: default
  labels:
    asya.sh/flow: early-return-flow
    asya.sh/generated: 'true'
spec:
  actor: router-early-return-flow-line-13-if-1
  image: python:3.13-slim
  handler: routers.router_early_return_flow_line_13_if_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ROUTER_EARLY_RETURN_FLOW_LINE_13_IF_1
    value: routers.router_early_return_flow_line_13_if_1
