flowchart TD
    %% Flow: if_elif_else_flow

    handler_default[handler_default]
    handler_finalize[handler_finalize]
    handler_type_a[handler_type_a]
    handler_type_b[handler_type_b]
    handler_validate[handler_validate]
    router_if_elif_else_flow_if_type_eq_a{{router_if_elif_else_flow_if_type_eq_a}}
    router_if_elif_else_flow_if_type_eq_b{{router_if_elif_else_flow_if_type_eq_b}}
    start_if_elif_else_flow([start_if_elif_else_flow])
    __end__((( )))

    start_if_elif_else_flow --> handler_validate
    handler_validate --> router_if_elif_else_flow_if_type_eq_a
    router_if_elif_else_flow_if_type_eq_b -->|"p['type'] == 'B'"| handler_type_b
    router_if_elif_else_flow_if_type_eq_b -->|"else"| handler_default
    router_if_elif_else_flow_if_type_eq_a -->|"p['type'] == 'A'"| handler_type_a
    handler_type_a --> handler_finalize
    router_if_elif_else_flow_if_type_eq_a -->|"else"| router_if_elif_else_flow_if_type_eq_b
    handler_type_b --> handler_finalize
    handler_default --> handler_finalize
    handler_finalize --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_if_elif_else_flow start
    class handler_finalize,__end__ endnode
    class router_if_elif_else_flow_if_type_eq_a,router_if_elif_else_flow_if_type_eq_b router
    class handler_default,handler_type_a,handler_type_b,handler_validate handler
    linkStyle 2,4 stroke:#2E8B57
    linkStyle 3,6 stroke:#E07040