flowchart TD
    %% Flow: if_elif_else_flow

    handler_default[handler_default]
    handler_finalize[handler_finalize]
    handler_type_a[handler_type_a]
    handler_type_b[handler_type_b]
    handler_validate[handler_validate]
    router_if_elif_else_flow_line_14_if_2{{router_if_elif_else_flow_line_14_if_2}}
    router_if_elif_else_flow_line_16_if_1{{router_if_elif_else_flow_line_16_if_1}}
    start_if_elif_else_flow([start_if_elif_else_flow])
    __end__((( )))

    start_if_elif_else_flow --> handler_validate
    handler_validate --> router_if_elif_else_flow_line_14_if_2
    router_if_elif_else_flow_line_16_if_1 -->|"p['type'] == 'B'"| handler_type_b
    router_if_elif_else_flow_line_16_if_1 -->|"else"| handler_default
    router_if_elif_else_flow_line_14_if_2 -->|"p['type'] == 'A'"| handler_type_a
    handler_type_a --> handler_finalize
    router_if_elif_else_flow_line_14_if_2 -->|"else"| router_if_elif_else_flow_line_16_if_1
    handler_type_b --> handler_finalize
    handler_default --> handler_finalize
    handler_finalize --> __end__