{{- if and .Values.sampleTransports.sqsLocalstack.enabled (eq .Values.global.transport "sqs") }}
apiVersion: v1
kind: Secret
metadata:
  name: sqs-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: localstack-sqs
    app.kubernetes.io/name: sqs-credentials
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sample-transport
type: Opaque
stringData:
  access-key-id: {{ .Values.sampleTransports.sqsLocalstack.auth.accessKeyId | default "test" | quote }}
  secret-access-key: {{ .Values.sampleTransports.sqsLocalstack.auth.secretAccessKey | default "test" | quote }}
{{- end }}
