flowchart TD
    %% Flow: nested_if_flow

    handler_a_x[handler_a_x]
    handler_a_y[handler_a_y]
    handler_b_x[handler_b_x]
    handler_b_y[handler_b_y]
    handler_finalize[handler_finalize]
    handler_validate[handler_validate]
    router_nested_if_flow_if_level1_eq_a{{router_nested_if_flow_if_level1_eq_a}}
    router_nested_if_flow_if_level2_eq_x{{"router_nested_if_flow_if_level2_eq_x<br/><br/>p['l1'] = 'A'"}}
    router_nested_if_flow_if_level2_eq_x_2{{"router_nested_if_flow_if_level2_eq_x_2<br/><br/>p['l1'] = 'B'"}}
    router_nested_if_flow_seq_set_l2{{"router_nested_if_flow_seq_set_l2<br/><br/>p['l2'] = 'X'"}}
    router_nested_if_flow_seq_set_l2_2{{"router_nested_if_flow_seq_set_l2_2<br/><br/>p['l2'] = 'Y'"}}
    router_nested_if_flow_seq_set_l2_3{{"router_nested_if_flow_seq_set_l2_3<br/><br/>p['l2'] = 'X'"}}
    router_nested_if_flow_seq_set_l2_4{{"router_nested_if_flow_seq_set_l2_4<br/><br/>p['l2'] = 'Y'"}}
    start_nested_if_flow([start_nested_if_flow])
    __end__((( )))

    start_nested_if_flow --> handler_validate
    handler_validate --> router_nested_if_flow_if_level1_eq_a
    router_nested_if_flow_seq_set_l2 --> handler_a_x
    router_nested_if_flow_seq_set_l2_2 --> handler_a_y
    router_nested_if_flow_if_level2_eq_x -->|"p['level2'] == 'X'"| router_nested_if_flow_seq_set_l2
    router_nested_if_flow_if_level2_eq_x -->|"else"| router_nested_if_flow_seq_set_l2_2
    router_nested_if_flow_seq_set_l2_3 --> handler_b_x
    router_nested_if_flow_seq_set_l2_4 --> handler_b_y
    router_nested_if_flow_if_level2_eq_x_2 -->|"p['level2'] == 'X'"| router_nested_if_flow_seq_set_l2_3
    router_nested_if_flow_if_level2_eq_x_2 -->|"else"| router_nested_if_flow_seq_set_l2_4
    router_nested_if_flow_if_level1_eq_a -->|"p['level1'] == 'A'"| router_nested_if_flow_if_level2_eq_x
    router_nested_if_flow_if_level1_eq_a -->|"else"| router_nested_if_flow_if_level2_eq_x_2
    handler_a_x --> handler_finalize
    handler_a_y --> handler_finalize
    handler_b_x --> handler_finalize
    handler_b_y --> handler_finalize
    handler_finalize --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_nested_if_flow start
    class handler_finalize,__end__ endnode
    class router_nested_if_flow_if_level1_eq_a,router_nested_if_flow_if_level2_eq_x,router_nested_if_flow_if_level2_eq_x_2,router_nested_if_flow_seq_set_l2,router_nested_if_flow_seq_set_l2_2,router_nested_if_flow_seq_set_l2_3,router_nested_if_flow_seq_set_l2_4 router
    class handler_a_x,handler_a_y,handler_b_x,handler_b_y,handler_validate handler
    linkStyle 4,8,10 stroke:#2E8B57
    linkStyle 5,9,11 stroke:#E07040