apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-plan-and-execute-while-current-step-lt-len-p-get-plan
  namespace: default
  labels:
    asya.sh/flow: plan-and-execute
    asya.sh/generated: 'true'
spec:
  actor: router-plan-and-execute-while-current-step-lt-len-p-get-plan
  image: python:3.13-slim
  handler: routers.router_plan_and_execute_while_current_step_lt_len_p_get_plan
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_EXECUTOR
    value: plan_and_execute.executor
  - name: ASYA_HANDLER_ACTOR_PLANNER
    value: plan_and_execute.planner
  - name: ASYA_HANDLER_ACTOR_RE_PLANNER
    value: plan_and_execute.re_planner
  - name: ASYA_HANDLER_ROUTER_PLAN_AND_EXECUTE_IF_CURRENT_STEP_LT_LEN_P_GET_PLAN
    value: routers.router_plan_and_execute_if_current_step_lt_len_p_get_plan
  - name: ASYA_HANDLER_ROUTER_PLAN_AND_EXECUTE_SEQ_SET_COMPLETED
    value: routers.router_plan_and_execute_seq_set_completed
  - name: ASYA_HANDLER_ROUTER_PLAN_AND_EXECUTE_WHILE_CURRENT_STEP_LT_LEN_P_GET_PLAN
    value: routers.router_plan_and_execute_while_current_step_lt_len_p_get_plan
  - name: ASYA_HANDLER_ACTOR_SYNTHESIZER
    value: plan_and_execute.synthesizer
  volumes:
  - name: routers
    configMap:
      name: plan-and-execute-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
