apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-plan-and-execute-line-61-seq-1
  namespace: default
  labels:
    asya.sh/flow: plan-and-execute
    asya.sh/generated: 'true'
spec:
  actor: router-plan-and-execute-line-61-seq-1
  image: python:3.13-slim
  handler: routers.router_plan_and_execute_line_61_seq_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_EXECUTOR
    value: executor
  - name: ASYA_HANDLER_PLANNER
    value: planner
  - name: ASYA_HANDLER_RE_PLANNER
    value: re_planner
  - name: ASYA_HANDLER_ROUTER_PLAN_AND_EXECUTE_LINE_53_WHILE_2
    value: routers.router_plan_and_execute_line_53_while_2
  - name: ASYA_HANDLER_ROUTER_PLAN_AND_EXECUTE_LINE_58_IF_3
    value: routers.router_plan_and_execute_line_58_if_3
  - name: ASYA_HANDLER_ROUTER_PLAN_AND_EXECUTE_LINE_61_SEQ_1
    value: routers.router_plan_and_execute_line_61_seq_1
  - name: ASYA_HANDLER_SYNTHESIZER
    value: synthesizer
