apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: planner
  namespace: default
  labels:
    asya.sh/flow: plan-and-execute
spec:
  actor: planner
  image: examples.asya.sh/planner:latest
  handler: planner
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
