apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: synthesizer
  namespace: default
  labels:
    asya.sh/flow: plan-and-execute
    asya.sh/role: end
spec:
  actor: synthesizer
  image: examples.asya.sh/synthesizer:latest
  handler: synthesizer
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
