apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-executor.yaml
- asya-actor-planner.yaml
- asya-actor-re-planner.yaml
- asya-actor-synthesizer.yaml
- asya-router-plan-and-execute-if-current-step-lt-len-p-get-plan.yaml
- asya-router-plan-and-execute-seq-set-completed.yaml
- asya-router-plan-and-execute-while-current-step-lt-len-p-get-plan.yaml
- asya-start-plan-and-execute.yaml
- configmap-routers.yaml
