apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
patches:
- path: patch-actor-analyze.yaml
- path: patch-actor-summarize.yaml
- path: patch-start-text-flow.yaml
