x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "2"

services:
  postgres:
    image: postgres:16-alpine
    logging: *default-logging
    env_file:
    - envs/.env.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
