apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-write-report
  namespace: default
  labels:
    asya.sh/flow: research-and-refine
    asya.sh/role: end
spec:
  actor: actor-write-report
  image: examples.asya.sh/write-report:latest
  handler: research_and_refine.write_report
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
