apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-research-and-refine-seq-set-iteration
  namespace: default
  labels:
    asya.sh/flow: research-and-refine
    asya.sh/generated: 'true'
spec:
  actor: router-research-and-refine-seq-set-iteration
  image: python:3.13-slim
  handler: routers.router_research_and_refine_seq_set_iteration
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CRITIC
    value: critic
  - name: ASYA_HANDLER_ACTOR_REFINE_QUERY
    value: refine_query
  - name: ASYA_HANDLER_ACTOR_RESEARCHER
    value: researcher
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AND_REFINE_IF_ITERATION_GE_5
    value: routers.router_research_and_refine_if_iteration_ge_5
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AND_REFINE_IF_NOT_GAPS_OR_QUALITY_SCORE_GE_85
    value: routers.router_research_and_refine_if_not_gaps_or_quality_score_ge_85
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AND_REFINE_SEQ_SET_ITERATION
    value: routers.router_research_and_refine_seq_set_iteration
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AND_REFINE_WHILE_LOOP
    value: routers.router_research_and_refine_while_loop
  - name: ASYA_HANDLER_ACTOR_WRITE_REPORT
    value: write_report
