apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-research-and-refine-line-49-while-1
  namespace: default
  labels:
    asya.sh/flow: research-and-refine
    asya.sh/generated: 'true'
spec:
  actor: router-research-and-refine-line-49-while-1
  image: python:3.13-slim
  handler: routers.router_research_and_refine_line_49_while_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CRITIC
    value: critic
  - name: ASYA_HANDLER_ACTOR_REFINE_QUERY
    value: refine_query
  - name: ASYA_HANDLER_ACTOR_RESEARCHER
    value: researcher
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AND_REFINE_LINE_49_WHILE_1
    value: routers.router_research_and_refine_line_49_while_1
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AND_REFINE_LINE_50_SEQ_4
    value: routers.router_research_and_refine_line_50_seq_4
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AND_REFINE_LINE_54_IF_3
    value: routers.router_research_and_refine_line_54_if_3
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AND_REFINE_LINE_58_IF_2
    value: routers.router_research_and_refine_line_58_if_2
  - name: ASYA_HANDLER_ACTOR_WRITE_REPORT
    value: write_report
