apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: critic
  namespace: default
  labels:
    asya.sh/flow: research-and-refine
spec:
  actor: critic
  image: examples.asya.sh/critic:latest
  handler: critic
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
