apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-critic.yaml
- asya-actor-refine-query.yaml
- asya-actor-researcher.yaml
- asya-actor-write-report.yaml
- asya-router-research-and-refine-if-iteration-ge-5.yaml
- asya-router-research-and-refine-if-not-gaps-or-quality-score-ge-85.yaml
- asya-router-research-and-refine-seq-set-iteration.yaml
- asya-router-research-and-refine-while-loop.yaml
- asya-start-research-and-refine.yaml
- configmap-routers.yaml
