flowchart TD
    %% Flow: research_agent

    __end__((( )))
    router_research_agent_if_tool_name_eq_calculator{{router_research_agent_if_tool_name_eq_calculator}}
    router_research_agent_if_tool_name_eq_code_exec{{router_research_agent_if_tool_name_eq_code_exec}}
    router_research_agent_if_tool_name_eq_search{{router_research_agent_if_tool_name_eq_search}}
    router_research_agent_while_loop{{router_research_agent_while_loop}}
    start_research_agent(["start_research_agent<br/><br/>p['messages'] = p.get('messages', [])"])

    start_research_agent --> router_research_agent_while_loop
    router_research_agent_if_tool_name_eq_code_exec -->|"else"| __end__
    router_research_agent_if_tool_name_eq_calculator -->|"else"| router_research_agent_if_tool_name_eq_code_exec
    router_research_agent_if_tool_name_eq_search -->|"else"| router_research_agent_if_tool_name_eq_calculator
    router_research_agent_while_loop --> router_research_agent_if_tool_name_eq_search
    router_research_agent_if_tool_name_eq_code_exec --> router_research_agent_while_loop

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_research_agent start
    class __end__ endnode
    class router_research_agent_if_tool_name_eq_calculator,router_research_agent_if_tool_name_eq_code_exec,router_research_agent_if_tool_name_eq_search,router_research_agent_while_loop router
    linkStyle 1,2,3 stroke:#E07040