flowchart TD
    %% Flow: adaptive_flow

    classifier[classifier]
    end_adaptive_flow([end_adaptive_flow])
    formatter[formatter]
    router_adaptive_flow_line_16_if_2{{router_adaptive_flow_line_16_if_2}}
    router_adaptive_flow_line_17_fanout_1{{router_adaptive_flow_line_17_fanout_1}}
    sequential_analyzer[sequential_analyzer]
    start_adaptive_flow([start_adaptive_flow])

    start_adaptive_flow --> classifier
    classifier --> router_adaptive_flow_line_16_if_2
    router_adaptive_flow_line_16_if_2 -->|p['parallel']| router_adaptive_flow_line_17_fanout_1
    router_adaptive_flow_line_17_fanout_1 --> formatter
    router_adaptive_flow_line_16_if_2 -->|not (p['parallel'])| sequential_analyzer
    sequential_analyzer --> formatter
    formatter --> end_adaptive_flow