apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-ingestion-pipeline-except-connectionerror-timeouterror
  namespace: default
  labels:
    asya.sh/flow: ingestion-pipeline
    asya.sh/generated: 'true'
spec:
  actor: router-ingestion-pipeline-except-connectionerror-timeouterror
  image: python:3.13-slim
  handler: routers.router_ingestion_pipeline_except_connectionerror_timeouterror
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_FETCH_DATA
    value: fetch_data
  - name: ASYA_HANDLER_ACTOR_PARSE_DATA
    value: parse_data
  - name: ASYA_HANDLER_ACTOR_QUEUE_FOR_RETRY
    value: queue_for_retry
  - name: ASYA_HANDLER_ACTOR_REJECT_INPUT
    value: reject_input
