apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-ingestion-pipeline-line-19-seq-3
  namespace: default
  labels:
    asya.sh/flow: ingestion-pipeline
    asya.sh/generated: 'true'
spec:
  actor: router-ingestion-pipeline-line-19-seq-3
  image: python:3.13-slim
  handler: routers.router_ingestion_pipeline_line_19_seq_3
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_FETCH_DATA
    value: fetch_data
  - name: ASYA_HANDLER_PARSE_DATA
    value: parse_data
  - name: ASYA_HANDLER_QUEUE_FOR_RETRY
    value: queue_for_retry
  - name: ASYA_HANDLER_REJECT_INPUT
    value: reject_input
  - name: ASYA_HANDLER_ROUTER_INGESTION_PIPELINE_LINE_16_SEQ_1
    value: routers.router_ingestion_pipeline_line_16_seq_1
  - name: ASYA_HANDLER_ROUTER_INGESTION_PIPELINE_LINE_19_SEQ_3
    value: routers.router_ingestion_pipeline_line_19_seq_3
