apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-fetch-data.yaml
- asya-actor-parse-data.yaml
- asya-actor-queue-for-retry.yaml
- asya-actor-reject-input.yaml
- asya-router-ingestion-pipeline-except-connectionerror-timeouterror.yaml
- asya-router-ingestion-pipeline-except-valueerror-keyerror.yaml
- asya-start-ingestion-pipeline.yaml
- configmap-routers.yaml
