"""Generate Python code for routers."""

from datetime import datetime
from typing import List, Set

from asya_cli.scene.grouper import Router
from asya_cli.scene.ir import ActorCall


class CodeGenerator:
    def __init__(self, scene_name: str, routers: List[Router], source_file: str):
        self.scene_name = scene_name
        self.routers = routers
        self.source_file = source_file
        self.all_handlers: Set[str] = set()

    def generate(self) -> str:
        self._collect_handlers()

        parts = []
        parts.append(self._generate_header())
        parts.append(self._generate_env_vars_doc())
        parts.append(self._generate_routers())
        parts.append(self._generate_resolve_function())

        return "\n".join(parts)

    def _collect_handlers(self) -> None:
        for router in self.routers:
            self.all_handlers.add(router.name)
            for actor_name in router.true_branch_actors:
                self.all_handlers.add(actor_name)
            for actor_name in router.false_branch_actors:
                self.all_handlers.add(actor_name)

    def _generate_header(self) -> str:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return f'''
"""
Auto-generated by asya scene compiler
Source: {self.source_file}
Generated: {timestamp}

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya scene compile {self.source_file}
"""
'''

    def _generate_env_vars_doc(self) -> str:
        lines = []
        lines.append("\n# " + "=" * 70)
        lines.append("# Required Environment Variables for Router Deployment")
        lines.append("# " + "=" * 70)
        lines.append('"""')
        lines.append("Set these environment variables when deploying router actors:")
        lines.append("")

        for handler in sorted(self.all_handlers):
            env_name = handler.upper().replace("-", "_")
            lines.append(f'ASYA_HANDLER_{env_name}="{handler}"')

        lines.append("")
        lines.append("Example for Kubernetes:")
        lines.append("  env:")
        for handler in sorted(self.all_handlers):
            env_name = handler.upper().replace("-", "_")
            lines.append(f'    - name: ASYA_HANDLER_{env_name}')
            lines.append(f'      value: "{handler}"')
        lines.append('"""')
        lines.append("")

        return "\n".join(lines)

    def _generate_routers(self) -> str:
        lines = []
        lines.append("\n# " + "=" * 70)
        lines.append("# Generated Routers (for kubernetes deployment)")
        lines.append("# " + "=" * 70)
        lines.append("")

        for router in self.routers:
            if router.name.startswith("start_"):
                lines.append(self._generate_start_router(router))
            elif router.name.startswith("end_"):
                lines.append(self._generate_end_router(router))
            else:
                lines.append(self._generate_router(router))

        return "\n".join(lines)

    def _generate_start_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(envelope: dict) -> dict:")
        lines.append(f'    """Entrypoint for scene \'{self.scene_name}\'"""')
        lines.append("    r = envelope['route']")
        lines.append("    c = r['current']")
        lines.append("")

        if router.true_branch_actors:
            next_list = ", ".join([f'resolve("{name}")' for name in router.true_branch_actors])
            lines.append(f"    r['actors'][c+1:c+1] = [{next_list}]")
        lines.append("")
        lines.append("    return envelope")
        lines.append("")

        return "\n".join(lines)

    def _generate_end_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(envelope: dict) -> dict:")
        lines.append(f'    """Exitpoint for scene \'{self.scene_name}\'"""')
        lines.append("    return envelope")
        lines.append("")

        return "\n".join(lines)

    def _generate_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(envelope: dict) -> dict:")
        lines.append('    """Router for control flow and payload mutations"""')
        lines.append("    p = envelope['payload']")
        lines.append("    r = envelope['route']")
        lines.append("    c = r['current']")
        lines.append("    _next = []")
        lines.append("")

        for mutation in router.mutations:
            lines.append(f"    {mutation.code}")

        if router.condition:
            lines.append(f"    if {router.condition.test}:")
            if router.true_branch_actors:
                for actor in router.true_branch_actors:
                    lines.append(f'        _next.append(resolve("{actor}"))')
            else:
                lines.append("        pass")
            lines.append("    else:")
            if router.false_branch_actors:
                for actor in router.false_branch_actors:
                    lines.append(f'        _next.append(resolve("{actor}"))')
            else:
                lines.append("        pass")
        else:
            for actor in router.true_branch_actors:
                lines.append(f'    _next.append(resolve("{actor}"))')

        lines.append("    r['actors'][c+1:c+1] = _next")
        lines.append("    return envelope")
        lines.append("")

        return "\n".join(lines)

    def _generate_resolve_function(self) -> str:
        return '''# ======================================================================
# Handler Resolution
# ======================================================================


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler full name to actor name for routing.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="module.handler" or "module.Class.method"

    The reverse mapping (handler -> actor) is built once at first call and cached.

    Args:
        handler_full_name: Full qualified name like "module.handler" or "module.Class.method"

    Returns:
        Actor name for routing (kebab-case)

    Raises:
        ValueError: If handler not found in environment variables

    Examples:
        # Environment: ASYA_HANDLER_IMAGE_PROCESSOR="my_module.ImageProcessor.process"
        resolve("my_module.ImageProcessor.process")  # returns "image-processor"

        # Environment: ASYA_HANDLER_TEXT_ANALYZER="text.analyze"
        resolve("text.analyze")  # returns "text-analyzer"
    """
    import os, logging

    if not hasattr(resolve, '_handler_to_actor'):
        resolve._handler_to_actor = {}
        for env_var, handler_name in os.environ.items():
            if env_var.startswith('ASYA_HANDLER_'):
                actor_name = env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
                resolve._handler_to_actor[handler_name] = actor_name
        logging.info(f"Loaded {len(resolve._handler_to_actor)} handler-to-actor values from env vars")

    if handler_full_name not in resolve._handler_to_actor:
        raise ValueError(
            f"Handler '{handler_full_name}' not found in environment variables. "
            f'Expected ASYA_HANDLER_<ACTOR_NAME>="{handler_full_name}" to be set. '
            f"See loaded handlers mapping: {resolve._handler_to_actor}"
        )

    return resolve._handler_to_actor[handler_full_name]
'''
