"""
Code templates for Flow DSL compiler.

Contains templates for resolve() function and other generated code.
"""

import textwrap


def get_file_header(source_file: str) -> str:
    """Generate file header comment."""
    from datetime import datetime

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return textwrap.dedent(
        f'''
        """
        Auto-generated by asya flow compiler
        Source: {source_file}
        Generated: {timestamp}

        DO NOT EDIT THIS FILE MANUALLY
        Regenerate by running: asya flow compile {source_file}
        """'''
    )


def get_resolve_function() -> str:
    """
    Get resolve() function template.

    This function resolves handler full names to actor names for routing.
    Uses reverse lookup in ASYA_HANDLER_* environment variables.
    """
    return textwrap.dedent(
        '''
        def resolve(handler_full_name: str) -> str:
            """
            Resolve handler full name to actor name for routing.

            Looks up handler in environment variables:
            - ASYA_HANDLER_<ACTOR_NAME>="module.handler" or "module.Class.method"

            The reverse mapping (handler -> actor) is built once at first call and cached.

            Args:
                handler_full_name: Full qualified name like "module.handler" or "module.Class.method"

            Returns:
                Actor name for routing (kebab-case)

            Raises:
                ValueError: If handler not found in environment variables

            Examples:
                # Environment: ASYA_HANDLER_IMAGE_PROCESSOR="my_module.ImageProcessor.process"
                resolve("my_module.ImageProcessor.process")  # returns "image-processor"

                # Environment: ASYA_HANDLER_TEXT_ANALYZER="text.analyze"
                resolve("text.analyze")  # returns "text-analyzer"
            """
            import os, logging

            # Build reverse mapping: {handler_full_name: actor_name}
            if not hasattr(resolve, '_handler_to_actor'):
                resolve._handler_to_actor = {}
                for env_var, handler_name in os.environ.items():
                    if env_var.startswith('ASYA_HANDLER_'):
                        # Extract actor name: ASYA_HANDLER_IMAGE_PROCESSOR -> image-processor
                        actor_name = env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
                        resolve._handler_to_actor[handler_name] = actor_name
                logging.info(f"Loaded {len(resolve._handler_to_actor)} handler-to-actor values from env vars")

            if handler_full_name not in resolve._handler_to_actor:
                raise ValueError(
                    f"Handler '{handler_full_name}' not found in environment variables. "
                    f'Expected ASYA_HANDLER_<ACTOR_NAME>="{handler_full_name}" to be set. '
                    f"See loaded handlers mapping: {resolve._handler_to_actor}"
                )

            return resolve._handler_to_actor[handler_full_name]
    '''
    )
