apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-if-inside-while-flow-line-14-while-1
  namespace: default
  labels:
    asya.sh/flow: if-inside-while-flow
    asya.sh/generated: 'true'
spec:
  actor: router-if-inside-while-flow-line-14-while-1
  image: python:3.13-slim
  handler: routers.router_if_inside_while_flow_line_14_while_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ROUTER_IF_INSIDE_WHILE_FLOW_LINE_14_WHILE_1
    value: routers.router_if_inside_while_flow_line_14_while_1
  - name: ASYA_HANDLER_ROUTER_IF_INSIDE_WHILE_FLOW_LINE_16_IF_2
    value: routers.router_if_inside_while_flow_line_16_if_2
