apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-store-result
  namespace: default
  labels:
    asya.sh/flow: llm-pipeline
    asya.sh/role: end
spec:
  actor: actor-store-result
  image: examples.asya.sh/store-result:latest
  handler: store_result
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env:
  - name: ASYA_IGNORE_DECORATORS
    value: tenacity.retry
  resiliency:
    policies:
      default:
        maxAttempts: 3
        maxDuration: 300
