apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-enrich
  namespace: default
  labels:
    asya.sh/flow: main-flow
spec:
  actor: actor-enrich
  image: examples.asya.sh/enrich:latest
  handler: enrich
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
