apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-concise-writer
  namespace: default
  labels:
    asya.sh/flow: voting-ensemble
spec:
  actor: actor-concise-writer
  image: examples.asya.sh/concise-writer:latest
  handler: concise_writer
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
