apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-analytical-writer.yaml
- asyncactor-concise-writer.yaml
- asyncactor-creative-writer.yaml
- asyncactor-judge.yaml
- asyncactor-router-voting-ensemble-line-43-fanout-1.yaml
- asyncactor-start-voting-ensemble.yaml
- configmap-routers.yaml
