apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: debater-b
  namespace: default
  labels:
    asya.sh/flow: multi-agent-debate
spec:
  actor: debater-b
  image: examples.asya.sh/debater-b:latest
  handler: debater_b
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
