apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-multi-agent-debate-line-54-seq-7
  namespace: default
  labels:
    asya.sh/flow: multi-agent-debate
    asya.sh/generated: 'true'
spec:
  actor: router-multi-agent-debate-line-54-seq-7
  image: python:3.13-slim
  handler: routers.router_multi_agent_debate_line_54_seq_7
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_CONVERGENCE_CHECKER
    value: convergence_checker
  - name: ASYA_HANDLER_DEBATER_A
    value: debater_a
  - name: ASYA_HANDLER_DEBATER_B
    value: debater_b
  - name: ASYA_HANDLER_DEBATER_C
    value: debater_c
  - name: ASYA_HANDLER_FANIN_MULTI_AGENT_DEBATE_LINE_56
    value: routers.fanin_multi_agent_debate_line_56
  - name: ASYA_HANDLER_FANIN_MULTI_AGENT_DEBATE_LINE_75
    value: routers.fanin_multi_agent_debate_line_75
  - name: ASYA_HANDLER_FINAL_JUDGE
    value: final_judge
  - name: ASYA_HANDLER_REVISE_A
    value: revise_a
  - name: ASYA_HANDLER_REVISE_B
    value: revise_b
  - name: ASYA_HANDLER_REVISE_C
    value: revise_c
  - name: ASYA_HANDLER_ROUTER_MULTI_AGENT_DEBATE_LINE_56_FANOUT_6
    value: routers.router_multi_agent_debate_line_56_fanout_6
  - name: ASYA_HANDLER_ROUTER_MULTI_AGENT_DEBATE_LINE_64_WHILE_1
    value: routers.router_multi_agent_debate_line_64_while_1
  - name: ASYA_HANDLER_ROUTER_MULTI_AGENT_DEBATE_LINE_65_SEQ_5
    value: routers.router_multi_agent_debate_line_65_seq_5
  - name: ASYA_HANDLER_ROUTER_MULTI_AGENT_DEBATE_LINE_69_IF_4
    value: routers.router_multi_agent_debate_line_69_if_4
  - name: ASYA_HANDLER_ROUTER_MULTI_AGENT_DEBATE_LINE_72_IF_3
    value: routers.router_multi_agent_debate_line_72_if_3
  - name: ASYA_HANDLER_ROUTER_MULTI_AGENT_DEBATE_LINE_75_FANOUT_2
    value: routers.router_multi_agent_debate_line_75_fanout_2
