apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-convergence-checker.yaml
- asya-actor-debater-a.yaml
- asya-actor-debater-b.yaml
- asya-actor-debater-c.yaml
- asya-actor-final-judge.yaml
- asya-actor-revise-a.yaml
- asya-actor-revise-b.yaml
- asya-actor-revise-c.yaml
- asya-router-multi-agent-debate-fanout-positions-2.yaml
- asya-router-multi-agent-debate-fanout-positions.yaml
- asya-router-multi-agent-debate-if-converged.yaml
- asya-router-multi-agent-debate-if-round-ge-3.yaml
- asya-router-multi-agent-debate-seq-set-round-2.yaml
- asya-router-multi-agent-debate-seq-set-round.yaml
- asya-router-multi-agent-debate-while-loop.yaml
- asya-start-multi-agent-debate.yaml
- configmap-routers.yaml
