apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-convergence-checker.yaml
- asya-actor-debater-a.yaml
- asya-actor-debater-b.yaml
- asya-actor-debater-c.yaml
- asya-actor-final-judge.yaml
- asya-actor-revise-a.yaml
- asya-actor-revise-b.yaml
- asya-actor-revise-c.yaml
- asya-router-multi-agent-debate-line-54-seq-7.yaml
- asya-router-multi-agent-debate-line-56-fanout-6.yaml
- asya-router-multi-agent-debate-line-64-while-1.yaml
- asya-router-multi-agent-debate-line-65-seq-5.yaml
- asya-router-multi-agent-debate-line-69-if-4.yaml
- asya-router-multi-agent-debate-line-72-if-3.yaml
- asya-router-multi-agent-debate-line-75-fanout-2.yaml
- asya-start-multi-agent-debate.yaml
- configmap-routers.yaml
