flowchart TD
    %% Flow: content_pipeline_flow

    router_content_pipeline_flow_if_content_type_eq_image{{router_content_pipeline_flow_if_content_type_eq_image}}
    router_content_pipeline_flow_if_content_type_eq_text{{router_content_pipeline_flow_if_content_type_eq_text}}
    start_content_pipeline_flow([start_content_pipeline_flow])
    __end__((( )))

    start_content_pipeline_flow --> router_content_pipeline_flow_if_content_type_eq_text
    router_content_pipeline_flow_if_content_type_eq_text -->|"else"| router_content_pipeline_flow_if_content_type_eq_image
    router_content_pipeline_flow_if_content_type_eq_image --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_content_pipeline_flow start
    class __end__ endnode
    class router_content_pipeline_flow_if_content_type_eq_image,router_content_pipeline_flow_if_content_type_eq_text router
    linkStyle 1 stroke:#E07040