flowchart TD
    %% Flow: content_pipeline_flow

    classifier[classifier]
    end_content_pipeline_flow([end_content_pipeline_flow])
    generic_processor[generic_processor]
    image_processor[image_processor]
    quality_check[quality_check]
    router_content_pipeline_flow_line_16_if_2{{router_content_pipeline_flow_line_16_if_2}}
    router_content_pipeline_flow_line_18_if_1{{router_content_pipeline_flow_line_18_if_1}}
    start_content_pipeline_flow([start_content_pipeline_flow])
    text_processor[text_processor]

    start_content_pipeline_flow --> classifier
    start_content_pipeline_flow --> router_content_pipeline_flow_line_16_if_2
    router_content_pipeline_flow_line_18_if_1 --> image_processor
    router_content_pipeline_flow_line_18_if_1 --> generic_processor
    router_content_pipeline_flow_line_16_if_2 --> text_processor
    router_content_pipeline_flow_line_16_if_2 --> quality_check
    router_content_pipeline_flow_line_16_if_2 --> router_content_pipeline_flow_line_18_if_1
    router_content_pipeline_flow_line_16_if_2 --> quality_check