apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-d
  namespace: default
  labels:
    asya.sh/flow: conditional-nested-flow
spec:
  actor: actor-handler-d
  image: examples.asya.sh/handler-d:latest
  handler: if_nested.handler_d
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
