apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-conditional-nested-flow-line-10-seq-10
  namespace: default
  labels:
    asya.sh/flow: conditional-nested-flow
    asya.sh/generated: 'true'
spec:
  actor: router-conditional-nested-flow-line-10-seq-10
  image: python:3.13-slim
  handler: routers.router_conditional_nested_flow_line_10_seq_10
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_A
    value: handler_a
  - name: ASYA_HANDLER_ACTOR_HANDLER_B
    value: handler_b
  - name: ASYA_HANDLER_ACTOR_HANDLER_C
    value: handler_c
  - name: ASYA_HANDLER_ACTOR_HANDLER_D
    value: handler_d
  - name: ASYA_HANDLER_ACTOR_HANDLER_FINALIZE
    value: handler_finalize
  - name: ASYA_HANDLER_ACTOR_HANDLER_VALIDATE_INPUT
    value: handler_validate_input
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_10_SEQ_10
    value: routers.router_conditional_nested_flow_line_10_seq_10
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_12_IF_9
    value: routers.router_conditional_nested_flow_line_12_if_9
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_15_IF_6
    value: routers.router_conditional_nested_flow_line_15_if_6
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_16_SEQ_4
    value: routers.router_conditional_nested_flow_line_16_seq_4
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_18_SEQ_3
    value: routers.router_conditional_nested_flow_line_18_seq_3
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_20_SEQ_5
    value: routers.router_conditional_nested_flow_line_20_seq_5
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_23_SEQ_8
    value: routers.router_conditional_nested_flow_line_23_seq_8
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_25_SEQ_7
    value: routers.router_conditional_nested_flow_line_25_seq_7
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_27_SEQ_2
    value: routers.router_conditional_nested_flow_line_27_seq_2
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_29_SEQ_1
    value: routers.router_conditional_nested_flow_line_29_seq_1
  - name: ASYA_HANDLER_ROUTER_CONDITIONAL_NESTED_FLOW_LINE_9_IF_11
    value: routers.router_conditional_nested_flow_line_9_if_11
