apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: handler-validate-input
  namespace: default
  labels:
    asya.sh/flow: conditional-nested-flow
spec:
  actor: handler-validate-input
  image: examples.asya.sh/handler-validate-input:latest
  handler: handler_validate_input
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
