apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handler-a.yaml
- asya-actor-handler-b.yaml
- asya-actor-handler-c.yaml
- asya-actor-handler-d.yaml
- asya-actor-handler-finalize.yaml
- asya-actor-handler-validate-input.yaml
- asya-router-conditional-nested-flow-if-a-eq-a.yaml
- asya-router-conditional-nested-flow-if-x-gt-2-2.yaml
- asya-router-conditional-nested-flow-if-x-gt-2.yaml
- asya-router-conditional-nested-flow-seq-set-x-2.yaml
- asya-router-conditional-nested-flow-seq-set-x-3.yaml
- asya-router-conditional-nested-flow-seq-set-x-4.yaml
- asya-router-conditional-nested-flow-seq-set-x-5.yaml
- asya-router-conditional-nested-flow-seq-set-x-6.yaml
- asya-router-conditional-nested-flow-seq-set-x-7.yaml
- asya-router-conditional-nested-flow-seq-set-x-8.yaml
- asya-router-conditional-nested-flow-seq-set-x.yaml
- asya-start-conditional-nested-flow.yaml
- configmap-routers.yaml
