flowchart TD
    %% Flow: text_flow

    analyze[analyze]
    start_text_flow([start_text_flow])
    summarize[summarize]
    __end__((( )))

    start_text_flow --> analyze
    analyze --> summarize
    summarize --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_text_flow start
    class summarize endnode
    class analyze handler
    class __end__ endpoint