# octocov configuration for coverage reporting
# https://github.com/k1LoW/octocov
#
# Coverage directory structure:
# .coverage/<mirrored-project-path>/<coverage-files>
# - Unit tests: cov.out (Go) or cov.json (Python)
# - Integration tests: cov.out (Go) or cov.json (Python)
# - Component tests: cov.json (Python)
# - E2E tests: cov.json (Python)
# - Special cases: cov-payload.json, cov-envelope.json (gateway-actors has 2 modes)
#
# Note: octocov automatically shows changed files coverage in PR comments when
# both report and diff datastores are configured (PR #67 feature)

coverage:
  paths:
  # Unit tests (Go)
  - .coverage/src/asya-sidecar/cov.out
  - .coverage/src/asya-gateway/cov.out
  - .coverage/src/asya-operator/cov.out
  # Unit tests (Python)
  - .coverage/src/asya-runtime/cov.json
  - .coverage/src/asya-crew/cov.json
  # Component tests (Go)
  - .coverage/testing/component/operator/transport_metrics/cov.out
  - .coverage/testing/component/operator/runtime_configmap/cov.out
  - .coverage/testing/component/gateway/cov-*.out
  # Component tests (Python)
  - .coverage/testing/component/gateway/cov-*.json
  - .coverage/testing/component/sidecar/cov-*.json
  - .coverage/testing/component/runtime/cov-*.json
  # Integration tests (Go)
  - .coverage/testing/integration/sidecar/cov.out
  - .coverage/testing/integration/gateway/cov.out
  - .coverage/testing/integration/operator/cov.out
  # Integration tests (Python)
  - .coverage/testing/integration/sidecar-runtime/cov-*.json
  - .coverage/testing/integration/gateway-actors/cov-*.json
  # E2E tests (Python)
  - .coverage/testing/e2e/cov-*.json
  badge:
    path: docs/coverage.svg

comment:
  if: is_pull_request
  deletePrevious: true
  hideFooterLink: true

diff:
  if: is_pull_request
  datastores:
  - artifact://${GITHUB_REPOSITORY}

# Store reports for diff comparison (both PR and main branch)
report:
  datastores:
  - artifact://${GITHUB_REPOSITORY}

# Test execution time tracking (from GitHub Actions)
testExecutionTime:
  steps:
  - "Run unit tests"
  - "Run component tests"
  - "Run simple integration tests"
  - "Run 2-parametrized integration tests.*"
  - "Run 3-parametrized integration tests.*"
  - "Run E2E tests.*"
  badge:
    path: docs/time.svg

# Set coverage thresholds
# - current >= 75%: Overall coverage must be at least 75%
# - diff >= 0%: Coverage must not decrease (no regression allowed)
acceptable:
  coverage: current >= 75% && diff >= 0%

# Disable code-to-test ratio (not needed for this project)
codeToTestRatio:
  code:
  - '!**/*'
  test:
  - '!**/*'
