apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-typeddict-pipeline
  namespace: default
  labels:
    asya.sh/flow: typeddict-pipeline
    asya.sh/role: start
    asya.sh/generated: 'true'
spec:
  actor: start-typeddict-pipeline
  image: python:3.13-slim
  handler: routers.start_typeddict_pipeline
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_ERROR_HANDLER
    value: typed_dict_pipeline.error_handler
  - name: ASYA_HANDLER_ACTOR_PARSER
    value: typed_dict_pipeline.parser
  - name: ASYA_HANDLER_ROUTER_TYPEDDICT_PIPELINE_IF_NOT_VALID
    value: routers.router_typeddict_pipeline_if_not_valid
  - name: ASYA_HANDLER_ACTOR_SINK_ADAPTER
    value: typed_dict_pipeline.sink_adapter
  - name: ASYA_HANDLER_ACTOR_TRANSFORMER
    value: typed_dict_pipeline.transformer
  - name: ASYA_HANDLER_ACTOR_VALIDATOR
    value: typed_dict_pipeline.validator
  volumes:
  - name: routers
    configMap:
      name: typeddict-pipeline-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
