apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: parser
  namespace: default
  labels:
    asya.sh/flow: typeddict-pipeline
spec:
  actor: parser
  image: examples.asya.sh/parser:latest
  handler: parser
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
