apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: error-handler
  namespace: default
  labels:
    asya.sh/flow: typeddict-pipeline
    asya.sh/role: end
spec:
  actor: error-handler
  image: examples.asya.sh/error-handler:latest
  handler: error_handler
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
