apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-error-handler.yaml
- asyncactor-parser.yaml
- asyncactor-router-typeddict-pipeline-line-76-if-1.yaml
- asyncactor-sink-adapter.yaml
- asyncactor-start-typeddict-pipeline.yaml
- asyncactor-transformer.yaml
- asyncactor-validator.yaml
- configmap-routers.yaml
