apiVersion: v1
kind: ConfigMap
metadata:
  name: asya-flow-greet-flow-config
  labels:
    asya.sh/flow: greet-flow
    asya.sh/config-type: flows
    asya.sh/managed-by: asya-lab
data:
  greet-flow.yaml: "flows:\n- name: greet-flow\n  entrypoint: start-greet-flow\n \
    \ description: Analyze text\n  a2a: {}\n"
