apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asya-demo
resources:
- ../base
- flow-expose.yaml
configurations:
- kustomizeconfig.yaml
patches:
- path: patch-actor-greet.yaml
- path: patch-actor-shout.yaml
- path: patch-start-greet-flow.yaml
