apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-multi-stage-flow-fanout-reviews
  namespace: default
  labels:
    asya.sh/flow: multi-stage-flow
    asya.sh/generated: 'true'
spec:
  actor: router-multi-stage-flow-fanout-reviews
  image: python:3.13-slim
  handler: routers.router_multi_stage_flow_fanout_reviews
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_FANIN_MULTI_STAGE_FLOW_RESEARCH
    value: routers.fanin_multi_stage_flow_research
  - name: ASYA_HANDLER_FANIN_MULTI_STAGE_FLOW_REVIEWS
    value: routers.fanin_multi_stage_flow_reviews
  - name: ASYA_HANDLER_ACTOR_RESEARCH_AGENT
    value: research_agent
  - name: ASYA_HANDLER_ACTOR_REVIEW_AGENT
    value: review_agent
  - name: ASYA_HANDLER_ROUTER_MULTI_STAGE_FLOW_FANOUT_RESEARCH
    value: routers.router_multi_stage_flow_fanout_research
  - name: ASYA_HANDLER_ROUTER_MULTI_STAGE_FLOW_FANOUT_REVIEWS
    value: routers.router_multi_stage_flow_fanout_reviews
  - name: ASYA_HANDLER_ACTOR_SUMMARIZER
    value: summarizer
