flowchart TD
    %% Flow: early_return_flow

    handler_error([handler_error])
    handler_finalize([handler_finalize])
    handler_process[handler_process]
    handler_validate[handler_validate]
    router_early_return_flow_line_14_if_1{{router_early_return_flow_line_14_if_1}}
    start_early_return_flow([start_early_return_flow])

    start_early_return_flow --> handler_validate
    handler_validate --> router_early_return_flow_line_14_if_1
    router_early_return_flow_line_14_if_1 -->|not (not p['valid'])| handler_process
    handler_process --> handler_finalize
    router_early_return_flow_line_14_if_1 -->|not p['valid']| handler_error