apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-research-agent-line-15-while-1
  namespace: default
  labels:
    asya.sh/flow: research-agent
    asya.sh/generated: 'true'
spec:
  actor: router-research-agent-line-15-while-1
  image: python:3.13-slim
  handler: routers.router_research_agent_line_15_while_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CALCULATOR
    value: calculator
  - name: ASYA_HANDLER_ACTOR_CODE_EXECUTOR
    value: code_executor
  - name: ASYA_HANDLER_ACTOR_LLM_CALL
    value: llm_call
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AGENT_LINE_15_WHILE_1
    value: routers.router_research_agent_line_15_while_1
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AGENT_LINE_17_IF_4
    value: routers.router_research_agent_line_17_if_4
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AGENT_LINE_19_IF_3
    value: routers.router_research_agent_line_19_if_3
  - name: ASYA_HANDLER_ROUTER_RESEARCH_AGENT_LINE_21_IF_2
    value: routers.router_research_agent_line_21_if_2
  - name: ASYA_HANDLER_ACTOR_WEB_SEARCH
    value: web_search
