apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-calculator.yaml
- asya-actor-code-executor.yaml
- asya-actor-llm-call.yaml
- asya-actor-web-search.yaml
- asya-router-research-agent-line-14-seq-5.yaml
- asya-router-research-agent-line-15-while-1.yaml
- asya-router-research-agent-line-17-if-4.yaml
- asya-router-research-agent-line-19-if-3.yaml
- asya-router-research-agent-line-21-if-2.yaml
- asya-start-research-agent.yaml
- configmap-routers.yaml
