apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-evaluator-optimizer-line-56-seq-5
  namespace: default
  labels:
    asya.sh/flow: evaluator-optimizer
    asya.sh/generated: 'true'
spec:
  actor: router-evaluator-optimizer-line-56-seq-5
  image: python:3.13-slim
  handler: routers.router_evaluator_optimizer_line_56_seq_5
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_EVALUATOR
    value: evaluator
  - name: ASYA_HANDLER_ACTOR_GENERATOR
    value: generator
  - name: ASYA_HANDLER_ACTOR_POLISHER
    value: polisher
  - name: ASYA_HANDLER_ROUTER_EVALUATOR_OPTIMIZER_LINE_58_WHILE_1
    value: routers.router_evaluator_optimizer_line_58_while_1
  - name: ASYA_HANDLER_ROUTER_EVALUATOR_OPTIMIZER_LINE_59_SEQ_4
    value: routers.router_evaluator_optimizer_line_59_seq_4
  - name: ASYA_HANDLER_ROUTER_EVALUATOR_OPTIMIZER_LINE_68_IF_3
    value: routers.router_evaluator_optimizer_line_68_if_3
  - name: ASYA_HANDLER_ROUTER_EVALUATOR_OPTIMIZER_LINE_72_IF_2
    value: routers.router_evaluator_optimizer_line_72_if_2
