apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-test-nested-flow
  namespace: asya-e2e
spec:
  actor: start-test-nested-flow
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.start_test_nested_flow
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-9-if-7
  namespace: asya-e2e
spec:
  actor: router-test-nested-flow-line-9-if-7
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.router_test_nested_flow_line_9_if_7
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-11-if-3
  namespace: asya-e2e
spec:
  actor: router-test-nested-flow-line-11-if-3
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.router_test_nested_flow_line_11_if_3
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-12-seq-1
  namespace: asya-e2e
spec:
  actor: router-test-nested-flow-line-12-seq-1
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.router_test_nested_flow_line_12_seq_1
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-15-seq-2
  namespace: asya-e2e
spec:
  actor: router-test-nested-flow-line-15-seq-2
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.router_test_nested_flow_line_15_seq_2
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-19-if-6
  namespace: asya-e2e
spec:
  actor: router-test-nested-flow-line-19-if-6
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.router_test_nested_flow_line_19_if_6
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-20-seq-4
  namespace: asya-e2e
spec:
  actor: router-test-nested-flow-line-20-seq-4
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.router_test_nested_flow_line_20_seq_4
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-23-seq-5
  namespace: asya-e2e
spec:
  actor: router-test-nested-flow-line-23-seq-5
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.router_test_nested_flow_line_23_seq_5
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: end-test-nested-flow
  namespace: asya-e2e
spec:
  actor: end-test-nested-flow
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.compiled_routers.end_test_nested_flow
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: validate-input
  namespace: asya-e2e
spec:
  actor: validate-input
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.flow.validate_input
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: route-a-x
  namespace: asya-e2e
spec:
  actor: route-a-x
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.flow.route_a_x
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: route-a-y
  namespace: asya-e2e
spec:
  actor: route-a-y
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.flow.route_a_y
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: route-b-x
  namespace: asya-e2e
spec:
  actor: route-b-x
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.flow.route_b_x
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: route-b-y
  namespace: asya-e2e
spec:
  actor: route-b-y
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.flow.route_b_y
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: finalize-result
  namespace: asya-e2e
spec:
  actor: finalize-result
  scaling:
    enabled: true
    minReplicaCount: 1
    maxReplicaCount: 5
    queueLength: 5

  image: IMAGE_PLACEHOLDER
  imagePullPolicy: IfNotPresent
  handler: testing.e2e.flows.nested_if.flow.finalize_result
