flowchart TD
    %% Flow: ingester

    end_ingester([end_ingester])
    router_ingester_line_181_seq_1{{router_ingester_line_181_seq_1}}
    start_ingester([start_ingester])

    start_ingester --> router_ingester_line_181_seq_1
    router_ingester_line_181_seq_1 --> end_ingester