apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-api-pipeline-line-30-seq-1
  namespace: default
  labels:
    asya.sh/flow: api-pipeline
    asya.sh/generated: 'true'
spec:
  actor: router-api-pipeline-line-30-seq-1
  image: python:3.13-slim
  handler: routers.router_api_pipeline_line_30_seq_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_FETCH_FROM_API
    value: fetch_from_api
  - name: ASYA_HANDLER_ACTOR_PROCESS_RESPONSE
    value: process_response
  - name: ASYA_HANDLER_ACTOR_STORE_RESULTS
    value: store_results
