apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-fetch-from-api.yaml
- asya-actor-process-response.yaml
- asya-actor-store-results.yaml
- asya-router-api-pipeline-line-30-seq-1.yaml
- asya-start-api-pipeline.yaml
- configmap-routers.yaml
