apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-type-a
  namespace: default
  labels:
    asya.sh/flow: sample-flow
spec:
  actor: actor-handler-type-a
  image: examples.asya.sh/handler-type-a:latest
  handler: handler_type_a
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
