apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-sample-flow-seq-set-branch-2
  namespace: default
  labels:
    asya.sh/flow: sample-flow
    asya.sh/generated: 'true'
spec:
  actor: router-sample-flow-seq-set-branch-2
  image: python:3.13-slim
  handler: routers.router_sample_flow_seq_set_branch_2
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_FINALIZE
    value: handler_finalize
  - name: ASYA_HANDLER_ACTOR_HANDLER_SETUP
    value: handler_setup
  - name: ASYA_HANDLER_ACTOR_HANDLER_TYPE_A
    value: handler_type_a
  - name: ASYA_HANDLER_ACTOR_HANDLER_TYPE_B
    value: handler_type_b
  - name: ASYA_HANDLER_ROUTER_SAMPLE_FLOW_IF_TYPE_EQ_A
    value: routers.router_sample_flow_if_type_eq_a
  - name: ASYA_HANDLER_ROUTER_SAMPLE_FLOW_SEQ_SET_BRANCH
    value: routers.router_sample_flow_seq_set_branch
  - name: ASYA_HANDLER_ROUTER_SAMPLE_FLOW_SEQ_SET_BRANCH_2
    value: routers.router_sample_flow_seq_set_branch_2
