apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-analyze
  namespace: default
  labels:
    asya.sh/flow: text-flow
spec:
  actor: actor-analyze
  image: src-team-a-proper-package
  handler: nlp.analyzer.analyze
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
