flowchart TD
    %% Flow: decorator_inline_comments

    classifier[classifier]
    fast_handler[fast_handler]
    router_decorator_inline_comments_flow_line_16_seq_2{{router_decorator_inline_comments_flow_line_16_seq_2}}
    router_decorator_inline_comments_flow_line_18_if_1{{router_decorator_inline_comments_flow_line_18_if_1}}
    standard_handler[standard_handler]
    start_decorator_inline_comments_flow([start_decorator_inline_comments_flow])
    __end__((( )))

    start_decorator_inline_comments_flow --> router_decorator_inline_comments_flow_line_16_seq_2
    router_decorator_inline_comments_flow_line_18_if_1 -->|p['category'] == 'priority'| fast_handler
    router_decorator_inline_comments_flow_line_18_if_1 -->|not (p['category'] == 'priority')| standard_handler
    router_decorator_inline_comments_flow_line_16_seq_2 --> classifier
    classifier --> router_decorator_inline_comments_flow_line_18_if_1
    fast_handler --> __end__
    standard_handler --> __end__