apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-fetch-data.yaml
- asya-actor-store-results.yaml
- asya-actor-transform-data.yaml
- asya-router-resilient-pipeline-seq-set-status.yaml
- asya-start-resilient-pipeline.yaml
- configmap-routers.yaml
