apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-agent-with-tools-while-loop
  namespace: default
  labels:
    asya.sh/flow: agent-with-tools
    asya.sh/generated: 'true'
spec:
  actor: router-agent-with-tools-while-loop
  image: python:3.13-slim
  handler: routers.router_agent_with_tools_while_loop
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_EXECUTE_TOOL
    value: execute_tool
  - name: ASYA_HANDLER_ACTOR_LLM_CALL
    value: llm_call
  - name: ASYA_HANDLER_ROUTER_AGENT_WITH_TOOLS_IF_TOOL_CALLS
    value: routers.router_agent_with_tools_if_tool_calls
  - name: ASYA_HANDLER_ROUTER_AGENT_WITH_TOOLS_WHILE_LOOP
    value: routers.router_agent_with_tools_while_loop
