apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: execute-tool
  namespace: default
  labels:
    asya.sh/flow: agent-with-tools
spec:
  actor: execute-tool
  image: examples.asya.sh/execute-tool:latest
  handler: execute_tool
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
