apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-execute-tool.yaml
- asyncactor-router-agent-with-tools-line-16-seq-3.yaml
- asyncactor-router-agent-with-tools-line-17-while-1.yaml
- asyncactor-router-agent-with-tools-line-19-if-2.yaml
- asyncactor-start-agent-with-tools.yaml
- configmap-routers.yaml
