apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-analysis-flow
  namespace: default
  labels:
    asya.sh/flow: analysis-flow
    asya.sh/role: start
    asya.sh/generated: 'true'
spec:
  actor: start-analysis-flow
  image: python:3.13-slim
  handler: routers.start_analysis_flow
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_ENTITY_RECOGNIZER
    value: entity_recognizer
  - name: ASYA_HANDLER_FANIN_ANALYSIS_FLOW_ANALYSIS
    value: routers.fanin_analysis_flow_analysis
  - name: ASYA_HANDLER_ACTOR_MERGE_ANALYSIS
    value: merge_analysis
  - name: ASYA_HANDLER_ROUTER_ANALYSIS_FLOW_FANOUT_ANALYSIS
    value: routers.router_analysis_flow_fanout_analysis
  - name: ASYA_HANDLER_ACTOR_SENTIMENT_ANALYZER
    value: sentiment_analyzer
  - name: ASYA_HANDLER_ACTOR_TOPIC_EXTRACTOR
    value: topic_extractor
