apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-entity-recognizer.yaml
- asyncactor-router-analysis-flow-line-13-fanout-1.yaml
- asyncactor-sentiment-analyzer.yaml
- asyncactor-start-analysis-flow.yaml
- asyncactor-topic-extractor.yaml
- configmap-routers.yaml
