apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-fetch-data
  namespace: default
  labels:
    asya.sh/flow: nested-error-handling
spec:
  actor: actor-fetch-data
  image: examples.asya.sh/fetch-data:latest
  handler: fetch_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
  resiliency:
    policies:
      try_except_line_24_0:
        maxAttempts: 1
        thenRoute:
        - router-nested-error-handling-line-33-except-2
    rules:
    - errors:
      - ConnectionError
      policy: try_except_line_24_0
