apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-fetch-data
  namespace: default
  labels:
    asya.sh/flow: nested-error-handling
spec:
  actor: actor-fetch-data
  image: examples.asya.sh/fetch-data:latest
  handler: fetch_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
  resiliency:
    policies:
      except_connectionerror:
        maxAttempts: 1
        thenRoute:
        - router-nested-error-handling-except-connectionerror
    rules:
    - errors:
      - ConnectionError
      policy: except_connectionerror
