apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handle-parse-error
  namespace: default
  labels:
    asya.sh/flow: nested-error-handling
spec:
  actor: actor-handle-parse-error
  image: examples.asya.sh/handle-parse-error:latest
  handler: handle_parse_error
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
