apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-parse-data
  namespace: default
  labels:
    asya.sh/flow: nested-error-handling
spec:
  actor: actor-parse-data
  image: examples.asya.sh/parse-data:latest
  handler: parse_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
  resiliency:
    policies:
      except_connectionerror:
        maxAttempts: 1
        thenRoute:
        - router-nested-error-handling-except-connectionerror
      except_valueerror:
        maxAttempts: 1
        thenRoute:
        - router-nested-error-handling-except-valueerror
    rules:
    - errors:
      - ConnectionError
      policy: except_connectionerror
    - errors:
      - ValueError
      policy: except_valueerror
