apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-cleanup.yaml
- asya-actor-fetch-data.yaml
- asya-actor-handle-connection-error.yaml
- asya-actor-handle-parse-error.yaml
- asya-actor-parse-data.yaml
- asya-actor-store-results.yaml
- asya-actor-transform-data.yaml
- asya-actor-validate-data.yaml
- asya-router-nested-error-handling-except-connectionerror.yaml
- asya-router-nested-error-handling-except-valueerror.yaml
- asya-start-nested-error-handling.yaml
- configmap-routers.yaml
