apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: vertex-ai
  labels:
    asya.sh/flavor: vertex-ai
data:
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /secrets/gcp/sa-key.json
  - name: VERTEXAI_PROJECT
    value: "foodsci-img-gen-dev-1407-1448"
  - name: VERTEXAI_LOCATION
    value: europe-west1
  volumes:
  - name: gcp-creds
    secret:
      secretName: asya-actor-creds
  volumeMounts:
  - name: gcp-creds
    mountPath: /secrets/gcp
    readOnly: true
