apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-text-improver-line-21-seq
  namespace: asya-demo
  labels:
    asya.sh/flow: text-improver
    asya.sh/flow-role: router
spec:
  compositionSelector:
    matchLabels:
      asya.sh/transport: sqs
  actor: router-text-improver-line-21-seq
  image: python:3.13-slim
  handler: routers.router_text_improver_line_21_seq
  transport: sqs
  env:
  - name: PYTHONPATH
    value: /app
  - name: ASYA_HANDLER_GENERATOR
    value: demo_actors.generator.generator
  - name: ASYA_HANDLER_EVALUATOR
    value: demo_actors.evaluator.evaluator
  - name: ASYA_HANDLER_ROUTER_TEXT_IMPROVER_LINE_26_IF
    value: routers.router_text_improver_line_26_if
  volumes:
  - name: handler
    configMap:
      name: text-improver-routers
  volumeMounts:
  - name: handler
    mountPath: /app
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
