apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handler-finalize.yaml
- asya-actor-handler-init.yaml
- asya-actor-handler-process.yaml
- asya-router-while-mutations-in-loop-flow-line-13-seq-4.yaml
- asya-router-while-mutations-in-loop-flow-line-15-while-1.yaml
- asya-router-while-mutations-in-loop-flow-line-16-seq-3.yaml
- asya-router-while-mutations-in-loop-flow-line-20-seq-2.yaml
- asya-start-while-mutations-in-loop-flow.yaml
- configmap-routers.yaml
