flowchart TD
    %% Flow: decorator_definitions_flow

    enrich[enrich]
    start_decorator_definitions_flow([start_decorator_definitions_flow])
    validate[validate]
    __end__((( )))

    start_decorator_definitions_flow --> validate
    validate --> enrich
    enrich --> __end__