apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-risk-evaluator
  namespace: default
  labels:
    asya.sh/flow: sequential-pipeline
    asya.sh/role: end
spec:
  actor: actor-risk-evaluator
  image: examples.asya.sh/risk-evaluator:latest
  handler: risk_evaluator
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
