apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-data-analyst
  namespace: default
  labels:
    asya.sh/flow: sequential-pipeline
spec:
  actor: actor-data-analyst
  image: examples.asya.sh/data-analyst:latest
  handler: sequential_pipeline.data_analyst
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
