apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: data-analyst
  namespace: default
  labels:
    asya.sh/flow: sequential-pipeline
spec:
  actor: data-analyst
  image: examples.asya.sh/data-analyst:latest
  handler: data_analyst
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
