apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-data-analyst.yaml
- asyncactor-execution-planner.yaml
- asyncactor-risk-evaluator.yaml
- asyncactor-start-sequential-pipeline.yaml
- asyncactor-trading-analyst.yaml
- configmap-routers.yaml
