apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-typed-pydantic-pipeline-seq-set-candidates
  namespace: default
  labels:
    asya.sh/flow: typed-pydantic-pipeline
    asya.sh/generated: 'true'
spec:
  actor: router-typed-pydantic-pipeline-seq-set-candidates
  image: python:3.13-slim
  handler: routers.router_typed_pydantic_pipeline_seq_set_candidates
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_RANKER
    value: ranker
  - name: ASYA_HANDLER_ACTOR_RESPONDER
    value: responder
  - name: ASYA_HANDLER_ACTOR_SCORER
    value: scorer
