apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-responder
  namespace: default
  labels:
    asya.sh/flow: typed-pydantic-pipeline
    asya.sh/role: end
spec:
  actor: actor-responder
  image: examples.asya.sh/responder:latest
  handler: typed_pydantic_pipeline.responder
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
