apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-process-bank-transfer
  namespace: default
  labels:
    asya.sh/flow: payment-flow
spec:
  actor: actor-process-bank-transfer
  image: examples.asya.sh/process-bank-transfer:latest
  handler: process_bank_transfer
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
  resiliency:
    policies:
      except_valueerror:
        maxAttempts: 1
        thenRoute:
        - router-payment-flow-except-valueerror
    rules:
    - errors:
      - ValueError
      policy: except_valueerror
