apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-process-bank-transfer
  namespace: default
  labels:
    asya.sh/flow: payment-flow
spec:
  actor: actor-process-bank-transfer
  image: examples.asya.sh/process-bank-transfer:latest
  handler: process_bank_transfer
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
  resiliency:
    policies:
      try_except_line_16_0:
        maxAttempts: 1
        thenRoute:
        - router-payment-flow-line-22-except-1
    rules:
    - errors:
      - ValueError
      policy: try_except_line_16_0
