apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-audit-log.yaml
- asya-actor-charge-card.yaml
- asya-actor-notify-payment-failure.yaml
- asya-actor-process-bank-transfer.yaml
- asya-actor-record-transaction.yaml
- asya-actor-send-receipt.yaml
- asya-actor-validate-payment.yaml
- asya-router-payment-flow-except-valueerror.yaml
- asya-router-payment-flow-if-method-eq-card.yaml
- asya-start-payment-flow.yaml
- configmap-routers.yaml
