apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-setup
  namespace: default
  labels:
    asya.sh/flow: if-mutations-in-branches-flow
spec:
  actor: actor-handler-setup
  image: examples.asya.sh/handler-setup:latest
  handler: if_mutations_in_branches.handler_setup
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
