apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-polish
  labels:
    asya.sh/flow: text-improver
    asya.sh/role: end
spec:
  actor: actor-polish
  image: demo-kubecon
  handler: adapter_polish.adapter_polish
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 10
  env:
  - name: PYTHONUNBUFFERED
    value: '1'
  volumes:
  - name: adapter
    configMap:
      name: text-improver-polish-adapter
  volumeMounts:
  - name: adapter
    mountPath: /opt/asya/adapter_polish.py
    subPath: adapter_polish.py
    readOnly: true
