apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-research
  labels:
    asya.sh/flow: text-improver
spec:
  actor: actor-research
  image: demo-kubecon
  handler: actors.research.research
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 10
  env:
  - name: PYTHONUNBUFFERED
    value: '1'
