apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-generate
  labels:
    asya.sh/flow: text-improver
spec:
  actor: actor-generate
  image: demo-kubecon
  handler: adapter_generate.adapter_generate
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 10
  env:
  - name: PYTHONUNBUFFERED
    value: '1'
  volumes:
  - name: adapter
    configMap:
      name: text-improver-generate-adapter
  volumeMounts:
  - name: adapter
    mountPath: /opt/asya/adapter_generate.py
    subPath: adapter_generate.py
    readOnly: true
