flowchart TD
    %% Flow: sequential_pipeline

    data_analyst[data_analyst]
    end_sequential_pipeline([end_sequential_pipeline])
    execution_planner[execution_planner]
    risk_evaluator[risk_evaluator]
    start_sequential_pipeline([start_sequential_pipeline])
    trading_analyst[trading_analyst]

    start_sequential_pipeline --> data_analyst
    start_sequential_pipeline --> trading_analyst
    start_sequential_pipeline --> execution_planner
    start_sequential_pipeline --> risk_evaluator