apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-if-no-else-flow-line-13-if-1
  namespace: default
  labels:
    asya.sh/flow: if-no-else-flow
    asya.sh/generated: 'true'
spec:
  actor: router-if-no-else-flow-line-13-if-1
  image: python:3.13-slim
  handler: routers.router_if_no_else_flow_line_13_if_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ROUTER_IF_NO_ELSE_FLOW_LINE_13_IF_1
    value: routers.router_if_no_else_flow_line_13_if_1
