flowchart TD
    %% Flow: complex_combined_flow

    end_complex_combined_flow([end_complex_combined_flow])
    handler_error[handler_error]
    router_complex_combined_flow_line_15_if_8{{router_complex_combined_flow_line_15_if_8}}
    router_complex_combined_flow_line_21_while_1{{router_complex_combined_flow_line_21_while_1}}
    router_complex_combined_flow_line_29_if_2{{router_complex_combined_flow_line_29_if_2}}

    router_complex_combined_flow_line_15_if_8 -->|not p['valid']| handler_error