# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: complex_combined.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile complex_combined.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

async def start_complex_combined_flow(payload: dict):
    """Entrypoint for flow 'complex_combined_flow'"""
    _next = []
    _next.append(resolve("handler_init"))
    _next.append(resolve("router_complex_combined_flow_line_15_if_8"))
    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_complex_combined_flow_line_29_if_2(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['stop_early']:
        yield "SET", ".route.next", [resolve("handler_finalize")]
        yield p
        return
    else:
        pass

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_complex_combined_flow_line_24_if_3(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['i'] += 1
    if p['skip_even'] and p['i'] % 2 == 0:
        _next.append(resolve("router_complex_combined_flow_line_21_while_1"))
    else:
        _next.append(resolve("handler_process"))
        _next.append(resolve("router_complex_combined_flow_line_29_if_2"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_complex_combined_flow_line_21_while_1(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['i'] < p['max_iterations']:
        _next.append(resolve("router_complex_combined_flow_line_24_if_3"))
        _next.append(resolve("router_complex_combined_flow_line_21_while_1"))
    else:
        yield "SET", ".route.next", [resolve("handler_finalize")]
        yield p
        return

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_complex_combined_flow_line_20_seq_4(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['i'] = 0
    _next.append(resolve("router_complex_combined_flow_line_21_while_1"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_complex_combined_flow_line_34_if_5(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['type'] == 'B':
        _next.append(resolve("handler_type_b"))
    else:
        _next.append(resolve("handler_default"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_complex_combined_flow_line_32_if_6(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['type'] == 'A':
        _next.append(resolve("handler_type_a"))
    else:
        _next.append(resolve("router_complex_combined_flow_line_34_if_5"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_complex_combined_flow_line_19_if_7(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['needs_loop']:
        _next.append(resolve("router_complex_combined_flow_line_20_seq_4"))
        _next.append(resolve("handler_finalize"))
    else:
        _next.append(resolve("router_complex_combined_flow_line_32_if_6"))
        _next.append(resolve("handler_finalize"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_complex_combined_flow_line_15_if_8(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if not p['valid']:
        yield "SET", ".route.next", [resolve("handler_error")]
        yield p
        return
    else:
        _next.append(resolve("router_complex_combined_flow_line_19_if_7"))

    yield "SET", ".route.next[:0]", _next
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
