apiVersion: v1
kind: ConfigMap
metadata:
  name: asya-flow-text-improver-config
  labels:
    asya.sh/flow: text-improver
    asya.sh/config-type: flows
    asya.sh/managed-by: asya-lab
data:
  text-improver.yaml: |
    flows:
    - name: text-improver
      entrypoint: start-text-improver
      description: Text improver with Gemini
      mcp: {}
      a2a: {}
