apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- flow-expose.yaml
configurations:
- kustomizeconfig.yaml
images:
- name: demo-kubecon
  newName: europe-west1-docker.pkg.dev/foodsci-img-gen-dev-1407-1448/asya-demo/demo-kubecon
  newTag: v0.5.10-127-gcc227d29
patches:
- path: patch-actor-evaluate.yaml
- path: patch-actor-generate.yaml
- path: patch-actor-polish.yaml
- path: patch-actor-research.yaml
