apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- flow-expose.yaml
configurations:
- kustomizeconfig.yaml
patches:
- path: patch-actor-evaluate.yaml
- path: patch-actor-generate.yaml
- path: patch-actor-polish.yaml
- path: patch-actor-research.yaml
