flowchart TD
    %% Flow: review_pipeline_flow

    auto_approve[auto_approve]
    detailed_review[detailed_review]
    end_review_pipeline_flow([end_review_pipeline_flow])
    human_review[human_review]
    initial_review[initial_review]
    router_review_pipeline_flow_line_17_if_1{{router_review_pipeline_flow_line_17_if_1}}
    start_review_pipeline_flow([start_review_pipeline_flow])

    start_review_pipeline_flow --> initial_review
    initial_review --> router_review_pipeline_flow_line_17_if_1
    router_review_pipeline_flow_line_17_if_1 -->|p['score'] < 0.5| detailed_review
    detailed_review --> human_review
    router_review_pipeline_flow_line_17_if_1 -->|not (p['score'] < 0.5)| auto_approve
    auto_approve --> end_review_pipeline_flow
    human_review --> end_review_pipeline_flow