flowchart TD
    %% Flow: hierarchical_delegation

    api_specialist[api_specialist]
    content_generalist[content_generalist]
    content_team_lead[content_team_lead]
    data_generalist[data_generalist]
    data_team_lead[data_team_lead]
    editor[editor]
    end_hierarchical_delegation([end_hierarchical_delegation])
    final_assembler[final_assembler]
    generalist[generalist]
    root_agent[root_agent]
    router_hierarchical_delegation_line_61_if_6{{router_hierarchical_delegation_line_61_if_6}}
    router_hierarchical_delegation_line_65_if_2{{router_hierarchical_delegation_line_65_if_2}}
    router_hierarchical_delegation_line_67_if_1{{router_hierarchical_delegation_line_67_if_1}}
    router_hierarchical_delegation_line_72_if_5{{router_hierarchical_delegation_line_72_if_5}}
    router_hierarchical_delegation_line_76_if_4{{router_hierarchical_delegation_line_76_if_4}}
    router_hierarchical_delegation_line_78_if_3{{router_hierarchical_delegation_line_78_if_3}}
    sql_specialist[sql_specialist]
    start_hierarchical_delegation([start_hierarchical_delegation])
    writer[writer]

    start_hierarchical_delegation --> root_agent
    root_agent --> router_hierarchical_delegation_line_61_if_6
    router_hierarchical_delegation_line_67_if_1 -->|p.get('subtask') == 'api'| api_specialist
    router_hierarchical_delegation_line_67_if_1 -->|not (p.get('subtask') == 'api')| data_generalist
    router_hierarchical_delegation_line_65_if_2 -->|p.get('subtask') == 'sql'| sql_specialist
    router_hierarchical_delegation_line_65_if_2 -->|not (p.get('subtask') == 'sql')| router_hierarchical_delegation_line_67_if_1
    router_hierarchical_delegation_line_78_if_3 -->|p.get('subtask') == 'edit'| editor
    router_hierarchical_delegation_line_78_if_3 -->|not (p.get('subtask') == 'edit')| content_generalist
    router_hierarchical_delegation_line_76_if_4 -->|p.get('subtask') == 'write'| writer
    router_hierarchical_delegation_line_76_if_4 -->|not (p.get('subtask') == 'write')| router_hierarchical_delegation_line_78_if_3
    router_hierarchical_delegation_line_72_if_5 -->|p.get('domain') == 'content'| content_team_lead
    content_team_lead --> router_hierarchical_delegation_line_76_if_4
    router_hierarchical_delegation_line_72_if_5 -->|not (p.get('domain') == 'content')| generalist
    router_hierarchical_delegation_line_61_if_6 -->|p.get('domain') == 'data'| data_team_lead
    data_team_lead --> router_hierarchical_delegation_line_65_if_2
    router_hierarchical_delegation_line_61_if_6 -->|not (p.get('domain') == 'data')| router_hierarchical_delegation_line_72_if_5
    sql_specialist --> final_assembler
    router_hierarchical_delegation_line_67_if_1 --> final_assembler
    router_hierarchical_delegation_line_76_if_4 --> final_assembler
    generalist --> final_assembler
    final_assembler --> end_hierarchical_delegation