apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-splitter
  namespace: default
  labels:
    asya.sh/flow: map-reduce
spec:
  actor: actor-splitter
  image: examples.asya.sh/splitter:latest
  handler: map_reduce.splitter
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
