apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-map-reduce-line-54-fanout-1
  namespace: default
  labels:
    asya.sh/flow: map-reduce
    asya.sh/generated: 'true'
spec:
  actor: router-map-reduce-line-54-fanout-1
  image: python:3.13-slim
  handler: routers.router_map_reduce_line_54_fanout_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_CHUNK_PROCESSOR
    value: chunk_processor
  - name: ASYA_HANDLER_FANIN_MAP_REDUCE_LINE_54
    value: routers.fanin_map_reduce_line_54
  - name: ASYA_HANDLER_REDUCER
    value: reducer
  - name: ASYA_HANDLER_ROUTER_MAP_REDUCE_LINE_54_FANOUT_1
    value: routers.router_map_reduce_line_54_fanout_1
  - name: ASYA_HANDLER_SPLITTER
    value: splitter
