apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-tool-calling-agent-line-117-if-5
  namespace: default
  labels:
    asya.sh/flow: tool-calling-agent
    asya.sh/generated: 'true'
spec:
  actor: router-tool-calling-agent-line-117-if-5
  image: python:3.13-slim
  handler: routers.router_tool_calling_agent_line_117_if_5
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CALCULATE
    value: calculate
  - name: ASYA_HANDLER_ACTOR_FORMAT_RESPONSE
    value: format_response
  - name: ASYA_HANDLER_ACTOR_GET_WEATHER
    value: get_weather
  - name: ASYA_HANDLER_ACTOR_LIST_GCS_FILES
    value: list_gcs_files
  - name: ASYA_HANDLER_ACTOR_LLM_REASON
    value: llm_reason
  - name: ASYA_HANDLER_ROUTER_TOOL_CALLING_AGENT_LINE_103_WHILE_1
    value: routers.router_tool_calling_agent_line_103_while_1
  - name: ASYA_HANDLER_ROUTER_TOOL_CALLING_AGENT_LINE_104_SEQ_8
    value: routers.router_tool_calling_agent_line_104_seq_8
  - name: ASYA_HANDLER_ROUTER_TOOL_CALLING_AGENT_LINE_109_IF_7
    value: routers.router_tool_calling_agent_line_109_if_7
  - name: ASYA_HANDLER_ROUTER_TOOL_CALLING_AGENT_LINE_115_IF_6
    value: routers.router_tool_calling_agent_line_115_if_6
  - name: ASYA_HANDLER_ROUTER_TOOL_CALLING_AGENT_LINE_117_IF_5
    value: routers.router_tool_calling_agent_line_117_if_5
  - name: ASYA_HANDLER_ROUTER_TOOL_CALLING_AGENT_LINE_119_IF_4
    value: routers.router_tool_calling_agent_line_119_if_4
  - name: ASYA_HANDLER_ROUTER_TOOL_CALLING_AGENT_LINE_122_IF_3
    value: routers.router_tool_calling_agent_line_122_if_3
  - name: ASYA_HANDLER_ROUTER_TOOL_CALLING_AGENT_LINE_127_SEQ_2
    value: routers.router_tool_calling_agent_line_127_seq_2
  - name: ASYA_HANDLER_ACTOR_WEB_SEARCH
    value: web_search
