x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "2"

services:
  gateway:
    build:
      context: ../../../../src/asya-gateway
      dockerfile: Dockerfile
    logging: *default-logging
    command: ["./mesh-api"]
    env_file:
    - ../envs/.env.${ASYA_TRANSPORT}
    environment:
      ASYA_MESH_EXTERNAL_PORT: "8080"
      ASYA_MESH_INTERNAL_PORT: "8081"
      ASYA_STATEPROXY_SOCKET: /tmp/stateproxy.sock
      ASYA_INTERNAL_URL: http://gateway:8081
      ASYA_LOG_LEVEL: ${ASYA_LOG_LEVEL:-INFO}
    volumes:
    - stateproxy-socket:/tmp
    ports:
    - "8081:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      pg-kv:
        condition: service_started

  pg-kv:
    build:
      context: ../../../../src/asya-state-proxy
      dockerfile: Dockerfile.pg-kv
      target: builder
    logging: *default-logging
    command: ["go", "run", "./cmd/pg-kv/"]
    environment:
      CONNECTOR_SOCKET: /tmp/stateproxy.sock
      STATE_PROXY_PG_URL: postgres://postgres:postgres@postgres:5432/asya_test?sslmode=disable
      STATE_PROXY_PG_INDEXES: "status"
    volumes:
    - stateproxy-socket:/tmp
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  stateproxy-socket:
