---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-test-nested-flow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: start-test-nested-flow
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}

  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.start_test_nested_flow
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-4-if
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-line-4-if
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_line_9_if
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-6-if
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-line-6-if
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_line_11_if
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-14-if
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-line-14-if
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_line_19_if
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-7-seq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-line-7-seq
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_line_12_seq
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-10-seq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-line-10-seq
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_line_15_seq
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-15-seq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-line-15-seq
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_line_20_seq
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-line-18-seq
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-line-18-seq
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_line_23_seq
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: end-test-nested-flow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: end-test-nested-flow
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.end_test_nested_flow
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
