---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-test-nested-flow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: start-test-nested-flow
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}

  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.start_test_nested_flow
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-if-level1-eq-a
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-if-level1-eq-a
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_if_level1_eq_a
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-if-level2-eq-x
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-if-level2-eq-x
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_if_level2_eq_x
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-seq-set-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-seq-set-route
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_seq_set_route
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-seq-set-route-2
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-seq-set-route-2
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_seq_set_route_2
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-if-level2-eq-x-2
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-if-level2-eq-x-2
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_if_level2_eq_x_2
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-seq-set-route-3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-seq-set-route-3
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_seq_set_route_3
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
---
apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-test-nested-flow-seq-set-route-4
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "asya-test-flows.labels" . | nindent 4 }}
    asya.sh/flow: nested-if
    asya.sh/actor-type: router
spec:
  actor: router-test-nested-flow-seq-set-route-4
  scaling:
    enabled: {{ .Values.scaling.enabled }}
    minReplicaCount: {{ .Values.scaling.minReplicaCount }}
    maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
    pollingInterval: {{ .Values.scaling.pollingInterval }}
    cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
    queueLength: {{ .Values.scaling.queueLength }}
  image: {{ .Values.workload.image }}
  imagePullPolicy: {{ .Values.workload.imagePullPolicy }}
  handler: asya_testing.flows.nested_if.compiled.routers.router_test_nested_flow_seq_set_route_4
  env:
  {{- include "asya-test-flows.nested-if-handler-env" . | nindent 2 }}
