apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-format-output
  namespace: default
  labels:
    asya.sh/flow: actor-override-flow
    asya.sh/role: end
spec:
  actor: actor-format-output
  image: examples.asya.sh/format-output:latest
  handler: format_output
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
