apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-actor-override-flow
  namespace: default
  labels:
    asya.sh/flow: actor-override-flow
    asya.sh/role: start
    asya.sh/generated: 'true'
spec:
  actor: start-actor-override-flow
  image: python:3.13-slim
  handler: routers.start_actor_override_flow
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_CLASSIFY
    value: classify
  - name: ASYA_HANDLER_FORMAT_OUTPUT
    value: format_output
  - name: ASYA_HANDLER_ROUTER_ACTOR_OVERRIDE_FLOW_LINE_26_IF_1
    value: routers.router_actor_override_flow_line_26_if_1
  - name: ASYA_HANDLER_TOOL_EXECUTOR
    value: tool_executor
