apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-preprocessor
  namespace: default
  labels:
    asya.sh/flow: research-flow
spec:
  actor: actor-preprocessor
  image: examples.asya.sh/preprocessor:latest
  handler: preprocessor
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
