apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-research-agent.yaml
- asyncactor-router-research-flow-line-14-fanout-1.yaml
- asyncactor-start-research-flow.yaml
- configmap-routers.yaml
