apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-retry-pipeline-line-15-while-1
  namespace: default
  labels:
    asya.sh/flow: retry-pipeline
    asya.sh/generated: 'true'
spec:
  actor: router-retry-pipeline-line-15-while-1
  image: python:3.13-slim
  handler: routers.router_retry_pipeline_line_15_while_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CALL_ANOTHER_API
    value: call_another_api
  - name: ASYA_HANDLER_ACTOR_CALL_EXTERNAL_API
    value: call_external_api
  - name: ASYA_HANDLER_ACTOR_LOG_RETRY
    value: log_retry
  - name: ASYA_HANDLER_ACTOR_PREPARE_REQUEST
    value: prepare_request
  - name: ASYA_HANDLER_ROUTER_RETRY_PIPELINE_LINE_15_WHILE_1
    value: routers.router_retry_pipeline_line_15_while_1
  - name: ASYA_HANDLER_ROUTER_RETRY_PIPELINE_LINE_16_SEQ_4
    value: routers.router_retry_pipeline_line_16_seq_4
