apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-router-retry-pipeline-line-13-seq-5.yaml
- asya-router-retry-pipeline-line-15-while-1.yaml
- asya-router-retry-pipeline-line-16-seq-4.yaml
- asya-router-retry-pipeline-line-20-except-2.yaml
- asya-router-retry-pipeline-line-22-except-3.yaml
- asya-start-retry-pipeline.yaml
- configmap-routers.yaml
