apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-preprocess
  namespace: default
  labels:
    asya.sh/flow: outer-pipeline
spec:
  actor: actor-preprocess
  image: examples.asya.sh/preprocess:latest
  handler: flow_composition_simple.preprocess
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
