apiVersion: v2
name: asya-operator
description: Asya Operator - Kubernetes operator for managing Actor resources
type: application
# versions are replaced by automatically .github/workflows/release.yml
version: 0.0.0
appVersion: "0.0.0"
keywords:
- operator
- actor
- crd
- sidecar
- ai
maintainers:
- name: Asya Team
