apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-class-instantiation-flow
  namespace: default
  labels:
    asya.sh/flow: class-instantiation-flow
    asya.sh/role: start
    asya.sh/generated: 'true'
spec:
  actor: start-class-instantiation-flow
  image: python:3.13-slim
  handler: routers.start_class_instantiation_flow
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_SEQUENTIAL_WITH_CLASS.DATAPREPROCESSOR.CLEAN
    value: sequential_with_class.DataPreprocessor.clean
  - name: ASYA_HANDLER_ACTOR_SEQUENTIAL_WITH_CLASS.MLMODEL.PREDICT
    value: sequential_with_class.MLModel.predict
  - name: ASYA_HANDLER_ACTOR_TRANSFORMATION
    value: sequential_with_class.transformation
  volumes:
  - name: routers
    configMap:
      name: class-instantiation-flow-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
