apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-sequential-with-class.MLModel.predict
  namespace: default
  labels:
    asya.sh/flow: class-instantiation-flow
    asya.sh/role: end
spec:
  actor: actor-sequential-with-class.MLModel.predict
  image: examples.asya.sh/sequential-with-class.MLModel.predict:latest
  handler: sequential_with_class.MLModel.predict
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
