apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-transformation
  namespace: default
  labels:
    asya.sh/flow: class-instantiation-flow
spec:
  actor: actor-transformation
  image: examples.asya.sh/transformation:latest
  handler: sequential_with_class.transformation
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
