apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-router-class-instantiation-flow-line-17-seq-1.yaml
- asyncactor-start-class-instantiation-flow.yaml
- configmap-routers.yaml
