apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-b
  namespace: default
  labels:
    asya.sh/flow: mutations-before-after-handler-flow
spec:
  actor: actor-handler-b
  image: examples.asya.sh/handler-b:latest
  handler: mutations_before_after_handler.handler_b
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
