apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-mutations-before-after-handler-flow-line-12-seq-3
  namespace: default
  labels:
    asya.sh/flow: mutations-before-after-handler-flow
    asya.sh/generated: 'true'
spec:
  actor: router-mutations-before-after-handler-flow-line-12-seq-3
  image: python:3.13-slim
  handler: routers.router_mutations_before_after_handler_flow_line_12_seq_3
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_A
    value: handler_a
  - name: ASYA_HANDLER_ACTOR_HANDLER_B
    value: handler_b
  - name: ASYA_HANDLER_ROUTER_MUTATIONS_BEFORE_AFTER_HANDLER_FLOW_LINE_14_SEQ_2
    value: routers.router_mutations_before_after_handler_flow_line_14_seq_2
  - name: ASYA_HANDLER_ROUTER_MUTATIONS_BEFORE_AFTER_HANDLER_FLOW_LINE_16_SEQ_1
    value: routers.router_mutations_before_after_handler_flow_line_16_seq_1
