apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-accuracy-scorer
  namespace: default
  labels:
    asya.sh/flow: llm-auditor
spec:
  actor: actor-accuracy-scorer
  image: examples.asya.sh/accuracy-scorer:latest
  handler: accuracy_scorer
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
