flowchart TD
    %% Flow: while_simple_flow

    end_while_simple_flow([end_while_simple_flow])
    handler_finalize[handler_finalize]
    handler_init[handler_init]
    handler_process[handler_process]
    router_while_simple_flow_line_13_seq_3{{router_while_simple_flow_line_13_seq_3}}
    router_while_simple_flow_line_14_while_1{{router_while_simple_flow_line_14_while_1}}
    router_while_simple_flow_line_15_seq_2{{router_while_simple_flow_line_15_seq_2}}
    start_while_simple_flow([start_while_simple_flow])

    start_while_simple_flow --> handler_init
    handler_init --> router_while_simple_flow_line_13_seq_3
    router_while_simple_flow_line_15_seq_2 --> handler_process
    router_while_simple_flow_line_14_while_1 -->|p['i'] < p['max_iterations']| router_while_simple_flow_line_15_seq_2
    router_while_simple_flow_line_15_seq_2 --> router_while_simple_flow_line_14_while_1
    router_while_simple_flow_line_14_while_1 -->|not (p['i'] < p['max_iterations'])| handler_finalize
    router_while_simple_flow_line_13_seq_3 --> router_while_simple_flow_line_14_while_1
    handler_finalize --> end_while_simple_flow
    handler_process --> end_while_simple_flow