flowchart TD
    %% Flow: parallel_sectioning

    end_parallel_sectioning([end_parallel_sectioning])
    preprocessor[preprocessor]
    router_parallel_sectioning_line_48_fanout_1{{router_parallel_sectioning_line_48_fanout_1}}
    start_parallel_sectioning([start_parallel_sectioning])

    start_parallel_sectioning --> preprocessor
    start_parallel_sectioning --> router_parallel_sectioning_line_48_fanout_1