apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-aggregator.yaml
- asyncactor-entity-recognizer.yaml
- asyncactor-preprocessor.yaml
- asyncactor-router-parallel-sectioning-line-47-fanout-1.yaml
- asyncactor-sentiment-analyzer.yaml
- asyncactor-start-parallel-sectioning.yaml
- asyncactor-topic-extractor.yaml
- configmap-routers.yaml
