apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-parse-data
  namespace: default
  labels:
    asya.sh/flow: data-pipeline
spec:
  actor: actor-parse-data
  image: examples.asya.sh/parse-data:latest
  handler: parse_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env:
  - name: ASYA_IGNORE_DECORATORS
    value: timeout_decorator.timeout
  resiliency:
    policies:
      try_except_line_30_0:
        maxAttempts: 1
        thenRoute:
        - router-data-pipeline-line-33-except-2
    rules:
    - errors:
      - ValueError
      policy: try_except_line_30_0
    timeout:
      actor: '10'
