apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-parse-data
  namespace: default
  labels:
    asya.sh/flow: resiliency-combined
spec:
  actor: actor-parse-data
  image: examples.asya.sh/parse-data:latest
  handler: resiliency_combined.parse_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env:
  - name: ASYA_IGNORE_DECORATORS
    value: timeout_decorator.timeout
  resiliency:
    policies:
      except_valueerror:
        maxAttempts: 1
        thenRoute:
        - router-resiliency-combined-except-valueerror
    rules:
    - errors:
      - ValueError
      policy: except_valueerror
    timeout:
      actor: 10
