apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-data-pipeline-seq-set-status
  namespace: default
  labels:
    asya.sh/flow: data-pipeline
    asya.sh/generated: 'true'
spec:
  actor: router-data-pipeline-seq-set-status
  image: python:3.13-slim
  handler: routers.router_data_pipeline_seq_set_status
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_FETCH_DATA
    value: fetch_data
  - name: ASYA_HANDLER_ACTOR_HANDLE_BAD_DATA
    value: handle_bad_data
  - name: ASYA_HANDLER_ACTOR_PARSE_DATA
    value: parse_data
  - name: ASYA_HANDLER_ACTOR_STORE_RESULTS
    value: store_results
