apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-fetch-data
  namespace: default
  labels:
    asya.sh/flow: data-pipeline
spec:
  actor: actor-fetch-data
  image: examples.asya.sh/fetch-data:latest
  handler: fetch_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env:
  - name: ASYA_IGNORE_DECORATORS
    value: tenacity.retry
  resiliency:
    policies:
      try_except_line_30_0:
        maxAttempts: 1
        thenRoute:
        - router-data-pipeline-line-33-except-2
      default:
        maxAttempts: '5'
        maxDuration: '30'
    rules:
    - errors:
      - ValueError
      policy: try_except_line_30_0
    timeout:
      actor: '60'
