apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-process
  namespace: default
  labels:
    asya.sh/flow: while-true-flow
spec:
  actor: actor-handler-process
  image: examples.asya.sh/handler-process:latest
  handler: while_true_simple.handler_process
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
