apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../common
- flow-expose.yaml
patches:
- path: patch-actor-generate.yaml
- path: patch-actor-evaluate.yaml
- path: patch-actor-format-output.yaml
- path: patch-actor-polish.yaml
- path: patch-actor-research.yaml
