"""Generate Python code for routers."""

from datetime import datetime
from textwrap import dedent

from asya_cli.flow.grouper import Router


class CodeGenerator:
    def __init__(self, flow_name: str, routers: list[Router], source_file: str):
        self.flow_name = flow_name
        self.routers = routers
        self.source_file = source_file
        self.all_handlers: set[str] = set()

    def generate(self) -> str:
        self._collect_handlers()

        parts = []
        parts.append(self._generate_header())
        parts.append(self._generate_routers())
        parts.append(self._generate_resolve_function())

        return "\n".join(parts)

    def _collect_handlers(self) -> None:
        for router in self.routers:
            self.all_handlers.add(router.name)
            for actor_name in router.true_branch_actors:
                self.all_handlers.add(actor_name)
            for actor_name in router.false_branch_actors:
                self.all_handlers.add(actor_name)

    def _generate_header(self) -> str:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return dedent(f'''
        """
        Auto-generated by asya flow compiler
        Source: {self.source_file}
        Generated: {timestamp}

        DO NOT EDIT THIS FILE MANUALLY
        Regenerate by running: asya flow compile {self.source_file}
        """
        # mypy: disable-error-code="attr-defined"
        ''')

    def _generate_routers(self) -> str:
        lines = []
        lines.append("\n# " + "=" * 70)
        lines.append("# Generated Routers (for kubernetes deployment)")
        lines.append("# " + "=" * 70)
        lines.append("")

        for router in self.routers:
            if router.name.startswith("start_"):
                lines.append(self._generate_start_router(router))
            elif router.name.startswith("end_"):
                lines.append(self._generate_end_router(router))
            else:
                lines.append(self._generate_router(router))

        return "\n".join(lines)

    def _generate_start_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(envelope: dict) -> dict:")
        lines.append(f'    """Entrypoint for flow \'{self.flow_name}\'"""')
        lines.append("    r = envelope['route']")
        lines.append("    c = r['current']")
        lines.append("")

        if router.true_branch_actors:
            filtered_actors = [name for name in router.true_branch_actors if not name.startswith("end_")]
            if filtered_actors:
                next_list = ", ".join([f'resolve("{name}")' for name in filtered_actors])
                lines.append(f"    r['actors'][c+1:c+1] = [{next_list}]")
        lines.append("    r['current'] = c + 1")
        lines.append("    return envelope")
        lines.append("")

        return "\n".join(lines)

    def _generate_end_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(envelope: dict) -> dict:")
        lines.append(f'    """Exitpoint for flow \'{self.flow_name}\'"""')
        lines.append("    return envelope")
        lines.append("")

        return "\n".join(lines)

    def _generate_router(self, router: Router) -> str:
        lines = []
        lines.append(f"def {router.name}(envelope: dict) -> dict:")
        lines.append('    """Router for control flow and payload mutations"""')
        lines.append("    p = envelope['payload']")
        lines.append("    r = envelope['route']")
        lines.append("    c = r['current']")
        lines.append("    _next = []")
        lines.append("")

        for mutation in router.mutations:
            lines.append(f"    {mutation.code}")

        if router.condition:
            lines.append(f"    if {router.condition.test}:")
            if router.true_branch_actors:
                filtered_true = [actor for actor in router.true_branch_actors if not actor.startswith("end_")]
                for actor in filtered_true:
                    lines.append(f'        _next.append(resolve("{actor}"))')
                if not filtered_true:
                    lines.append("        pass")
            else:
                lines.append("        pass")
            lines.append("    else:")
            if router.false_branch_actors:
                filtered_false = [actor for actor in router.false_branch_actors if not actor.startswith("end_")]
                for actor in filtered_false:
                    lines.append(f'        _next.append(resolve("{actor}"))')
                if not filtered_false:
                    lines.append("        pass")
            else:
                lines.append("        pass")
        else:
            filtered_actors = [actor for actor in router.true_branch_actors if not actor.startswith("end_")]
            for actor in filtered_actors:
                lines.append(f'    _next.append(resolve("{actor}"))')

        lines.append("")
        lines.append("    r['actors'][c+1:c+1] = _next")
        lines.append("    r['current'] = c + 1")
        lines.append("    return envelope")
        lines.append("")

        return "\n".join(lines)

    def _generate_resolve_function(self) -> str:
        return dedent('''
        # ======================================================================
    # Handler Resolution
    # ======================================================================


    def resolve(handler_full_name: str) -> str:
        """
        Resolve handler name to actor name using suffix-based matching.

        Looks up handler in environment variables:
        - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

        Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
        - "method" (shortest)
        - "ClassName.method" (class + method)
        - "module.ClassName.method" (partial path)
        - "full.module.path.ClassName.method" (full path)

        Args:
            handler_full_name: Any suffix of the full handler path

        Returns:
            Actor name for routing (kebab-case, lowercase)

        Raises:
            ValueError: If handler suffix not found or is ambiguous

        Examples:
            # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

            # All of these work (if unambiguous):
            resolve("clean")  # shortest suffix
            resolve("DataPreprocessor.clean")  # class + method
            resolve("class_instantiation.DataPreprocessor.clean")  # full path

            # Ambiguous suffix
            # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
            resolve("clean")  # raises ValueError: ambiguous, use longer suffix
        """
        import os, logging

        if not hasattr(resolve, '_handler_to_actor'):
            resolve._handler_to_actor = {}
            resolve._suffix_to_handlers = {}

            for env_var, handler_name in os.environ.items():
                if env_var.startswith('ASYA_HANDLER_'):
                    actor_name = env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
                    resolve._handler_to_actor[handler_name] = actor_name

                    # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
                    parts = handler_name.split('.')
                    for i in range(len(parts)):
                        suffix = '.'.join(parts[i:])
                        if suffix not in resolve._suffix_to_handlers:
                            resolve._suffix_to_handlers[suffix] = []
                        resolve._suffix_to_handlers[suffix].append(handler_name)

            logging.info(f"Loaded {len(resolve._handler_to_actor)} handler-to-actor mappings")

        # Try suffix-based resolution (exact match or any valid suffix)
        if handler_full_name in resolve._suffix_to_handlers:
            candidates = resolve._suffix_to_handlers[handler_full_name]
            if len(candidates) == 1:
                return resolve._handler_to_actor[candidates[0]]
            else:
                raise ValueError(
                    f"Handler suffix '{handler_full_name}' is ambiguous. "
                    f"Found multiple matches: {candidates}. "
                    f"Use a longer suffix to disambiguate."
                )

        raise ValueError(
            f"Handler '{handler_full_name}' not found in environment variables. "
            f'No handler ends with suffix "{handler_full_name}". '
            f"Available handlers: {list(resolve._handler_to_actor.keys())}"
        )
        ''')
