"""
Code templates for Flow DSL compiler.

Contains templates for resolve() function and other generated code.
"""


def get_resolve_function() -> str:
    """
    Get resolve() function template.

    This function resolves handler full names to actor names for routing.
    Uses the same import logic as asya_runtime.py.
    """
    return '''def resolve(handler_full_name: str) -> str:
    """
    Resolve handler full name to actor name for routing.

    Priority:
    1. Environment variable ASYA_ACTOR_{HANDLER_NAME}
    2. Import Python object and use kebab-case conversion

    Args:
        handler_full_name: Full qualified name like "module.handler" or "module.Class.method"

    Returns:
        Actor name for routing

    Examples:
        resolve("my_module.processor") -> "processor" (or env var value)
        resolve("my_module.ImageProcessor.process") -> "image-processor-process"
    """
    import importlib
    import os

    # Extract handler name (last component)
    parts = handler_full_name.split(".")
    handler_name = parts[-1]

    # Priority 1: Environment variable
    env_key = f"ASYA_ACTOR_{handler_name.upper()}"
    if env_key in os.environ:
        return os.environ[env_key]

    # Priority 2: Try to import and get actual name
    # Use same algorithm as asya_runtime.py: try imports from right to left
    module = None
    module_parts = []
    attr_parts = []

    for i in range(len(parts) - 1, 0, -1):
        module_path = ".".join(parts[:i])
        try:
            module = importlib.import_module(module_path)
            module_parts = parts[:i]
            attr_parts = parts[i:]
            break
        except ImportError:
            continue

    if module:
        try:
            # Get the object
            obj = module
            for part in attr_parts:
                obj = getattr(obj, part)

            # Use object's __name__ if available
            actual_name = getattr(obj, "__name__", handler_name)
            return actual_name.replace("_", "-")
        except (AttributeError, TypeError):
            pass

    # Priority 3: Fallback to kebab-case conversion
    return handler_name.replace("_", "-")'''


def get_file_header(source_file: str) -> str:
    """Generate file header comment."""
    from datetime import datetime

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return f'''"""
Auto-generated by asya-cli flow compiler
Source: {source_file}
Generated: {timestamp}

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya-cli flow compile {source_file}
"""'''


def get_initial_route(flow_name: str, first_router_id: str) -> str:
    """Generate initial route setup code."""
    return f'''# Initial route for flow '{flow_name}'
# In PoC mode: call flow function directly
# In production: send envelope to gateway with route = ["{first_router_id}"]
INITIAL_ROUTE = ["{first_router_id}"]'''
