"""
Code templates for Flow DSL compiler.

Contains templates for resolve() function and other generated code.
"""

import textwrap


def get_file_header(source_file: str) -> str:
    """Generate file header comment."""
    from datetime import datetime

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return textwrap.dedent(f'''"""
Auto-generated by asya flow compiler
Source: {source_file}
Generated: {timestamp}

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile {source_file}
"""''')


def get_resolve_function() -> str:
    """
    Get resolve() function template.

    This function resolves handler full names to actor names for routing.
    Uses reverse lookup in ASYA_HANDLER_* environment variables.
    """
    return textwrap.dedent('''def resolve(handler_full_name: str) -> str:
    """
    Resolve handler full name to actor name for routing.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="module.handler" or "module.Class.method"

    The reverse mapping (handler -> actor) is built once at first call and cached.

    Args:
        handler_full_name: Full qualified name like "module.handler" or "module.Class.method"

    Returns:
        Actor name for routing (kebab-case)

    Raises:
        ValueError: If handler not found in environment variables

    Examples:
        # Environment: ASYA_HANDLER_IMAGE_PROCESSOR="my_module.ImageProcessor.process"
        resolve("my_module.ImageProcessor.process")  # returns "image-processor"

        # Environment: ASYA_HANDLER_TEXT_ANALYZER="text.analyze"
        resolve("text.analyze")  # returns "text-analyzer"
    """
    import os

    # Build reverse mapping: {handler_full_name: actor_name}
    if not hasattr(resolve, '_handler_to_actor'):
        resolve._handler_to_actor = {}
        for key, value in os.environ.items():
            if key.startswith('ASYA_HANDLER_'):
                # Extract actor name: ASYA_HANDLER_IMAGE_PROCESSOR -> IMAGE_PROCESSOR
                actor_name_upper = key[len('ASYA_HANDLER_'):]
                # Convert to kebab-case: IMAGE_PROCESSOR -> image-processor
                actor_name = actor_name_upper.lower().replace('_', '-')
                # Map handler -> actor
                resolve._handler_to_actor[value] = actor_name

    if handler_full_name not in resolve._handler_to_actor:
        raise ValueError(
            f"Handler '{handler_full_name}' not found in environment variables. "
            f"Expected ASYA_HANDLER_<ACTOR_NAME>=\\"{handler_full_name}\\" to be set."
        )

    return resolve._handler_to_actor[handler_full_name]''')


def get_initial_route(flow_name: str, first_router_id: str) -> str:
    """Generate initial route setup code."""
    return textwrap.dedent(f'''# Initial route for flow '{flow_name}'
# Execution modes:
#   - local: call flow function directly (import and execute)
#   - docker: run handlers in local docker compose (future)
#   - kubernetes: send envelope to gateway with route = ["{first_router_id}"]
INITIAL_ROUTE = ["{first_router_id}"]''')
