flowchart TD
    %% Flow: bare_script_flow

    greet[greet]
    shout[shout]
    start_bare_script_flow([start_bare_script_flow])
    __end__((( )))

    start_bare_script_flow --> greet
    greet --> shout
    shout --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_bare_script_flow start
    class shout,__end__ endnode
    class greet handler