flowchart TD
    %% Flow: map_reduce

    chunk_processor[chunk_processor]
    end_map_reduce([end_map_reduce])
    fanin_map_reduce_line_55[fanin_map_reduce_line_55]
    reducer[reducer]
    router_map_reduce_line_55_fanout_1{{router_map_reduce_line_55_fanout_1}}
    splitter[splitter]
    start_map_reduce([start_map_reduce])

    start_map_reduce --> splitter
    splitter --> router_map_reduce_line_55_fanout_1
    router_map_reduce_line_55_fanout_1 --> fanin_map_reduce_line_55
    fanin_map_reduce_line_55 --> reducer
    router_map_reduce_line_55_fanout_1 --> chunk_processor
    chunk_processor --> fanin_map_reduce_line_55
    reducer --> end_map_reduce