templates:
  router_image: "python:3.13-slim"
  max_replicas: 10

compiler:
  code: "./compiled/${arg:flow_name}/code"
  artifacts: "./compiled/${arg:flow_name}/artifacts"
  manifests: "./compiled/${arg:flow_name}/manifests"
  templates: ".asya/templates"

registry: europe-west1-docker.pkg.dev/<YOUR-GCP-PROJECT>/asya-demo

contexts:
  dev:
    namespace: asya-demo
    gateway_url: http://localhost:18080
  local:
    namespace: asya-e2e
    kubectl_context: kind-asya-e2e-pubsub-gcs
    gateway_url: http://localhost:8080
    tempo_url: http://localhost:3200
    grafana_url: http://localhost:3000

default_context: dev
