apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-resource-pipeline-except-runtimeerror
  namespace: default
  labels:
    asya.sh/flow: resource-pipeline
    asya.sh/generated: 'true'
spec:
  actor: router-resource-pipeline-except-runtimeerror
  image: python:3.13-slim
  handler: routers.router_resource_pipeline_except_runtimeerror
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_ACQUIRE_RESOURCE
    value: acquire_resource
  - name: ASYA_HANDLER_ACTOR_FINALIZE
    value: finalize
  - name: ASYA_HANDLER_ACTOR_HANDLE_FAILURE
    value: handle_failure
  - name: ASYA_HANDLER_ACTOR_PROCESS_WITH_RESOURCE
    value: process_with_resource
  - name: ASYA_HANDLER_ACTOR_RELEASE_RESOURCE
    value: release_resource
