apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-release-resource
  namespace: default
  labels:
    asya.sh/flow: resource-pipeline
spec:
  actor: actor-release-resource
  image: examples.asya.sh/release-resource:latest
  handler: release_resource
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
