apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-acquire-resource.yaml
- asya-actor-finalize.yaml
- asya-actor-handle-failure.yaml
- asya-actor-process-with-resource.yaml
- asya-actor-release-resource.yaml
- asya-router-resource-pipeline-except-runtimeerror.yaml
- asya-router-resource-pipeline-seq-set-status.yaml
- asya-start-resource-pipeline.yaml
- configmap-routers.yaml
