flowchart TD
    %% Flow: rag_pipeline

    fact_checker([fact_checker])
    generator[generator]
    query_analyzer[query_analyzer]
    query_refiner([query_refiner])
    relevance_evaluator[relevance_evaluator]
    retriever[retriever]
    router_rag_pipeline_line_50_seq_5{{router_rag_pipeline_line_50_seq_5}}
    router_rag_pipeline_line_56_while_1{{router_rag_pipeline_line_56_while_1}}
    router_rag_pipeline_line_57_seq_4{{router_rag_pipeline_line_57_seq_4}}
    router_rag_pipeline_line_66_if_3{{router_rag_pipeline_line_66_if_3}}
    router_rag_pipeline_line_70_if_2{{router_rag_pipeline_line_70_if_2}}
    start_rag_pipeline([start_rag_pipeline])

    start_rag_pipeline --> router_rag_pipeline_line_50_seq_5
    router_rag_pipeline_line_70_if_2 -->|not (p['retrieval_attempts'] >= 3)| query_refiner
    router_rag_pipeline_line_70_if_2 -->|p['retrieval_attempts'] >= 3| generator
    generator --> fact_checker
    router_rag_pipeline_line_66_if_3 -->|not (p.get('is_sufficient'))| router_rag_pipeline_line_70_if_2
    router_rag_pipeline_line_66_if_3 -->|p.get('is_sufficient')| generator
    router_rag_pipeline_line_57_seq_4 --> retriever
    retriever --> relevance_evaluator
    relevance_evaluator --> router_rag_pipeline_line_66_if_3
    router_rag_pipeline_line_56_while_1 --> router_rag_pipeline_line_57_seq_4
    router_rag_pipeline_line_50_seq_5 --> query_analyzer
    query_analyzer --> router_rag_pipeline_line_56_while_1
    router_rag_pipeline_line_66_if_3 --> router_rag_pipeline_line_56_while_1