flowchart TD
    %% Flow: if_no_else_flow

    handler_setup[handler_setup]
    handler_true[handler_true]
    router_if_no_else_flow_line_13_if_1{{router_if_no_else_flow_line_13_if_1}}
    start_if_no_else_flow([start_if_no_else_flow])
    __end__((( )))

    start_if_no_else_flow --> handler_setup
    handler_setup --> router_if_no_else_flow_line_13_if_1
    router_if_no_else_flow_line_13_if_1 -->|"p['condition']"| handler_true
    router_if_no_else_flow_line_13_if_1 -->|"else"| handler_true
    handler_true --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_if_no_else_flow start
    class handler_true endnode
    class router_if_no_else_flow_line_13_if_1 router
    class handler_setup handler
    class __end__ endpoint
    linkStyle 2 stroke:#2E8B57
    linkStyle 3 stroke:#E07040