flowchart TD
    %% Flow: fanout_comprehension

    fanin_research_flow_line_15[fanin_research_flow_line_15]
    post_processor[post_processor]
    preprocessor[preprocessor]
    research_agent[research_agent]
    router_research_flow_line_15_fanout_1{{router_research_flow_line_15_fanout_1}}
    start_research_flow([start_research_flow])
    __end__((( )))

    start_research_flow --> preprocessor
    preprocessor --> router_research_flow_line_15_fanout_1
    router_research_flow_line_15_fanout_1 -->|fanout: p['topics']| fanin_research_flow_line_15
    fanin_research_flow_line_15 --> post_processor
    router_research_flow_line_15_fanout_1 --> research_agent
    research_agent --> fanin_research_flow_line_15
    post_processor --> __end__