flowchart TD
    %% Flow: llm_auditor_flow

    critic[critic]
    reviser[reviser]
    start_llm_auditor_flow([start_llm_auditor_flow])
    __end__((( )))

    start_llm_auditor_flow --> critic
    critic --> reviser
    reviser --> __end__