apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-call-fallback-llm.yaml
- asyncactor-call-llm.yaml
- asyncactor-notify-admin.yaml
- asyncactor-router-llm-pipeline-line-12-seq-5.yaml
- asyncactor-router-llm-pipeline-line-15-except-2.yaml
- asyncactor-router-llm-pipeline-line-16-seq-1.yaml
- asyncactor-router-llm-pipeline-line-18-except-4.yaml
- asyncactor-router-llm-pipeline-line-19-seq-3.yaml
- asyncactor-start-llm-pipeline.yaml
- configmap-routers.yaml
