apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-call-fallback-llm.yaml
- asya-actor-call-llm.yaml
- asya-actor-notify-admin.yaml
- asya-router-llm-pipeline-except-authenticationerror.yaml
- asya-router-llm-pipeline-except-ratelimiterror.yaml
- asya-start-llm-pipeline.yaml
- configmap-routers.yaml
