# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: react_tool_loop.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile react_tool_loop.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

async def start_react_tool_loop(payload: dict):
    """Entrypoint for flow 'react_tool_loop'"""
    p = payload
    _next = []
    p['messages'] = p.get('messages', [])
    p['iteration'] = 0
    _next.append(resolve("router_react_tool_loop_line_49_while_1"))
    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_react_tool_loop_line_75_if_2(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['messages'] = p.get('messages', [])
    if p['iteration'] >= 10:
        yield "SET", ".route.next", [resolve("format_response")]
        yield p
        return
    else:
        pass

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_react_tool_loop_line_69_seq_3(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['observation'] = 'Unknown tool'

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_react_tool_loop_line_66_if_4(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['tool_name'] == 'calculator':
        _next.append(resolve("calculator"))
    else:
        _next.append(resolve("router_react_tool_loop_line_69_seq_3"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_react_tool_loop_line_64_if_5(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['tool_name'] == 'code_exec':
        _next.append(resolve("code_exec"))
    else:
        _next.append(resolve("router_react_tool_loop_line_66_if_4"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_react_tool_loop_line_62_if_6(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['tool_name'] = p['tool_calls'][0]['name']
    if p['tool_name'] == 'web_search':
        _next.append(resolve("web_search"))
        _next.append(resolve("router_react_tool_loop_line_75_if_2"))
    else:
        _next.append(resolve("router_react_tool_loop_line_64_if_5"))
        _next.append(resolve("router_react_tool_loop_line_75_if_2"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_react_tool_loop_line_56_if_7(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if not p.get('tool_calls'):
        yield "SET", ".route.next", [resolve("format_response")]
        yield p
        return
    else:
        _next.append(resolve("router_react_tool_loop_line_62_if_6"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_react_tool_loop_line_50_seq_8(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['iteration'] += 1
    _next.append(resolve("llm_reason"))
    _next.append(resolve("router_react_tool_loop_line_56_if_7"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_react_tool_loop_line_49_while_1(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    _next.append(resolve("router_react_tool_loop_line_50_seq_8"))
    _next.append(resolve("router_react_tool_loop_line_49_while_1"))

    yield "SET", ".route.next[:0]", _next
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
