apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator
  labels:
    app: translator
    team: team-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translator
  template:
    metadata:
      labels:
        app: translator
        team: team-b
    spec:
      containers:
      - name: translator
        image: skaffold-translator
        ports:
        - containerPort: 8080
