flowchart TD
    %% Flow: while_nested_flow

    handler_finalize[handler_finalize]
    handler_init[handler_init]
    handler_inner[handler_inner]
    handler_outer[handler_outer]
    handler_outer_end[handler_outer_end]
    router_while_nested_flow_seq_set_i{{"router_while_nested_flow_seq_set_i<br/><br/>p['i'] += 1"}}
    router_while_nested_flow_seq_set_i_2{{"router_while_nested_flow_seq_set_i_2<br/><br/>p['i'] = 0"}}
    router_while_nested_flow_seq_set_j{{"router_while_nested_flow_seq_set_j<br/><br/>p['j'] += 1"}}
    router_while_nested_flow_seq_set_j_2{{"router_while_nested_flow_seq_set_j_2<br/><br/>p['j'] = 0"}}
    router_while_nested_flow_while_i_lt_max_i{{router_while_nested_flow_while_i_lt_max_i}}
    router_while_nested_flow_while_j_lt_max_j{{router_while_nested_flow_while_j_lt_max_j}}
    start_while_nested_flow([start_while_nested_flow])
    __end__((( )))

    start_while_nested_flow --> handler_init
    handler_init --> router_while_nested_flow_seq_set_i_2
    router_while_nested_flow_seq_set_j --> handler_inner
    router_while_nested_flow_while_j_lt_max_j -->|"p['j'] < p['max_j']"| router_while_nested_flow_seq_set_j
    router_while_nested_flow_while_j_lt_max_j -->|"else"| handler_outer_end
    router_while_nested_flow_seq_set_j_2 --> router_while_nested_flow_while_j_lt_max_j
    router_while_nested_flow_seq_set_i --> handler_outer
    handler_outer --> router_while_nested_flow_seq_set_j_2
    router_while_nested_flow_while_i_lt_max_i -->|"p['i'] < p['max_i']"| router_while_nested_flow_seq_set_i
    router_while_nested_flow_while_i_lt_max_i -->|"else"| handler_finalize
    router_while_nested_flow_seq_set_i_2 --> router_while_nested_flow_while_i_lt_max_i
    handler_inner --> router_while_nested_flow_while_j_lt_max_j
    router_while_nested_flow_while_j_lt_max_j --> router_while_nested_flow_while_i_lt_max_i
    handler_finalize --> __end__
    handler_outer_end --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_while_nested_flow start
    class handler_finalize,handler_outer_end,__end__ endnode
    class router_while_nested_flow_seq_set_i,router_while_nested_flow_seq_set_i_2,router_while_nested_flow_seq_set_j,router_while_nested_flow_seq_set_j_2,router_while_nested_flow_while_i_lt_max_i,router_while_nested_flow_while_j_lt_max_j router
    class handler_init,handler_inner,handler_outer handler
    linkStyle 3,8 stroke:#2E8B57
    linkStyle 4,9 stroke:#E07040