flowchart TD
    %% Flow: while_nested_flow

    end_while_nested_flow([end_while_nested_flow])
    handler_finalize[handler_finalize]
    handler_init[handler_init]
    handler_inner[handler_inner]
    handler_outer[handler_outer]
    handler_outer_end[handler_outer_end]
    router_while_nested_flow_line_13_seq_6{{router_while_nested_flow_line_13_seq_6}}
    router_while_nested_flow_line_14_while_1{{router_while_nested_flow_line_14_while_1}}
    router_while_nested_flow_line_15_seq_5{{router_while_nested_flow_line_15_seq_5}}
    router_while_nested_flow_line_17_seq_4{{router_while_nested_flow_line_17_seq_4}}
    router_while_nested_flow_line_18_while_2{{router_while_nested_flow_line_18_while_2}}
    router_while_nested_flow_line_19_seq_3{{router_while_nested_flow_line_19_seq_3}}
    start_while_nested_flow([start_while_nested_flow])

    start_while_nested_flow --> handler_init
    handler_init --> router_while_nested_flow_line_13_seq_6
    router_while_nested_flow_line_19_seq_3 --> handler_inner
    router_while_nested_flow_line_18_while_2 -->|p['j'] < p['max_j']| router_while_nested_flow_line_19_seq_3
    router_while_nested_flow_line_18_while_2 -->|not (p['j'] < p['max_j'])| handler_outer_end
    router_while_nested_flow_line_17_seq_4 --> router_while_nested_flow_line_18_while_2
    router_while_nested_flow_line_15_seq_5 --> handler_outer
    handler_outer --> router_while_nested_flow_line_17_seq_4
    router_while_nested_flow_line_14_while_1 -->|p['i'] < p['max_i']| router_while_nested_flow_line_15_seq_5
    router_while_nested_flow_line_14_while_1 -->|not (p['i'] < p['max_i'])| handler_finalize
    router_while_nested_flow_line_13_seq_6 --> router_while_nested_flow_line_14_while_1
    handler_inner --> router_while_nested_flow_line_18_while_2
    router_while_nested_flow_line_17_seq_4 --> router_while_nested_flow_line_14_while_1
    handler_finalize --> end_while_nested_flow
    handler_outer_end --> end_while_nested_flow