flowchart TD
    %% Flow: while_nested_flow

    end_while_nested_flow([end_while_nested_flow])
    handler_finalize[handler_finalize]
    handler_outer_end[handler_outer_end]
    router_while_nested_flow_line_14_while_1{{router_while_nested_flow_line_14_while_1}}
    router_while_nested_flow_line_18_while_2{{router_while_nested_flow_line_18_while_2}}

    router_while_nested_flow_line_18_while_2 -->|p['j'] < p['max_j']| handler_outer_end
    router_while_nested_flow_line_14_while_1 -->|p['i'] < p['max_i']| handler_finalize