apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-while-with-break-flow-seq-set-i-2
  namespace: default
  labels:
    asya.sh/flow: while-with-break-flow
    asya.sh/generated: 'true'
spec:
  actor: router-while-with-break-flow-seq-set-i-2
  image: python:3.13-slim
  handler: routers.router_while_with_break_flow_seq_set_i_2
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_FINALIZE
    value: while_with_break.handler_finalize
  - name: ASYA_HANDLER_ACTOR_HANDLER_INIT
    value: while_with_break.handler_init
  - name: ASYA_HANDLER_ACTOR_HANDLER_PROCESS
    value: while_with_break.handler_process
  - name: ASYA_HANDLER_ROUTER_WHILE_WITH_BREAK_FLOW_IF_STOP_CONDITION
    value: routers.router_while_with_break_flow_if_stop_condition
  - name: ASYA_HANDLER_ROUTER_WHILE_WITH_BREAK_FLOW_SEQ_SET_I
    value: routers.router_while_with_break_flow_seq_set_i
  - name: ASYA_HANDLER_ROUTER_WHILE_WITH_BREAK_FLOW_SEQ_SET_I_2
    value: routers.router_while_with_break_flow_seq_set_i_2
  - name: ASYA_HANDLER_ROUTER_WHILE_WITH_BREAK_FLOW_WHILE_I_LT_MAX_ITERATIONS
    value: routers.router_while_with_break_flow_while_i_lt_max_iterations
  volumes:
  - name: routers
    configMap:
      name: while-with-break-flow-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
