apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handler-finalize.yaml
- asya-actor-handler-init.yaml
- asya-actor-handler-process.yaml
- asya-router-while-with-break-flow-if-stop-condition.yaml
- asya-router-while-with-break-flow-seq-set-i-2.yaml
- asya-router-while-with-break-flow-seq-set-i.yaml
- asya-router-while-with-break-flow-while-i-lt-max-iterations.yaml
- asya-start-while-with-break-flow.yaml
- configmap-routers.yaml
