apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-shout
  namespace: default
  labels:
    asya.sh/flow: bare-script-flow
    asya.sh/role: end
spec:
  actor: actor-shout
  image: examples.asya.sh/shout:latest
  handler: bare_script_flow.shout
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
