apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-greet
  namespace: default
  labels:
    asya.sh/flow: bare-script-flow
spec:
  actor: actor-greet
  image: examples.asya.sh/greet:latest
  handler: bare_script_flow.greet
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
