apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-clean-text.yaml
- asya-actor-english-sentiment.yaml
- asya-actor-extract-entities.yaml
- asya-actor-spanish-sentiment.yaml
- asya-actor-tokenize.yaml
- asya-router-text-analysis-flow-if-language-eq-en.yaml
- asya-router-text-analysis-flow-if-language-eq-es.yaml
- asya-router-text-analysis-flow-seq-set-extracted.yaml
- asya-router-text-analysis-flow-seq-set-sentiment.yaml
- asya-start-text-analysis-flow.yaml
- configmap-routers.yaml
