flowchart TD
    %% Flow: with_inline_ctx

    fulfillment_handler[fulfillment_handler]
    payment_processor[payment_processor]
    router_order_processing_line_27_with{{router_order_processing_line_27_with}}
    router_order_processing_line_30_if{{router_order_processing_line_30_if}}
    router_order_processing_line_33_seq{{"router_order_processing_line_33_seq<br/><br/>p['status'] = 'rejected'"}}
    router_order_processing_line_36_seq{{"router_order_processing_line_36_seq<br/><br/>p['stage'] = 'fulfillment'"}}
    start_order_processing(["start_order_processing<br/><br/>p['stage'] = 'validation'"])
    validate_order[validate_order]
    __end__((( )))

    start_order_processing --> router_order_processing_line_27_with
    router_order_processing_line_36_seq --> fulfillment_handler
    router_order_processing_line_30_if -->|p.get('valid')| payment_processor
    payment_processor --> router_order_processing_line_36_seq
    router_order_processing_line_30_if -->|not (p.get('valid'))| router_order_processing_line_33_seq
    router_order_processing_line_27_with --> validate_order
    validate_order --> router_order_processing_line_30_if
    fulfillment_handler --> __end__
    router_order_processing_line_33_seq --> __end__