apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-risky-operation
  namespace: default
  labels:
    asya.sh/flow: resilient-pipeline
spec:
  actor: actor-risky-operation
  image: examples.asya.sh/risky-operation:latest
  handler: risky_operation
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
  resiliency:
    policies:
      except_valueerror:
        maxAttempts: 1
        thenRoute:
        - router-resilient-pipeline-except-valueerror
      default:
        maxAttempts: 1
        thenRoute:
        - router-resilient-pipeline-except-all
    rules:
    - errors:
      - ValueError
      policy: except_valueerror
