apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-risky-operation
  namespace: default
  labels:
    asya.sh/flow: resilient-pipeline
spec:
  actor: actor-risky-operation
  image: examples.asya.sh/risky-operation:latest
  handler: risky_operation
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
  resiliency:
    policies:
      try_except_line_6_0:
        maxAttempts: 1
        thenRoute:
        - router-resilient-pipeline-line-8-except-1
      default:
        maxAttempts: 1
        thenRoute:
        - router-resilient-pipeline-line-11-except-2
    rules:
    - errors:
      - ValueError
      policy: try_except_line_6_0
