apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handle-known-error
  namespace: default
  labels:
    asya.sh/flow: resilient-pipeline
    asya.sh/role: end
spec:
  actor: actor-handle-known-error
  image: examples.asya.sh/handle-known-error:latest
  handler: handle_known_error
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
