apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handle-known-error.yaml
- asya-actor-handle-unknown-error.yaml
- asya-actor-risky-operation.yaml
- asya-router-try-except-catch-all-except-all.yaml
- asya-router-try-except-catch-all-except-valueerror.yaml
- asya-start-try-except-catch-all.yaml
- configmap-routers.yaml
