flowchart TD
    %% Flow: resilient_pipeline

    handle_known_error[handle_known_error]
    handle_unknown_error[handle_unknown_error]
    risky_operation[risky_operation]
    router_resilient_pipeline_line_11_except_4{{router_resilient_pipeline_line_11_except_4}}
    router_resilient_pipeline_line_12_seq_3{{"router_resilient_pipeline_line_12_seq_3<br/><br/>p['error_type'] = 'unknown'"}}
    router_resilient_pipeline_line_8_except_2{{router_resilient_pipeline_line_8_except_2}}
    router_resilient_pipeline_line_9_seq_1{{"router_resilient_pipeline_line_9_seq_1<br/><br/>p['error_type'] = 'known'"}}
    start_resilient_pipeline([start_resilient_pipeline])
    __end__((( )))

    start_resilient_pipeline --> risky_operation
    router_resilient_pipeline_line_9_seq_1 --> handle_known_error
    router_resilient_pipeline_line_8_except_2 --> router_resilient_pipeline_line_9_seq_1
    router_resilient_pipeline_line_12_seq_3 --> handle_unknown_error
    router_resilient_pipeline_line_11_except_4 --> router_resilient_pipeline_line_12_seq_3
    risky_operation -->|"ValueError"| router_resilient_pipeline_line_8_except_2
    risky_operation -->|"except *"| router_resilient_pipeline_line_11_except_4
    handle_known_error --> __end__
    handle_unknown_error --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_resilient_pipeline start
    class handle_known_error,handle_unknown_error endnode
    class router_resilient_pipeline_line_11_except_4,router_resilient_pipeline_line_12_seq_3,router_resilient_pipeline_line_8_except_2,router_resilient_pipeline_line_9_seq_1 router
    class risky_operation handler
    class __end__ endpoint
    linkStyle 5,6 stroke:#DC143C