apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-parse-syntax
  namespace: default
  labels:
    asya.sh/flow: compiler-pipeline
spec:
  actor: actor-parse-syntax
  image: examples.asya.sh/parse-syntax:latest
  handler: parse_syntax
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
