apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-calculate.yaml
- asya-actor-format-response.yaml
- asya-actor-get-weather.yaml
- asya-actor-list-gcs-files.yaml
- asya-actor-llm-reason.yaml
- asya-actor-web-search.yaml
- asya-router-tool-calling-agent-if-not-tool-name.yaml
- asya-router-tool-calling-agent-if-tool-name-eq-calculate.yaml
- asya-router-tool-calling-agent-if-tool-name-eq-get-weather.yaml
- asya-router-tool-calling-agent-if-tool-name-eq-list-gcs-files.yaml
- asya-router-tool-calling-agent-if-tool-name-eq-web-search.yaml
- asya-router-tool-calling-agent-seq-set-iteration.yaml
- asya-router-tool-calling-agent-seq-set-messages.yaml
- asya-router-tool-calling-agent-while-loop.yaml
- asya-start-tool-calling-agent.yaml
- configmap-calculate-adapter.yaml
- configmap-get-weather-adapter.yaml
- configmap-list-gcs-files-adapter.yaml
- configmap-routers.yaml
- configmap-web-search-adapter.yaml
