apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-data-validator
  namespace: default
  labels:
    asya.sh/flow: ingestion-pipeline
spec:
  actor: actor-data-validator
  image: examples.asya.sh/data-validator:latest
  handler: data_validator
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
  resiliency:
    timeout:
      actor: 60
