apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: data-writer
  namespace: default
  labels:
    asya.sh/flow: ingestion-pipeline
    asya.sh/role: end
spec:
  actor: data-writer
  image: examples.asya.sh/data-writer:latest
  handler: data_writer
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
