apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: data-fetcher
  namespace: default
  labels:
    asya.sh/flow: ingestion-pipeline
spec:
  actor: data-fetcher
  image: examples.asya.sh/data-fetcher:latest
  handler: data_fetcher
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
