apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-data-fetcher.yaml
- asyncactor-data-parser.yaml
- asyncactor-data-validator.yaml
- asyncactor-data-writer.yaml
- asyncactor-start-ingestion-pipeline.yaml
- configmap-routers.yaml
