apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: notify-payment-failure
  namespace: default
  labels:
    asya.sh/flow: payment-flow
spec:
  actor: notify-payment-failure
  image: examples.asya.sh/notify-payment-failure:latest
  handler: notify_payment_failure
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
