apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-decorator-callsite-flow-seq-p-stamp-timestamp-p
  namespace: default
  labels:
    asya.sh/flow: decorator-callsite-flow
    asya.sh/generated: 'true'
spec:
  actor: router-decorator-callsite-flow-seq-p-stamp-timestamp-p
  image: python:3.13-slim
  handler: routers.router_decorator_callsite_flow_seq_p_stamp_timestamp_p
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_ENRICHER
    value: enricher
  - name: ASYA_HANDLER_ACTOR_VALIDATOR
    value: validator
