apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-while-nested-flow
  namespace: default
  labels:
    asya.sh/flow: while-nested-flow
    asya.sh/role: start
    asya.sh/generated: 'true'
spec:
  actor: start-while-nested-flow
  image: python:3.13-slim
  handler: routers.start_while_nested_flow
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ROUTER_WHILE_NESTED_FLOW_LINE_14_WHILE_1
    value: routers.router_while_nested_flow_line_14_while_1
  - name: ASYA_HANDLER_ROUTER_WHILE_NESTED_FLOW_LINE_15_SEQ_4
    value: routers.router_while_nested_flow_line_15_seq_4
  - name: ASYA_HANDLER_ROUTER_WHILE_NESTED_FLOW_LINE_18_WHILE_2
    value: routers.router_while_nested_flow_line_18_while_2
  - name: ASYA_HANDLER_ROUTER_WHILE_NESTED_FLOW_LINE_19_SEQ_3
    value: routers.router_while_nested_flow_line_19_seq_3
