apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-finalize
  namespace: default
  labels:
    asya.sh/flow: while-nested-flow
    asya.sh/role: end
spec:
  actor: actor-handler-finalize
  image: examples.asya.sh/handler-finalize:latest
  handler: handler_finalize
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
