apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-analysis-worker.yaml
- asya-actor-data-worker.yaml
- asya-actor-orchestrator.yaml
- asya-actor-synthesizer.yaml
- asya-actor-writing-worker.yaml
- asya-router-orchestrator-workers-if-is-complete.yaml
- asya-router-orchestrator-workers-if-iteration-ge-10.yaml
- asya-router-orchestrator-workers-if-next-action-eq-analyze.yaml
- asya-router-orchestrator-workers-if-next-action-eq-research.yaml
- asya-router-orchestrator-workers-if-next-action-eq-write.yaml
- asya-router-orchestrator-workers-seq-set-iteration-2.yaml
- asya-router-orchestrator-workers-seq-set-iteration.yaml
- asya-router-orchestrator-workers-while-loop.yaml
- asya-start-orchestrator-workers.yaml
- configmap-routers.yaml
