apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-language-detector.yaml
- asya-actor-ocr-extractor.yaml
- asya-actor-sentiment-analyzer.yaml
- asya-actor-translator.yaml
- asya-router-document-pipeline-if-language-ne-en.yaml
- asya-router-document-pipeline-seq-set-status.yaml
- asya-start-document-pipeline.yaml
- configmap-routers.yaml
