apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-react-tool-loop-if-iteration-ge-10
  namespace: default
  labels:
    asya.sh/flow: react-tool-loop
    asya.sh/generated: 'true'
spec:
  actor: router-react-tool-loop-if-iteration-ge-10
  image: python:3.13-slim
  handler: routers.router_react_tool_loop_if_iteration_ge_10
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CALCULATOR
    value: react_tool_loop.calculator
  - name: ASYA_HANDLER_ACTOR_CODE_EXEC
    value: react_tool_loop.code_exec
  - name: ASYA_HANDLER_ACTOR_FORMAT_RESPONSE
    value: react_tool_loop.format_response
  - name: ASYA_HANDLER_ACTOR_LLM_REASON
    value: react_tool_loop.llm_reason
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_IF_ITERATION_GE_10
    value: routers.router_react_tool_loop_if_iteration_ge_10
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_IF_NOT_TOOL_CALLS
    value: routers.router_react_tool_loop_if_not_tool_calls
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_IF_TOOL_NAME_EQ_CALCULATOR
    value: routers.router_react_tool_loop_if_tool_name_eq_calculator
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_IF_TOOL_NAME_EQ_CODE_EXEC
    value: routers.router_react_tool_loop_if_tool_name_eq_code_exec
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_IF_TOOL_NAME_EQ_WEB_SEARCH
    value: routers.router_react_tool_loop_if_tool_name_eq_web_search
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_SEQ_SET_ITERATION
    value: routers.router_react_tool_loop_seq_set_iteration
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_SEQ_SET_OBSERVATION
    value: routers.router_react_tool_loop_seq_set_observation
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_WHILE_LOOP
    value: routers.router_react_tool_loop_while_loop
  - name: ASYA_HANDLER_ACTOR_WEB_SEARCH
    value: react_tool_loop.web_search
  volumes:
  - name: routers
    configMap:
      name: react-tool-loop-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
