apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-react-tool-loop-line-49-while-1
  namespace: default
  labels:
    asya.sh/flow: react-tool-loop
    asya.sh/generated: 'true'
spec:
  actor: router-react-tool-loop-line-49-while-1
  image: python:3.13-slim
  handler: routers.router_react_tool_loop_line_49_while_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CALCULATOR
    value: calculator
  - name: ASYA_HANDLER_ACTOR_CODE_EXEC
    value: code_exec
  - name: ASYA_HANDLER_ACTOR_FORMAT_RESPONSE
    value: format_response
  - name: ASYA_HANDLER_ACTOR_LLM_REASON
    value: llm_reason
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_LINE_49_WHILE_1
    value: routers.router_react_tool_loop_line_49_while_1
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_LINE_50_SEQ_8
    value: routers.router_react_tool_loop_line_50_seq_8
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_LINE_56_IF_7
    value: routers.router_react_tool_loop_line_56_if_7
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_LINE_62_IF_6
    value: routers.router_react_tool_loop_line_62_if_6
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_LINE_64_IF_5
    value: routers.router_react_tool_loop_line_64_if_5
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_LINE_66_IF_4
    value: routers.router_react_tool_loop_line_66_if_4
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_LINE_69_SEQ_3
    value: routers.router_react_tool_loop_line_69_seq_3
  - name: ASYA_HANDLER_ROUTER_REACT_TOOL_LOOP_LINE_75_IF_2
    value: routers.router_react_tool_loop_line_75_if_2
  - name: ASYA_HANDLER_ACTOR_WEB_SEARCH
    value: web_search
