apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-calculator.yaml
- asya-actor-code-exec.yaml
- asya-actor-format-response.yaml
- asya-actor-llm-reason.yaml
- asya-actor-web-search.yaml
- asya-router-react-tool-loop-line-46-seq-9.yaml
- asya-router-react-tool-loop-line-49-while-1.yaml
- asya-router-react-tool-loop-line-50-seq-8.yaml
- asya-router-react-tool-loop-line-56-if-7.yaml
- asya-router-react-tool-loop-line-62-if-6.yaml
- asya-router-react-tool-loop-line-64-if-5.yaml
- asya-router-react-tool-loop-line-66-if-4.yaml
- asya-router-react-tool-loop-line-69-seq-3.yaml
- asya-router-react-tool-loop-line-75-if-2.yaml
- asya-start-react-tool-loop.yaml
- configmap-routers.yaml
