apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-calculator.yaml
- asyncactor-code-exec.yaml
- asyncactor-format-response.yaml
- asyncactor-llm-reason.yaml
- asyncactor-router-react-tool-loop-line-46-seq-9.yaml
- asyncactor-router-react-tool-loop-line-49-while-1.yaml
- asyncactor-router-react-tool-loop-line-50-seq-8.yaml
- asyncactor-router-react-tool-loop-line-56-if-7.yaml
- asyncactor-router-react-tool-loop-line-62-if-6.yaml
- asyncactor-router-react-tool-loop-line-64-if-5.yaml
- asyncactor-router-react-tool-loop-line-66-if-4.yaml
- asyncactor-router-react-tool-loop-line-69-seq-3.yaml
- asyncactor-router-react-tool-loop-line-75-if-2.yaml
- asyncactor-start-react-tool-loop.yaml
- asyncactor-web-search.yaml
- configmap-routers.yaml
