flowchart TD
    %% Flow: while_with_continue_flow

    handler_finalize[handler_finalize]
    handler_init[handler_init]
    handler_process[handler_process]
    router_while_with_continue_flow_if_skip_iteration{{"router_while_with_continue_flow_if_skip_iteration<br/><br/>p['i'] += 1"}}
    router_while_with_continue_flow_seq_set_i{{"router_while_with_continue_flow_seq_set_i<br/><br/>p['i'] = 0"}}
    router_while_with_continue_flow_while_i_lt_max_iterations{{router_while_with_continue_flow_while_i_lt_max_iterations}}
    start_while_with_continue_flow([start_while_with_continue_flow])
    __end__((( )))

    start_while_with_continue_flow --> handler_init
    handler_init --> router_while_with_continue_flow_seq_set_i
    router_while_with_continue_flow_if_skip_iteration -->|"p['skip_iteration']"| router_while_with_continue_flow_while_i_lt_max_iterations
    router_while_with_continue_flow_if_skip_iteration -->|"else"| handler_process
    router_while_with_continue_flow_while_i_lt_max_iterations -->|"p['i'] < p['max_iterations']"| router_while_with_continue_flow_if_skip_iteration
    router_while_with_continue_flow_while_i_lt_max_iterations -->|"else"| handler_finalize
    router_while_with_continue_flow_seq_set_i --> router_while_with_continue_flow_while_i_lt_max_iterations
    handler_process --> router_while_with_continue_flow_while_i_lt_max_iterations
    handler_finalize --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_while_with_continue_flow start
    class handler_finalize,__end__ endnode
    class router_while_with_continue_flow_if_skip_iteration,router_while_with_continue_flow_seq_set_i,router_while_with_continue_flow_while_i_lt_max_iterations router
    class handler_init,handler_process handler
    linkStyle 2,4 stroke:#2E8B57
    linkStyle 3,5 stroke:#E07040