flowchart TD
    %% Flow: while_with_continue_flow

    end_while_with_continue_flow([end_while_with_continue_flow])
    handler_finalize[handler_finalize]
    router_while_with_continue_flow_line_14_while_1{{router_while_with_continue_flow_line_14_while_1}}

    router_while_with_continue_flow_line_14_while_1 -->|p['i'] < p['max_iterations']| handler_finalize