# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../minimal.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../minimal.py
"""


# ======================================================================
# Single-Actor Flow: no router needed
# The actor below IS the entrypoint; label it in your AsyncActor spec:
#   asya.sh/flow: minimal_flow
#   asya.sh/flow-role: entry
# ======================================================================

FLOW_METADATA = {
    "flow_name": "minimal_flow",
    "type": "single-actor",
    "actor": 'handler_a',
    "labels": {
        "asya.sh/flow": "minimal_flow",
        "asya.sh/flow-role": "start",
    },
}
