apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-call-primary
  namespace: default
  labels:
    asya.sh/flow: failover-pipeline
spec:
  actor: actor-call-primary
  image: examples.asya.sh/call-primary:latest
  handler: call_primary
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env:
  - name: ASYA_IGNORE_DECORATORS
    value: tenacity.retry
  resiliency:
    policies:
      try_except_line_25_0:
        maxAttempts: 1
        thenRoute:
        - router-failover-pipeline-line-27-except-1
      try_except_line_25_1:
        maxAttempts: 1
        thenRoute:
        - router-failover-pipeline-line-30-except-2
      default:
        maxAttempts: '3'
    rules:
    - errors:
      - ConnectionError
      policy: try_except_line_25_0
    - errors:
      - ValueError
      policy: try_except_line_25_1
