templates:
  namespace: default
  router_image: "python:3.13-slim"
  max_replicas: 5

compiler:
  routers: "./compiled"
  manifests: "./compiled"
  templates: ".asya/templates"

build:
- module: "*"
  image: "examples.asya.sh/*:latest"
