flowchart TD
    %% Flow: research_flow

    fanin_research_flow_line_7[fanin_research_flow_line_7]
    research_agent[research_agent]
    router_research_flow_line_7_fanout_1{{router_research_flow_line_7_fanout_1}}
    start_research_flow([start_research_flow])
    summarizer[summarizer]
    __end__((( )))

    start_research_flow --> router_research_flow_line_7_fanout_1
    router_research_flow_line_7_fanout_1 -->|"fanout: p['topics']"| fanin_research_flow_line_7
    fanin_research_flow_line_7 --> summarizer
    router_research_flow_line_7_fanout_1 --> research_agent
    research_agent --> fanin_research_flow_line_7
    summarizer --> __end__