apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-core-agent
  namespace: default
  labels:
    asya.sh/flow: guardrails-sandwich
spec:
  actor: actor-core-agent
  image: examples.asya.sh/core-agent:latest
  handler: core_agent
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
  resiliency:
    policies:
      except_exception:
        maxAttempts: 1
        thenRoute:
        - router-guardrails-sandwich-except-exception
    rules:
    - errors:
      - Exception
      policy: except_exception
