apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-core-agent.yaml
- asya-actor-input-validator.yaml
- asya-actor-output-validator.yaml
- asya-actor-safe-fallback.yaml
- asya-router-guardrails-sandwich-except-exception.yaml
- asya-start-guardrails-sandwich.yaml
- configmap-routers.yaml
