apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: validate-order
  namespace: default
  labels:
    asya.sh/flow: order-pipeline
spec:
  actor: validate-order
  image: examples.asya.sh/validate-order:latest
  handler: validate_order
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
