apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-router-order-pipeline-line-27-seq-3.yaml
- asyncactor-router-order-pipeline-line-32-if-2.yaml
- asyncactor-router-order-pipeline-line-33-seq-1.yaml
- asyncactor-start-order-pipeline.yaml
- asyncactor-validate-order.yaml
- configmap-routers.yaml
