apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-charge-payment.yaml
- asya-actor-validate-order.yaml
- asya-router-order-pipeline-if-fraud-score-gt-0.8.yaml
- asya-router-order-pipeline-seq-set-status.yaml
- asya-start-order-pipeline.yaml
- configmap-routers.yaml
