apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: executor
  namespace: default
  labels:
    asya.sh/flow: human-in-the-loop
spec:
  actor: executor
  image: examples.asya.sh/executor:latest
  handler: executor
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
