apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-decorator-inline-comments-flow-line-45-seq-2
  namespace: default
  labels:
    asya.sh/flow: decorator-inline-comments-flow
    asya.sh/generated: 'true'
spec:
  actor: router-decorator-inline-comments-flow-line-45-seq-2
  image: python:3.13-slim
  handler: routers.router_decorator_inline_comments_flow_line_45_seq_2
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_CLASSIFIER
    value: classifier
  - name: ASYA_HANDLER_ROUTER_DECORATOR_INLINE_COMMENTS_FLOW_LINE_18_IF_3
    value: routers.router_decorator_inline_comments_flow_line_18_if_3
  - name: ASYA_HANDLER_ROUTER_DECORATOR_INLINE_COMMENTS_FLOW_LINE_39_SEQ_1
    value: routers.router_decorator_inline_comments_flow_line_39_seq_1
  - name: ASYA_HANDLER_ROUTER_DECORATOR_INLINE_COMMENTS_FLOW_LINE_45_SEQ_2
    value: routers.router_decorator_inline_comments_flow_line_45_seq_2
