apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-classifier.yaml
- asya-actor-fast-handler.yaml
- asya-actor-standard-handler.yaml
- asya-router-decorator-inline-comments-flow-if-category-eq-priority.yaml
- asya-start-decorator-inline-comments-flow.yaml
- configmap-routers.yaml
