apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-translate
  namespace: demo-skaffold
  labels:
    asya.sh/flow: pipeline
    asya.sh/role: end
spec:
  actor: actor-translate
  image: europe-west1-docker.pkg.dev/foodsci-img-gen-dev-1407-1448/asya-demo/skaffold-translator:v0.5.7-10-g8df83ba2
  handler: translator.handler.translate
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
