apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-analyze
  namespace: demo-skaffold
  labels:
    asya.sh/flow: pipeline
spec:
  actor: actor-analyze
  image: europe-west1-docker.pkg.dev/foodsci-img-gen-dev-1407-1448/asya-demo/skaffold-sentiment-actors:v0.5.7-10-g8df83ba2-dirty
  handler: sentiment_actors.handler.analyze
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
