flowchart TD
    %% Flow: while_break_continue_flow

    handler_check[handler_check]
    handler_finalize[handler_finalize]
    handler_init[handler_init]
    handler_process[handler_process]
    router_while_break_continue_flow_line_13_seq_5{{"router_while_break_continue_flow_line_13_seq_5<br/><br/>p['i'] = 0"}}
    router_while_break_continue_flow_line_14_while_1{{router_while_break_continue_flow_line_14_while_1}}
    router_while_break_continue_flow_line_15_seq_4{{"router_while_break_continue_flow_line_15_seq_4<br/><br/>p['i'] += 1"}}
    router_while_break_continue_flow_line_17_if_3{{router_while_break_continue_flow_line_17_if_3}}
    router_while_break_continue_flow_line_20_if_2{{router_while_break_continue_flow_line_20_if_2}}
    start_while_break_continue_flow([start_while_break_continue_flow])
    __end__((( )))

    start_while_break_continue_flow --> handler_init
    handler_init --> router_while_break_continue_flow_line_13_seq_5
    router_while_break_continue_flow_line_20_if_2 -->|"p['stop']"| handler_finalize
    router_while_break_continue_flow_line_17_if_3 -->|"p['skip']"| router_while_break_continue_flow_line_14_while_1
    router_while_break_continue_flow_line_17_if_3 -->|"else"| handler_process
    handler_process --> router_while_break_continue_flow_line_20_if_2
    router_while_break_continue_flow_line_15_seq_4 --> handler_check
    handler_check --> router_while_break_continue_flow_line_17_if_3
    router_while_break_continue_flow_line_14_while_1 -->|"p['i'] < p['max_iterations']"| router_while_break_continue_flow_line_15_seq_4
    router_while_break_continue_flow_line_14_while_1 -->|"else"| handler_finalize
    router_while_break_continue_flow_line_13_seq_5 --> router_while_break_continue_flow_line_14_while_1
    router_while_break_continue_flow_line_20_if_2 -->|"else"| router_while_break_continue_flow_line_14_while_1
    handler_finalize --> __end__

    classDef entrypoint fill:#98FB98,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_while_break_continue_flow entrypoint
    class router_while_break_continue_flow_line_13_seq_5,router_while_break_continue_flow_line_14_while_1,router_while_break_continue_flow_line_15_seq_4,router_while_break_continue_flow_line_17_if_3,router_while_break_continue_flow_line_20_if_2 router
    class handler_check,handler_finalize,handler_init,handler_process handler
    class __end__ endpoint
    linkStyle 2,3,8 stroke:#2E8B57
    linkStyle 4,9,11 stroke:#E07040