flowchart TD
    %% Flow: test_nested_flow

    finalize_result[finalize_result]
    route_a_x[route_a_x]
    route_a_y[route_a_y]
    route_b_x[route_b_x]
    route_b_y[route_b_y]
    router_test_nested_flow_if_level1_eq_a{{router_test_nested_flow_if_level1_eq_a}}
    router_test_nested_flow_if_level2_eq_x{{"router_test_nested_flow_if_level2_eq_x<br/><br/>p['path'] = 'A'"}}
    router_test_nested_flow_if_level2_eq_x_2{{"router_test_nested_flow_if_level2_eq_x_2<br/><br/>p['path'] = 'B'"}}
    router_test_nested_flow_seq_set_route{{"router_test_nested_flow_seq_set_route<br/><br/>p['route'] = 'A-X'"}}
    router_test_nested_flow_seq_set_route_2{{"router_test_nested_flow_seq_set_route_2<br/><br/>p['route'] = 'A-Y'"}}
    router_test_nested_flow_seq_set_route_3{{"router_test_nested_flow_seq_set_route_3<br/><br/>p['route'] = 'B-X'"}}
    router_test_nested_flow_seq_set_route_4{{"router_test_nested_flow_seq_set_route_4<br/><br/>p['route'] = 'B-Y'"}}
    start_test_nested_flow([start_test_nested_flow])
    validate_input[validate_input]
    __end__((( )))

    start_test_nested_flow --> validate_input
    validate_input --> router_test_nested_flow_if_level1_eq_a
    router_test_nested_flow_seq_set_route --> route_a_x
    router_test_nested_flow_seq_set_route_2 --> route_a_y
    router_test_nested_flow_if_level2_eq_x -->|"p['level2'] == 'X'"| router_test_nested_flow_seq_set_route
    router_test_nested_flow_if_level2_eq_x -->|"else"| router_test_nested_flow_seq_set_route_2
    router_test_nested_flow_seq_set_route_3 --> route_b_x
    router_test_nested_flow_seq_set_route_4 --> route_b_y
    router_test_nested_flow_if_level2_eq_x_2 -->|"p['level2'] == 'X'"| router_test_nested_flow_seq_set_route_3
    router_test_nested_flow_if_level2_eq_x_2 -->|"else"| router_test_nested_flow_seq_set_route_4
    router_test_nested_flow_if_level1_eq_a -->|"p['level1'] == 'A'"| router_test_nested_flow_if_level2_eq_x
    router_test_nested_flow_if_level1_eq_a -->|"else"| router_test_nested_flow_if_level2_eq_x_2
    route_a_x --> finalize_result
    route_a_y --> finalize_result
    route_b_x --> finalize_result
    route_b_y --> finalize_result
    finalize_result --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_test_nested_flow start
    class finalize_result endnode
    class router_test_nested_flow_if_level1_eq_a,router_test_nested_flow_if_level2_eq_x,router_test_nested_flow_if_level2_eq_x_2,router_test_nested_flow_seq_set_route,router_test_nested_flow_seq_set_route_2,router_test_nested_flow_seq_set_route_3,router_test_nested_flow_seq_set_route_4 router
    class route_a_x,route_a_y,route_b_x,route_b_y,validate_input handler
    class __end__ endpoint
    linkStyle 4,8,10 stroke:#2E8B57
    linkStyle 5,9,11 stroke:#E07040