apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-text-analysis-flow-seq-set-extracted
  namespace: default
  labels:
    asya.sh/flow: text-analysis-flow
    asya.sh/generated: 'true'
spec:
  actor: router-text-analysis-flow-seq-set-extracted
  image: python:3.13-slim
  handler: routers.router_text_analysis_flow_seq_set_extracted
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CLEAN_TEXT
    value: text_analysis_flow.clean_text
  - name: ASYA_HANDLER_ACTOR_ENGLISH_SENTIMENT
    value: text_analysis_flow.english_sentiment
  - name: ASYA_HANDLER_ACTOR_EXTRACT_ENTITIES
    value: text_analysis_flow.extract_entities
  - name: ASYA_HANDLER_ROUTER_TEXT_ANALYSIS_FLOW_IF_LANGUAGE_EQ_EN
    value: routers.router_text_analysis_flow_if_language_eq_en
  - name: ASYA_HANDLER_ROUTER_TEXT_ANALYSIS_FLOW_IF_LANGUAGE_EQ_ES
    value: routers.router_text_analysis_flow_if_language_eq_es
  - name: ASYA_HANDLER_ROUTER_TEXT_ANALYSIS_FLOW_SEQ_SET_EXTRACTED
    value: routers.router_text_analysis_flow_seq_set_extracted
  - name: ASYA_HANDLER_ROUTER_TEXT_ANALYSIS_FLOW_SEQ_SET_SENTIMENT
    value: routers.router_text_analysis_flow_seq_set_sentiment
  - name: ASYA_HANDLER_ACTOR_SPANISH_SENTIMENT
    value: text_analysis_flow.spanish_sentiment
  - name: ASYA_HANDLER_ACTOR_TOKENIZE
    value: text_analysis_flow.tokenize
  volumes:
  - name: routers
    configMap:
      name: text-analysis-flow-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
