flowchart TD
    %% Flow: typeddict_pipeline

    error_handler[error_handler]
    parser[parser]
    router_typeddict_pipeline_line_77_if_1{{router_typeddict_pipeline_line_77_if_1}}
    sink_adapter[sink_adapter]
    start_typeddict_pipeline([start_typeddict_pipeline])
    transformer[transformer]
    validator[validator]
    __end__((( )))

    start_typeddict_pipeline --> parser
    parser --> validator
    validator --> router_typeddict_pipeline_line_77_if_1
    router_typeddict_pipeline_line_77_if_1 -->|"else"| transformer
    transformer --> sink_adapter
    router_typeddict_pipeline_line_77_if_1 -->|"not p.get('valid', True)"| error_handler
    error_handler --> __end__
    sink_adapter --> __end__

    classDef entrypoint fill:#98FB98,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_typeddict_pipeline entrypoint
    class router_typeddict_pipeline_line_77_if_1 router
    class error_handler,parser,sink_adapter,transformer,validator handler
    class __end__ endpoint
    linkStyle 5 stroke:#2E8B57
    linkStyle 3 stroke:#E07040