flowchart TD
    %% Flow: while_loop_processing

    check_threshold[check_threshold]
    finalize_loop[finalize_loop]
    initialize[initialize]
    process_abort[process_abort]
    process_item[process_item]
    router_loop_flow_line_15_seq_7{{"router_loop_flow_line_15_seq_7<br/><br/>p['iteration'] = 0"}}
    router_loop_flow_line_16_while_1{{router_loop_flow_line_16_while_1}}
    router_loop_flow_line_17_seq_6{{"router_loop_flow_line_17_seq_6<br/><br/>p['iteration'] += 1"}}
    router_loop_flow_line_20_if_5{{router_loop_flow_line_20_if_5}}
    router_loop_flow_line_21_seq_4{{"router_loop_flow_line_21_seq_4<br/><br/>p['abort'] = 1"}}
    router_loop_flow_line_23_seq_3{{"router_loop_flow_line_23_seq_3<br/><br/>p['abort'] = 2"}}
    router_loop_flow_line_27_if_2{{router_loop_flow_line_27_if_2}}
    start_loop_flow([start_loop_flow])
    __end__((( )))

    start_loop_flow --> initialize
    initialize --> router_loop_flow_line_15_seq_7
    router_loop_flow_line_27_if_2 -->|p['threshold_met']| finalize_loop
    router_loop_flow_line_23_seq_3 --> router_loop_flow_line_16_while_1
    router_loop_flow_line_21_seq_4 --> process_abort
    process_abort --> router_loop_flow_line_23_seq_3
    router_loop_flow_line_20_if_5 -->|p.get('skip_threshold_check')| router_loop_flow_line_21_seq_4
    router_loop_flow_line_20_if_5 -->|not (p.get('skip_threshold_check'))| check_threshold
    check_threshold --> router_loop_flow_line_27_if_2
    router_loop_flow_line_17_seq_6 --> process_item
    process_item --> router_loop_flow_line_20_if_5
    router_loop_flow_line_16_while_1 -->|p['iteration'] < p['max_iterations']| router_loop_flow_line_17_seq_6
    router_loop_flow_line_16_while_1 -->|not (p['iteration'] < p['max_iterations'])| finalize_loop
    router_loop_flow_line_15_seq_7 --> router_loop_flow_line_16_while_1
    router_loop_flow_line_20_if_5 --> router_loop_flow_line_16_while_1
    finalize_loop --> __end__