templates:
  namespace: demo-skaffold
  router_image: "python:3.13-slim"
  max_replicas: 5

build:
- module: "analyze"
  image: "skaffold-sentiment-actors"
- module: "summarize"
  image: "skaffold-summarizer"
- module: "translate"
  image: "skaffold-translator"

compiler:
  routers: "./compiled"
  manifests: ".asya/manifests"
  templates: ".asya/templates"
