apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-analyze.yaml
- asyncactor-start-pipeline.yaml
- asyncactor-summarize.yaml
- asyncactor-translate.yaml
- configmap-routers.yaml
