flowchart TD
    %% Flow: while_with_break

    handler_finalize[handler_finalize]
    handler_init[handler_init]
    handler_process[handler_process]
    router_while_with_break_flow_line_13_seq_4{{"router_while_with_break_flow_line_13_seq_4<br/><br/>p['i'] = 0"}}
    router_while_with_break_flow_line_14_while_1{{router_while_with_break_flow_line_14_while_1}}
    router_while_with_break_flow_line_15_seq_3{{"router_while_with_break_flow_line_15_seq_3<br/><br/>p['i'] += 1"}}
    router_while_with_break_flow_line_17_if_2{{router_while_with_break_flow_line_17_if_2}}
    start_while_with_break_flow([start_while_with_break_flow])
    __end__((( )))

    start_while_with_break_flow --> handler_init
    handler_init --> router_while_with_break_flow_line_13_seq_4
    router_while_with_break_flow_line_17_if_2 -->|p['stop_condition']| handler_finalize
    router_while_with_break_flow_line_15_seq_3 --> handler_process
    handler_process --> router_while_with_break_flow_line_17_if_2
    router_while_with_break_flow_line_14_while_1 -->|p['i'] < p['max_iterations']| router_while_with_break_flow_line_15_seq_3
    router_while_with_break_flow_line_14_while_1 -->|not (p['i'] < p['max_iterations'])| handler_finalize
    router_while_with_break_flow_line_13_seq_4 --> router_while_with_break_flow_line_14_while_1
    router_while_with_break_flow_line_17_if_2 --> router_while_with_break_flow_line_14_while_1
    handler_finalize --> __end__