apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-topic-extractor
  namespace: default
  labels:
    asya.sh/flow: analysis-flow
spec:
  actor: actor-topic-extractor
  image: examples.asya.sh/topic-extractor:latest
  handler: 04_fanout.topic_extractor
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
