apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handler-a-x.yaml
- asya-actor-handler-a-y.yaml
- asya-actor-handler-b-x.yaml
- asya-actor-handler-b-y.yaml
- asya-actor-handler-finalize.yaml
- asya-actor-handler-validate.yaml
- asya-router-nested-if-flow-if-level1-eq-a.yaml
- asya-router-nested-if-flow-if-level2-eq-x-2.yaml
- asya-router-nested-if-flow-if-level2-eq-x.yaml
- asya-router-nested-if-flow-seq-set-l2-2.yaml
- asya-router-nested-if-flow-seq-set-l2-3.yaml
- asya-router-nested-if-flow-seq-set-l2-4.yaml
- asya-router-nested-if-flow-seq-set-l2.yaml
- asya-start-nested-if-flow.yaml
- configmap-routers.yaml
