apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-mutations-with-handler-flow-seq-set-finalized
  namespace: default
  labels:
    asya.sh/flow: mutations-with-handler-flow
    asya.sh/generated: 'true'
spec:
  actor: router-mutations-with-handler-flow-seq-set-finalized
  image: python:3.13-slim
  handler: routers.router_mutations_with_handler_flow_seq_set_finalized
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_PROCESS
    value: 07_mutations.handler_process
  - name: ASYA_HANDLER_ROUTER_MUTATIONS_WITH_HANDLER_FLOW_SEQ_SET_FINALIZED
    value: routers.router_mutations_with_handler_flow_seq_set_finalized
  volumes:
  - name: routers
    configMap:
      name: mutations-with-handler-flow-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
