apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: polisher
spec:
  actor: polisher
  transport: sqs
  image: asya-demo:latest
  handler: demo_handlers.polisher.polish
  flavors:
  - vertex-ai
  - llm-resilient
  scaling:
    minReplicaCount: 0
    maxReplicaCount: 1
    queueLength: 1
