flowchart TD
    %% Flow: nested_loop_flow

    finalize_loop_i[finalize_loop_i]
    finalize_loop_j[finalize_loop_j]
    initialize[initialize]
    process_item[process_item]
    router_nested_loop_flow_line_15_seq_5{{"router_nested_loop_flow_line_15_seq_5<br/><br/>p['i'] = 0"}}
    router_nested_loop_flow_line_16_while_1{{router_nested_loop_flow_line_16_while_1}}
    router_nested_loop_flow_line_17_seq_4{{"router_nested_loop_flow_line_17_seq_4<br/><br/>p['i'] += 1<br/>p['j'] = 0"}}
    router_nested_loop_flow_line_19_while_2{{router_nested_loop_flow_line_19_while_2}}
    router_nested_loop_flow_line_20_seq_3{{"router_nested_loop_flow_line_20_seq_3<br/><br/>p['j'] += 1"}}
    start_nested_loop_flow([start_nested_loop_flow])
    __end__((( )))

    start_nested_loop_flow --> initialize
    initialize --> router_nested_loop_flow_line_15_seq_5
    router_nested_loop_flow_line_20_seq_3 --> process_item
    router_nested_loop_flow_line_19_while_2 -->|"p['j'] < p['max_j']"| router_nested_loop_flow_line_20_seq_3
    router_nested_loop_flow_line_19_while_2 -->|"else"| finalize_loop_j
    router_nested_loop_flow_line_17_seq_4 --> router_nested_loop_flow_line_19_while_2
    router_nested_loop_flow_line_16_while_1 -->|"p['i'] < p['max_i']"| router_nested_loop_flow_line_17_seq_4
    router_nested_loop_flow_line_16_while_1 -->|"else"| finalize_loop_i
    router_nested_loop_flow_line_15_seq_5 --> router_nested_loop_flow_line_16_while_1
    process_item --> router_nested_loop_flow_line_19_while_2
    router_nested_loop_flow_line_20_seq_3 --> router_nested_loop_flow_line_16_while_1
    finalize_loop_i --> __end__
    finalize_loop_j --> __end__

    classDef entrypoint fill:#98FB98,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_nested_loop_flow entrypoint
    class router_nested_loop_flow_line_15_seq_5,router_nested_loop_flow_line_16_while_1,router_nested_loop_flow_line_17_seq_4,router_nested_loop_flow_line_19_while_2,router_nested_loop_flow_line_20_seq_3 router
    class finalize_loop_i,finalize_loop_j,initialize,process_item handler
    class __end__ endpoint
    linkStyle 3,6 stroke:#2E8B57
    linkStyle 4,7 stroke:#E07040