flowchart TD
    %% Flow: nested_loop_flow

    end_nested_loop_flow([end_nested_loop_flow])
    finalize_loop_i[finalize_loop_i]
    finalize_loop_j[finalize_loop_j]
    initialize[initialize]
    process_item[process_item]
    router_nested_loop_flow_line_15_seq_5{{router_nested_loop_flow_line_15_seq_5}}
    router_nested_loop_flow_line_16_while_1{{router_nested_loop_flow_line_16_while_1}}
    router_nested_loop_flow_line_17_seq_4{{router_nested_loop_flow_line_17_seq_4}}
    router_nested_loop_flow_line_19_while_2{{router_nested_loop_flow_line_19_while_2}}
    router_nested_loop_flow_line_20_seq_3{{router_nested_loop_flow_line_20_seq_3}}
    start_nested_loop_flow([start_nested_loop_flow])

    start_nested_loop_flow --> initialize
    initialize --> router_nested_loop_flow_line_15_seq_5
    router_nested_loop_flow_line_20_seq_3 --> process_item
    router_nested_loop_flow_line_19_while_2 -->|p['j'] < p['max_j']| router_nested_loop_flow_line_20_seq_3
    router_nested_loop_flow_line_20_seq_3 --> router_nested_loop_flow_line_19_while_2
    router_nested_loop_flow_line_19_while_2 -->|not (p['j'] < p['max_j'])| finalize_loop_j
    router_nested_loop_flow_line_17_seq_4 --> router_nested_loop_flow_line_19_while_2
    router_nested_loop_flow_line_16_while_1 -->|p['i'] < p['max_i']| router_nested_loop_flow_line_17_seq_4
    router_nested_loop_flow_line_17_seq_4 --> router_nested_loop_flow_line_16_while_1
    router_nested_loop_flow_line_16_while_1 -->|not (p['i'] < p['max_i'])| finalize_loop_i
    router_nested_loop_flow_line_15_seq_5 --> router_nested_loop_flow_line_16_while_1
    finalize_loop_i --> end_nested_loop_flow
    finalize_loop_j --> end_nested_loop_flow
    process_item --> end_nested_loop_flow