apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-adaptive-flow
  namespace: default
  labels:
    asya.sh/flow: adaptive-flow
    asya.sh/role: start
    asya.sh/generated: 'true'
spec:
  actor: start-adaptive-flow
  image: python:3.13-slim
  handler: routers.start_adaptive_flow
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_CLASSIFIER
    value: classifier
  - name: ASYA_HANDLER_ACTOR_DEEP_ANALYZER
    value: deep_analyzer
  - name: ASYA_HANDLER_FANIN_ADAPTIVE_FLOW_RESULTS
    value: routers.fanin_adaptive_flow_results
  - name: ASYA_HANDLER_ACTOR_FAST_ANALYZER
    value: fast_analyzer
  - name: ASYA_HANDLER_ACTOR_FORMATTER
    value: formatter
  - name: ASYA_HANDLER_ROUTER_ADAPTIVE_FLOW_FANOUT_RESULTS
    value: routers.router_adaptive_flow_fanout_results
  - name: ASYA_HANDLER_ROUTER_ADAPTIVE_FLOW_IF_PARALLEL
    value: routers.router_adaptive_flow_if_parallel
  - name: ASYA_HANDLER_ACTOR_SEQUENTIAL_ANALYZER
    value: sequential_analyzer
