apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-adaptive-flow-line-16-fanout-1
  namespace: default
  labels:
    asya.sh/flow: adaptive-flow
    asya.sh/generated: 'true'
spec:
  actor: router-adaptive-flow-line-16-fanout-1
  image: python:3.13-slim
  handler: routers.router_adaptive_flow_line_16_fanout_1
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_DEEP_ANALYZER
    value: deep_analyzer
  - name: ASYA_HANDLER_FANIN_ADAPTIVE_FLOW_LINE_16
    value: routers.fanin_adaptive_flow_line_16
  - name: ASYA_HANDLER_ACTOR_FAST_ANALYZER
    value: fast_analyzer
  - name: ASYA_HANDLER_ROUTER_ADAPTIVE_FLOW_LINE_15_IF_2
    value: routers.router_adaptive_flow_line_15_if_2
  - name: ASYA_HANDLER_ROUTER_ADAPTIVE_FLOW_LINE_16_FANOUT_1
    value: routers.router_adaptive_flow_line_16_fanout_1
