apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: deep-analyzer
  namespace: default
  labels:
    asya.sh/flow: adaptive-flow
spec:
  actor: deep-analyzer
  image: examples.asya.sh/deep-analyzer:latest
  handler: deep_analyzer
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
