apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-deep-analyzer.yaml
- asyncactor-fast-analyzer.yaml
- asyncactor-router-adaptive-flow-line-15-if-2.yaml
- asyncactor-router-adaptive-flow-line-16-fanout-1.yaml
- asyncactor-start-adaptive-flow.yaml
- configmap-routers.yaml
