apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-classifier.yaml
- asya-actor-deep-analyzer.yaml
- asya-actor-fast-analyzer.yaml
- asya-actor-formatter.yaml
- asya-actor-sequential-analyzer.yaml
- asya-router-adaptive-flow-fanout-results.yaml
- asya-router-adaptive-flow-if-parallel.yaml
- asya-start-adaptive-flow.yaml
- configmap-routers.yaml
