flowchart TD
    %% Flow: class_instantiation_flow

    router_class_instantiation_flow_line_18_seq_1{{router_class_instantiation_flow_line_18_seq_1}}
    start_class_instantiation_flow([start_class_instantiation_flow])
    __end__((( )))

    start_class_instantiation_flow --> router_class_instantiation_flow_line_18_seq_1
    router_class_instantiation_flow_line_18_seq_1 --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_class_instantiation_flow start
    class router_class_instantiation_flow_line_18_seq_1 router
    class __end__ endpoint