flowchart TD
    %% Flow: class_instantiation_flow

    sequential_with_class_DataPreprocessor_clean[DataPreprocessor.clean]
    sequential_with_class_MLModel_predict([MLModel.predict])
    start_class_instantiation_flow([start_class_instantiation_flow])
    transformation[transformation]

    start_class_instantiation_flow --> sequential_with_class_DataPreprocessor_clean
    sequential_with_class_DataPreprocessor_clean --> transformation
    transformation --> sequential_with_class_MLModel_predict