flowchart TD
    %% Flow: conditional_nested_flow

    end_conditional_nested_flow([end_conditional_nested_flow])
    handler_a[handler_a]
    handler_b[handler_b]
    handler_c[handler_c]
    handler_d[handler_d]
    handler_finalize[handler_finalize]
    handler_validate_input[handler_validate_input]
    router_conditional_nested_flow_line_10_seq_10{{router_conditional_nested_flow_line_10_seq_10}}
    router_conditional_nested_flow_line_12_if_9{{router_conditional_nested_flow_line_12_if_9}}
    router_conditional_nested_flow_line_15_if_6{{router_conditional_nested_flow_line_15_if_6}}
    router_conditional_nested_flow_line_16_seq_4{{router_conditional_nested_flow_line_16_seq_4}}
    router_conditional_nested_flow_line_18_seq_3{{router_conditional_nested_flow_line_18_seq_3}}
    router_conditional_nested_flow_line_20_seq_5{{router_conditional_nested_flow_line_20_seq_5}}
    router_conditional_nested_flow_line_23_seq_8{{router_conditional_nested_flow_line_23_seq_8}}
    router_conditional_nested_flow_line_25_seq_7{{router_conditional_nested_flow_line_25_seq_7}}
    router_conditional_nested_flow_line_27_seq_2{{router_conditional_nested_flow_line_27_seq_2}}
    router_conditional_nested_flow_line_29_seq_1{{router_conditional_nested_flow_line_29_seq_1}}
    router_conditional_nested_flow_line_9_if_11{{router_conditional_nested_flow_line_9_if_11}}
    start_conditional_nested_flow([start_conditional_nested_flow])

    start_conditional_nested_flow --> handler_validate_input
    start_conditional_nested_flow --> router_conditional_nested_flow_line_9_if_11
    router_conditional_nested_flow_line_27_seq_2 --> handler_finalize
    router_conditional_nested_flow_line_27_seq_2 --> router_conditional_nested_flow_line_29_seq_1
    router_conditional_nested_flow_line_16_seq_4 --> handler_b
    router_conditional_nested_flow_line_16_seq_4 --> router_conditional_nested_flow_line_18_seq_3
    router_conditional_nested_flow_line_20_seq_5 --> handler_c
    router_conditional_nested_flow_line_15_if_6 -->|p['x'] > 2| router_conditional_nested_flow_line_16_seq_4
    router_conditional_nested_flow_line_15_if_6 -->|not (p['x'] > 2)| router_conditional_nested_flow_line_20_seq_5
    router_conditional_nested_flow_line_23_seq_8 --> handler_d
    router_conditional_nested_flow_line_23_seq_8 --> router_conditional_nested_flow_line_25_seq_7
    router_conditional_nested_flow_line_12_if_9 -->|p['x'] > 2| handler_b
    router_conditional_nested_flow_line_12_if_9 -->|p['x'] > 2| router_conditional_nested_flow_line_15_if_6
    router_conditional_nested_flow_line_12_if_9 -->|not (p['x'] > 2)| router_conditional_nested_flow_line_23_seq_8
    router_conditional_nested_flow_line_10_seq_10 --> handler_a
    router_conditional_nested_flow_line_10_seq_10 --> router_conditional_nested_flow_line_12_if_9
    router_conditional_nested_flow_line_9_if_11 -->|p['a'] == 'A'| router_conditional_nested_flow_line_10_seq_10
    router_conditional_nested_flow_line_9_if_11 -->|p['a'] == 'A'| router_conditional_nested_flow_line_27_seq_2
    router_conditional_nested_flow_line_9_if_11 -->|not (p['a'] == 'A')| router_conditional_nested_flow_line_27_seq_2