# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: if_nested.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile if_nested.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

async def start_conditional_nested_flow(payload: dict):
    """Entrypoint for flow 'conditional_nested_flow'"""
    _next = []
    _next.append(resolve("handler_validate_input"))
    _next.append(resolve("router_conditional_nested_flow_line_9_if_11"))
    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_29_seq_1(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    p['x'] += 9
    p['x'] *= 10
    yield "SET", ".route.next", []
    yield p

async def router_conditional_nested_flow_line_27_seq_2(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] += 8
    _next.append(resolve("handler_finalize"))
    _next.append(resolve("router_conditional_nested_flow_line_29_seq_1"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_18_seq_3(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] += 4

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_16_seq_4(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] += 3
    _next.append(resolve("handler_b"))
    _next.append(resolve("router_conditional_nested_flow_line_18_seq_3"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_20_seq_5(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] += 5
    _next.append(resolve("handler_c"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_15_if_6(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] += 2
    if p['x'] > 2:
        _next.append(resolve("router_conditional_nested_flow_line_16_seq_4"))
    else:
        _next.append(resolve("router_conditional_nested_flow_line_20_seq_5"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_25_seq_7(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] += 7

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_23_seq_8(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] += 6
    _next.append(resolve("handler_d"))
    _next.append(resolve("router_conditional_nested_flow_line_25_seq_7"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_12_if_9(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['x'] > 2:
        _next.append(resolve("handler_b"))
        _next.append(resolve("router_conditional_nested_flow_line_15_if_6"))
    else:
        _next.append(resolve("router_conditional_nested_flow_line_23_seq_8"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_10_seq_10(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] += 1
    _next.append(resolve("handler_a"))
    _next.append(resolve("router_conditional_nested_flow_line_12_if_9"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_conditional_nested_flow_line_9_if_11(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['x'] = 1
    if p['a'] == 'A':
        _next.append(resolve("router_conditional_nested_flow_line_10_seq_10"))
        _next.append(resolve("router_conditional_nested_flow_line_27_seq_2"))
    else:
        _next.append(resolve("router_conditional_nested_flow_line_27_seq_2"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def end_conditional_nested_flow(payload: dict):
    """Exitpoint for flow 'conditional_nested_flow'"""
    yield "SET", ".route.next", []
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
