# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../if_nested.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../if_nested.py
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_conditional_nested_flow(envelope: dict) -> dict:
    """Entrypoint for flow 'conditional_nested_flow'"""
    r = envelope['route']
    c = r['current']

    r['actors'][c+1:c+1] = [resolve("handler_validate_input"), resolve("router_conditional_nested_flow_line_6_if")]
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_15_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 4
    _next.append(resolve("router_conditional_nested_flow_line_24_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_13_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 3
    _next.append(resolve("handler_b"))
    _next.append(resolve("router_conditional_nested_flow_line_15_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_17_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 5
    _next.append(resolve("handler_c"))
    _next.append(resolve("router_conditional_nested_flow_line_24_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_12_if(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 2
    if p['x'] > 2:
        _next.append(resolve("router_conditional_nested_flow_line_13_seq"))
    else:
        _next.append(resolve("router_conditional_nested_flow_line_17_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_22_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 7
    _next.append(resolve("router_conditional_nested_flow_line_24_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_20_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 6
    _next.append(resolve("handler_d"))
    _next.append(resolve("router_conditional_nested_flow_line_22_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_9_if(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    if p['x'] > 2:
        _next.append(resolve("handler_b"))
        _next.append(resolve("router_conditional_nested_flow_line_12_if"))
    else:
        _next.append(resolve("router_conditional_nested_flow_line_20_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_7_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 1
    _next.append(resolve("handler_a"))
    _next.append(resolve("router_conditional_nested_flow_line_9_if"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_26_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 9
    p['x'] *= 10

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_24_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] += 8
    _next.append(resolve("handler_finalize"))
    _next.append(resolve("router_conditional_nested_flow_line_26_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def router_conditional_nested_flow_line_6_if(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['x'] = 1
    if p['a'] == 'A':
        _next.append(resolve("router_conditional_nested_flow_line_7_seq"))
    else:
        _next.append(resolve("router_conditional_nested_flow_line_24_seq"))

    r['actors'][c+1:c+1] = _next
    r['current'] = c + 1
    return envelope

def end_conditional_nested_flow(envelope: dict) -> dict:
    """Exitpoint for flow 'conditional_nested_flow'"""
    return envelope


# ======================================================================
# Handler Resolution
# ======================================================================

def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    import os, logging

    if not hasattr(resolve, "_handler_to_actor"):
        resolve._handler_to_actor = {}
        resolve._suffix_to_handlers = {}

        for env_var, handler_name in os.environ.items():
            if env_var.startswith('ASYA_HANDLER_'):
                actor_name = env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
                resolve._handler_to_actor[handler_name] = actor_name

                # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
                parts = handler_name.split('.')
                for i in range(len(parts)):
                    suffix = '.'.join(parts[i:])
                    if suffix not in resolve._suffix_to_handlers:
                        resolve._suffix_to_handlers[suffix] = []
                    resolve._suffix_to_handlers[suffix].append(handler_name)

        logging.info(f"Loaded {len(resolve._handler_to_actor)} handler-to-actor mappings")

    # Try suffix-based resolution (exact match or any valid suffix)
    if handler_full_name in resolve._suffix_to_handlers:
        candidates = resolve._suffix_to_handlers[handler_full_name]
        if len(candidates) == 1:
            return resolve._handler_to_actor[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(resolve._handler_to_actor.keys())}"
    )
