apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-notify-rejection
  namespace: default
  labels:
    asya.sh/flow: order-processing
    asya.sh/role: end
spec:
  actor: actor-notify-rejection
  image: examples.asya.sh/notify-rejection:latest
  handler: notify_rejection
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
