apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-generic-processor
  namespace: default
  labels:
    asya.sh/flow: content-pipeline-flow
spec:
  actor: actor-generic-processor
  image: examples.asya.sh/generic-processor:latest
  handler: generic_processor
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
