apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-router-content-pipeline-flow-if-content-type-eq-image.yaml
- asya-router-content-pipeline-flow-if-content-type-eq-text.yaml
- asya-start-content-pipeline-flow.yaml
- configmap-routers.yaml
