apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-type-b
  namespace: default
  labels:
    asya.sh/flow: if-elif-else-flow
spec:
  actor: actor-handler-type-b
  image: examples.asya.sh/handler-type-b:latest
  handler: if_elif_else.handler_type_b
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
