apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-if-elif-else-flow-if-type-eq-a
  namespace: default
  labels:
    asya.sh/flow: if-elif-else-flow
    asya.sh/generated: 'true'
spec:
  actor: router-if-elif-else-flow-if-type-eq-a
  image: python:3.13-slim
  handler: routers.router_if_elif_else_flow_if_type_eq_a
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_DEFAULT
    value: handler_default
  - name: ASYA_HANDLER_ACTOR_HANDLER_FINALIZE
    value: handler_finalize
  - name: ASYA_HANDLER_ACTOR_HANDLER_TYPE_A
    value: handler_type_a
  - name: ASYA_HANDLER_ACTOR_HANDLER_TYPE_B
    value: handler_type_b
  - name: ASYA_HANDLER_ACTOR_HANDLER_VALIDATE
    value: handler_validate
  - name: ASYA_HANDLER_ROUTER_IF_ELIF_ELSE_FLOW_IF_TYPE_EQ_A
    value: routers.router_if_elif_else_flow_if_type_eq_a
  - name: ASYA_HANDLER_ROUTER_IF_ELIF_ELSE_FLOW_IF_TYPE_EQ_B
    value: routers.router_if_elif_else_flow_if_type_eq_b
