apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-router-if-elif-else-flow-line-13-if-2.yaml
- asya-router-if-elif-else-flow-line-15-if-1.yaml
- asya-start-if-elif-else-flow.yaml
- configmap-routers.yaml
