apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handler-default.yaml
- asya-actor-handler-finalize.yaml
- asya-actor-handler-type-a.yaml
- asya-actor-handler-type-b.yaml
- asya-actor-handler-validate.yaml
- asya-router-if-elif-else-flow-if-type-eq-a.yaml
- asya-router-if-elif-else-flow-if-type-eq-b.yaml
- asya-start-if-elif-else-flow.yaml
- configmap-routers.yaml
