flowchart TD
    %% Flow: if_inside_while_flow

    end_if_inside_while_flow([end_if_inside_while_flow])
    handler_finalize[handler_finalize]
    router_if_inside_while_flow_line_14_while_1{{router_if_inside_while_flow_line_14_while_1}}

    router_if_inside_while_flow_line_14_while_1 -->|p['i'] < p['max_iterations']| handler_finalize