flowchart TD
    %% Flow: if_inside_while_flow

    handler_even[handler_even]
    handler_finalize[handler_finalize]
    handler_init[handler_init]
    handler_odd[handler_odd]
    router_if_inside_while_flow_line_13_seq_3{{"router_if_inside_while_flow_line_13_seq_3<br/><br/>p['i'] = 0"}}
    router_if_inside_while_flow_line_14_while_1{{router_if_inside_while_flow_line_14_while_1}}
    router_if_inside_while_flow_line_16_if_2{{"router_if_inside_while_flow_line_16_if_2<br/><br/>p['i'] += 1"}}
    start_if_inside_while_flow([start_if_inside_while_flow])
    __end__((( )))

    start_if_inside_while_flow --> handler_init
    handler_init --> router_if_inside_while_flow_line_13_seq_3
    router_if_inside_while_flow_line_16_if_2 -->|"p['i'] % 2 == 0"| handler_even
    router_if_inside_while_flow_line_16_if_2 -->|"else"| handler_odd
    router_if_inside_while_flow_line_14_while_1 -->|"p['i'] < p['max_iterations']"| router_if_inside_while_flow_line_16_if_2
    router_if_inside_while_flow_line_14_while_1 -->|"else"| handler_finalize
    router_if_inside_while_flow_line_13_seq_3 --> router_if_inside_while_flow_line_14_while_1
    handler_even --> router_if_inside_while_flow_line_14_while_1
    handler_odd --> router_if_inside_while_flow_line_14_while_1
    handler_finalize --> __end__

    classDef entrypoint fill:#98FB98,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_if_inside_while_flow entrypoint
    class router_if_inside_while_flow_line_13_seq_3,router_if_inside_while_flow_line_14_while_1,router_if_inside_while_flow_line_16_if_2 router
    class handler_even,handler_finalize,handler_init,handler_odd handler
    class __end__ endpoint
    linkStyle 2,4 stroke:#2E8B57
    linkStyle 3,5 stroke:#E07040