apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-review-pipeline-flow-if-score-lt-0.5
  namespace: default
  labels:
    asya.sh/flow: review-pipeline-flow
    asya.sh/generated: 'true'
spec:
  actor: router-review-pipeline-flow-if-score-lt-0.5
  image: python:3.13-slim
  handler: routers.router_review_pipeline_flow_if_score_lt_0.5
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ROUTER_REVIEW_PIPELINE_FLOW_IF_SCORE_LT_0.5
    value: routers.router_review_pipeline_flow_if_score_lt_0.5
  volumes:
  - name: routers
    configMap:
      name: review-pipeline-flow-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
