apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-detailed-review
  namespace: default
  labels:
    asya.sh/flow: review-pipeline-flow
spec:
  actor: actor-detailed-review
  image: examples.asya.sh/detailed-review:latest
  handler: detailed_review
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
