
"""
Auto-generated by asya flow compiler
Source: examples/scenes/nested_loop_scene.py
Generated: 2025-12-11 14:30:21

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile examples/scenes/nested_loop_scene.py
"""


# ======================================================================
# Required Environment Variables for Router Deployment
# ======================================================================
"""
Set these environment variables when deploying router actors:

ASYA_HANDLER_END_NESTED_LOOP_SCENE="end_nested_loop_scene"
ASYA_HANDLER_FINALIZE_LOOP_I="finalize_loop_i"
ASYA_HANDLER_INITIALIZE="initialize"
ASYA_HANDLER_PROCESS_ITEM="process_item"
ASYA_HANDLER_ROUTER_NESTED_LOOP_SCENE_LINE_11_SEQ="router_nested_loop_scene_line_11_seq"
ASYA_HANDLER_ROUTER_NESTED_LOOP_SCENE_LINE_12_IF="router_nested_loop_scene_line_12_if"
ASYA_HANDLER_ROUTER_NESTED_LOOP_SCENE_LINE_15_IF="router_nested_loop_scene_line_15_if"
ASYA_HANDLER_START_NESTED_LOOP_SCENE="start_nested_loop_scene"

Example for Kubernetes:
  env:
    - name: ASYA_HANDLER_END_NESTED_LOOP_SCENE
      value: "end_nested_loop_scene"
    - name: ASYA_HANDLER_FINALIZE_LOOP_I
      value: "finalize_loop_i"
    - name: ASYA_HANDLER_INITIALIZE
      value: "initialize"
    - name: ASYA_HANDLER_PROCESS_ITEM
      value: "process_item"
    - name: ASYA_HANDLER_ROUTER_NESTED_LOOP_SCENE_LINE_11_SEQ
      value: "router_nested_loop_scene_line_11_seq"
    - name: ASYA_HANDLER_ROUTER_NESTED_LOOP_SCENE_LINE_12_IF
      value: "router_nested_loop_scene_line_12_if"
    - name: ASYA_HANDLER_ROUTER_NESTED_LOOP_SCENE_LINE_15_IF
      value: "router_nested_loop_scene_line_15_if"
    - name: ASYA_HANDLER_START_NESTED_LOOP_SCENE
      value: "start_nested_loop_scene"
"""


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

def start_nested_loop_scene(envelope: dict) -> dict:
    """Entrypoint for scene 'nested_loop_scene'"""
    r = envelope['route']
    c = r['current']

    r['actors'][c+1:c+1] = [resolve("initialize"), resolve("router_nested_loop_scene_line_11_seq"), resolve("end_nested_loop_scene")]

    return envelope

def end_nested_loop_scene(envelope: dict) -> dict:
    """Exitpoint for scene 'nested_loop_scene'"""
    return envelope

def router_nested_loop_scene_line_11_seq(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    p['i'] = 0
    _next.append(resolve("router_nested_loop_scene_line_12_if"))

    r['actors'][c+1:c+1] = _next
    return envelope

def router_nested_loop_scene_line_12_if(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    if p['i'] < p['max_i']:
        p['i'] = p['i'] + 1
        p['j'] = 0
        _next.append(resolve("router_nested_loop_scene_line_15_if"))
    else:
        _next.append(resolve("finalize_loop_i"))

    r['actors'][c+1:c+1] = _next
    return envelope

def router_nested_loop_scene_line_15_if(envelope: dict) -> dict:
    """Router for control flow and payload mutations"""
    p = envelope['payload']
    r = envelope['route']
    c = r['current']
    _next = []

    if p['j'] < p['max_j']:
        p['j'] = p['j'] + 1
        _next.append(resolve("process_item"))
        _next.append(resolve("router_nested_loop_scene_line_15_if"))
    else:
        _next.append(resolve("finalize_loop_i"))

    r['actors'][c+1:c+1] = _next
    return envelope

# ======================================================================
# Handler Resolution
# ======================================================================


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler full name to actor name for routing.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="module.handler" or "module.Class.method"

    The reverse mapping (handler -> actor) is built once at first call and cached.

    Args:
        handler_full_name: Full qualified name like "module.handler" or "module.Class.method"

    Returns:
        Actor name for routing (kebab-case)

    Raises:
        ValueError: If handler not found in environment variables

    Examples:
        # Environment: ASYA_HANDLER_IMAGE_PROCESSOR="my_module.ImageProcessor.process"
        resolve("my_module.ImageProcessor.process")  # returns "image-processor"

        # Environment: ASYA_HANDLER_TEXT_ANALYZER="text.analyze"
        resolve("text.analyze")  # returns "text-analyzer"
    """
    import os, logging

    # Build reverse mapping: {handler_full_name: actor_name}
    if not hasattr(resolve, '_handler_to_actor'):
        resolve._handler_to_actor = {}
        for env_var, handler_name in os.environ.items():
            if env_var.startswith('ASYA_HANDLER_'):
                # Extract actor name: ASYA_HANDLER_IMAGE_PROCESSOR -> image-processor
                actor_name = env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
                resolve._handler_to_actor[handler_name] = actor_name
        logging.info(f"Loaded {len(resolve._handler_to_actor)} handler-to-actor values from env vars")

    if handler_full_name not in resolve._handler_to_actor:
        raise ValueError(
            f"Handler '{handler_full_name}' not found in environment variables. "
            f'Expected ASYA_HANDLER_<ACTOR_NAME>="{handler_full_name}" to be set. '
            f"See loaded handlers mapping: {resolve._handler_to_actor}"
        )

    return resolve._handler_to_actor[handler_full_name]

