apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-text-improver
  namespace: asya-demo
  labels:
    asya.sh/flow: text-improver
    asya.sh/flow-role: entrypoint
spec:
  compositionSelector:
    matchLabels:
      asya.sh/transport: pubsub
  actor: start-text-improver
  image: python:3.13-slim
  handler: routers.start_text_improver
  transport: pubsub
  env:
  - name: PYTHONPATH
    value: /app
  - name: ASYA_HANDLER_ROUTER_TEXT_IMPROVER_LINE_20_LOOP_BACK_0
    value: routers.router_text_improver_line_20_loop_back_0
  volumes:
  - name: handler
    configMap:
      name: text-improver-routers
  volumeMounts:
  - name: handler
    mountPath: /app
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
