apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-text-improver-line-29-if
  namespace: asya-demo
  labels:
    asya.sh/flow: text-improver
    asya.sh/flow-role: router
spec:
  actor: router-text-improver-line-29-if
  image: python:3.13-slim
  handler: routers.router_text_improver_line_29_if
  env:
  - name: PYTHONPATH
    value: /app
  - name: ASYA_HANDLER_POLISHER
    value: demo_actors.polisher.polisher
  - name: ASYA_HANDLER_END_TEXT_IMPROVER
    value: routers.end_text_improver
  volumes:
  - name: handler
    configMap:
      name: text-improver-routers
  volumeMounts:
  - name: handler
    mountPath: /app
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
