apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: polisher
  namespace: asya-demo
  labels:
    asya.sh/flow: text-improver
    asya.sh/flow-role: handler
spec:
  compositionSelector:
    matchLabels:
      asya.sh/transport: sqs
  actor: polisher
  image: asya-demo:latest
  handler: demo_actors.polisher.polisher
  transport: sqs
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
