apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-end-text-improver.yaml
- asya-evaluator.yaml
- asya-generator.yaml
- asya-polisher.yaml
- asya-router-text-improver-line-20-loop-back-0.yaml
- asya-router-text-improver-line-21-seq.yaml
- asya-router-text-improver-line-26-if.yaml
- asya-router-text-improver-line-29-if.yaml
- asya-start-text-improver.yaml
- configmap-routers.yaml
