flowchart TD
    %% Flow: complex_flow

    end_complex_flow([end_complex_flow])
    handler_error[handler_error]
    router_complex_flow_line_15_if_6{{router_complex_flow_line_15_if_6}}
    router_complex_flow_line_22_while_1{{router_complex_flow_line_22_while_1}}
    router_complex_flow_line_29_if_2{{router_complex_flow_line_29_if_2}}

    router_complex_flow_line_15_if_6 -->|not p['valid']| handler_error