templates:
  namespace: demo-tilt
  router_image: "python:3.13-slim"
  max_replicas: 5

build:
- module: "analyze"
  image: "tilt-sentiment-actors"
- module: "summarize"
  image: "tilt-summarizer"
- module: "translate"
  image: "tilt-translator"

compiler:
  routers: "./compiled"
  manifests: ".asya/manifests"
  templates: ".asya/templates"
