apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-rag-pipeline
  namespace: default
  labels:
    asya.sh/flow: rag-pipeline
    asya.sh/role: start
    asya.sh/generated: 'true'
spec:
  actor: start-rag-pipeline
  image: python:3.13-slim
  handler: routers.start_rag_pipeline
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_FACT_CHECKER
    value: rag_pipeline.fact_checker
  - name: ASYA_HANDLER_ACTOR_GENERATOR
    value: rag_pipeline.generator
  - name: ASYA_HANDLER_ACTOR_QUERY_ANALYZER
    value: rag_pipeline.query_analyzer
  - name: ASYA_HANDLER_ACTOR_QUERY_REFINER
    value: rag_pipeline.query_refiner
  - name: ASYA_HANDLER_ACTOR_RELEVANCE_EVALUATOR
    value: rag_pipeline.relevance_evaluator
  - name: ASYA_HANDLER_ACTOR_RETRIEVER
    value: rag_pipeline.retriever
  - name: ASYA_HANDLER_ROUTER_RAG_PIPELINE_IF_IS_SUFFICIENT
    value: routers.router_rag_pipeline_if_is_sufficient
  - name: ASYA_HANDLER_ROUTER_RAG_PIPELINE_IF_RETRIEVAL_ATTEMPTS_GE_3
    value: routers.router_rag_pipeline_if_retrieval_attempts_ge_3
  - name: ASYA_HANDLER_ROUTER_RAG_PIPELINE_SEQ_SET_RETRIEVAL_ATTEMPTS
    value: routers.router_rag_pipeline_seq_set_retrieval_attempts
  - name: ASYA_HANDLER_ROUTER_RAG_PIPELINE_WHILE_LOOP
    value: routers.router_rag_pipeline_while_loop
  volumes:
  - name: routers
    configMap:
      name: rag-pipeline-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
