apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-retriever
  namespace: default
  labels:
    asya.sh/flow: rag-pipeline
spec:
  actor: actor-retriever
  image: examples.asya.sh/retriever:latest
  handler: retriever
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
