apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-fact-checker.yaml
- asya-actor-generator.yaml
- asya-actor-query-analyzer.yaml
- asya-actor-query-refiner.yaml
- asya-actor-relevance-evaluator.yaml
- asya-actor-retriever.yaml
- asya-router-rag-pipeline-line-49-seq-5.yaml
- asya-router-rag-pipeline-line-55-while-1.yaml
- asya-router-rag-pipeline-line-56-seq-4.yaml
- asya-router-rag-pipeline-line-65-if-3.yaml
- asya-router-rag-pipeline-line-69-if-2.yaml
- asya-start-rag-pipeline.yaml
- configmap-routers.yaml
