apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-formatter
  namespace: default
  labels:
    asya.sh/flow: typed-dataclass-pipeline
    asya.sh/role: end
spec:
  actor: actor-formatter
  image: examples.asya.sh/formatter:latest
  handler: typed_dataclass_pipeline.formatter
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
