apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: extractor
  namespace: default
  labels:
    asya.sh/flow: typed-dataclass-pipeline
spec:
  actor: extractor
  image: examples.asya.sh/extractor:latest
  handler: extractor
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
