apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: enricher
  namespace: default
  labels:
    asya.sh/flow: typed-dataclass-pipeline
spec:
  actor: enricher
  image: examples.asya.sh/enricher:latest
  handler: enricher
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
