apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-classifier.yaml
- asyncactor-enricher.yaml
- asyncactor-extractor.yaml
- asyncactor-formatter.yaml
- asyncactor-start-typed-dataclass-pipeline.yaml
- configmap-routers.yaml
