apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-order-processing-line-8-except-2
  namespace: default
  labels:
    asya.sh/flow: order-processing
    asya.sh/generated: 'true'
spec:
  actor: router-order-processing-line-8-except-2
  image: python:3.13-slim
  handler: routers.router_order_processing_line_8_except_2
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_NOTIFY_REJECTION
    value: notify_rejection
  - name: ASYA_HANDLER_ROUTER_ORDER_PROCESSING_LINE_9_SEQ_1
    value: routers.router_order_processing_line_9_seq_1
  - name: ASYA_HANDLER_VALIDATE_ORDER
    value: validate_order
