apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-react-agent-line-15-if-2
  namespace: default
  labels:
    asya.sh/flow: react-agent
    asya.sh/generated: 'true'
spec:
  actor: router-react-agent-line-15-if-2
  image: python:3.13-slim
  handler: routers.router_react_agent_line_15_if_2
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_EXECUTE_TOOL
    value: execute_tool
  - name: ASYA_HANDLER_ACTOR_LLM_CALL
    value: llm_call
  - name: ASYA_HANDLER_ROUTER_REACT_AGENT_LINE_13_WHILE_1
    value: routers.router_react_agent_line_13_while_1
  - name: ASYA_HANDLER_ROUTER_REACT_AGENT_LINE_15_IF_2
    value: routers.router_react_agent_line_15_if_2
