apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-execute-tool.yaml
- asya-actor-llm-call.yaml
- asya-router-react-agent-if-tool-calls.yaml
- asya-router-react-agent-while-loop.yaml
- asya-start-react-agent.yaml
- configmap-routers.yaml
