apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-complex-flow-if-not-valid
  namespace: default
  labels:
    asya.sh/flow: complex-flow
    asya.sh/generated: 'true'
spec:
  actor: router-complex-flow-if-not-valid
  image: python:3.13-slim
  handler: routers.router_complex_flow_if_not_valid
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_CHECK_QUALITY
    value: complex_with_while.handler_check_quality
  - name: ASYA_HANDLER_ACTOR_HANDLER_ENRICH_DATA
    value: complex_with_while.handler_enrich_data
  - name: ASYA_HANDLER_ACTOR_HANDLER_ERROR
    value: complex_with_while.handler_error
  - name: ASYA_HANDLER_ACTOR_HANDLER_FINALIZE
    value: complex_with_while.handler_finalize
  - name: ASYA_HANDLER_ACTOR_HANDLER_PREPROCESS
    value: complex_with_while.handler_preprocess
  - name: ASYA_HANDLER_ACTOR_HANDLER_RETRY_HANDLER
    value: complex_with_while.handler_retry_handler
  - name: ASYA_HANDLER_ACTOR_HANDLER_TRANSFORM_BATCH
    value: complex_with_while.handler_transform_batch
  - name: ASYA_HANDLER_ACTOR_HANDLER_VALIDATE
    value: complex_with_while.handler_validate
  - name: ASYA_HANDLER_ROUTER_COMPLEX_FLOW_IF_NEEDS_ENRICHMENT
    value: routers.router_complex_flow_if_needs_enrichment
  - name: ASYA_HANDLER_ROUTER_COMPLEX_FLOW_IF_NOT_VALID
    value: routers.router_complex_flow_if_not_valid
  - name: ASYA_HANDLER_ROUTER_COMPLEX_FLOW_IF_QUALITY_SCORE_GE_50
    value: routers.router_complex_flow_if_quality_score_ge_50
  - name: ASYA_HANDLER_ROUTER_COMPLEX_FLOW_IF_QUALITY_SCORE_LT_20
    value: routers.router_complex_flow_if_quality_score_lt_20
  - name: ASYA_HANDLER_ROUTER_COMPLEX_FLOW_IF_REQUIRES_RETRY
    value: routers.router_complex_flow_if_requires_retry
  - name: ASYA_HANDLER_ROUTER_COMPLEX_FLOW_WHILE_BATCH_COUNT_LT_MAX_BATCHES
    value: routers.router_complex_flow_while_batch_count_lt_max_batches
  volumes:
  - name: routers
    configMap:
      name: complex-flow-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
