apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-check-quality
  namespace: default
  labels:
    asya.sh/flow: complex-flow
spec:
  actor: actor-handler-check-quality
  image: examples.asya.sh/handler-check-quality:latest
  handler: complex_with_while.handler_check_quality
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
