apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-enrich-data
  namespace: default
  labels:
    asya.sh/flow: complex-flow
spec:
  actor: actor-handler-enrich-data
  image: examples.asya.sh/handler-enrich-data:latest
  handler: handler_enrich_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
