apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-transform-batch
  namespace: default
  labels:
    asya.sh/flow: complex-flow
spec:
  actor: actor-handler-transform-batch
  image: examples.asya.sh/handler-transform-batch:latest
  handler: handler_transform_batch
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
