apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-handler-retry-handler
  namespace: default
  labels:
    asya.sh/flow: complex-flow
spec:
  actor: actor-handler-retry-handler
  image: examples.asya.sh/handler-retry-handler:latest
  handler: complex_with_while.handler_retry_handler
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
