apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-router-complex-flow-line-15-if-14.yaml
- asyncactor-router-complex-flow-line-19-if-12.yaml
- asyncactor-router-complex-flow-line-22-while-2.yaml
- asyncactor-router-complex-flow-line-26-if-4.yaml
- asyncactor-router-complex-flow-line-29-if-3.yaml
- asyncactor-router-complex-flow-line-32-if-11.yaml
- asyncactor-router-complex-flow-line-53-seq-7.yaml
- asyncactor-router-complex-flow-line-59-if-6.yaml
- asyncactor-router-complex-flow-line-60-seq-5.yaml
- asyncactor-router-complex-flow-line-75-if-10.yaml
- asyncactor-router-complex-flow-line-76-seq-9.yaml
- asyncactor-router-complex-flow-line-77-seq-8.yaml
- asyncactor-router-complex-flow-line-83-seq-13.yaml
- asyncactor-router-complex-flow-line-89-seq-1.yaml
- asyncactor-start-complex-flow.yaml
- configmap-routers.yaml
