flowchart TD
    %% Flow: voting_ensemble

    analytical_writer[analytical_writer]
    concise_writer[concise_writer]
    creative_writer[creative_writer]
    fanin_voting_ensemble_line_44[fanin_voting_ensemble_line_44]
    judge([judge])
    router_voting_ensemble_line_44_fanout_1{{router_voting_ensemble_line_44_fanout_1}}
    start_voting_ensemble([start_voting_ensemble])

    start_voting_ensemble --> router_voting_ensemble_line_44_fanout_1
    router_voting_ensemble_line_44_fanout_1 -->|fanout| fanin_voting_ensemble_line_44
    fanin_voting_ensemble_line_44 --> judge
    router_voting_ensemble_line_44_fanout_1 --> creative_writer
    creative_writer --> fanin_voting_ensemble_line_44
    router_voting_ensemble_line_44_fanout_1 --> analytical_writer
    analytical_writer --> fanin_voting_ensemble_line_44
    router_voting_ensemble_line_44_fanout_1 --> concise_writer
    concise_writer --> fanin_voting_ensemble_line_44