flowchart TD
    %% Flow: voting_ensemble

    analytical_writer[analytical_writer]
    concise_writer[concise_writer]
    creative_writer[creative_writer]
    fanin_voting_ensemble_candidates[fanin_voting_ensemble_candidates]
    judge[judge]
    router_voting_ensemble_fanout_candidates{{router_voting_ensemble_fanout_candidates}}
    start_voting_ensemble([start_voting_ensemble])
    __end__((( )))

    start_voting_ensemble --> router_voting_ensemble_fanout_candidates
    router_voting_ensemble_fanout_candidates -->|"fanout"| fanin_voting_ensemble_candidates
    fanin_voting_ensemble_candidates --> judge
    router_voting_ensemble_fanout_candidates --> creative_writer
    creative_writer --> fanin_voting_ensemble_candidates
    router_voting_ensemble_fanout_candidates --> analytical_writer
    analytical_writer --> fanin_voting_ensemble_candidates
    router_voting_ensemble_fanout_candidates --> concise_writer
    concise_writer --> fanin_voting_ensemble_candidates
    judge --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_voting_ensemble start
    class judge endnode
    class router_voting_ensemble_fanout_candidates router
    class analytical_writer,concise_writer,creative_writer,fanin_voting_ensemble_candidates handler
    class __end__ endpoint
    linkStyle 1 stroke:#7B68EE