apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-check-threshold
  namespace: default
  labels:
    asya.sh/flow: loop-flow
spec:
  actor: actor-check-threshold
  image: examples.asya.sh/check-threshold:latest
  handler: check_threshold
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
