apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-check-threshold.yaml
- asya-actor-finalize-loop.yaml
- asya-actor-initialize.yaml
- asya-actor-process-abort.yaml
- asya-actor-process-item.yaml
- asya-router-loop-flow-if-skip-threshold-check.yaml
- asya-router-loop-flow-if-threshold-met.yaml
- asya-router-loop-flow-seq-set-abort-2.yaml
- asya-router-loop-flow-seq-set-abort.yaml
- asya-router-loop-flow-seq-set-iteration-2.yaml
- asya-router-loop-flow-seq-set-iteration.yaml
- asya-router-loop-flow-while-iteration-lt-max-iterations.yaml
- asya-start-loop-flow.yaml
- configmap-routers.yaml
