apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-check-threshold.yaml
- asya-actor-finalize-loop.yaml
- asya-actor-initialize.yaml
- asya-actor-process-abort.yaml
- asya-actor-process-item.yaml
- asya-router-loop-flow-line-14-seq-7.yaml
- asya-router-loop-flow-line-15-while-1.yaml
- asya-router-loop-flow-line-16-seq-6.yaml
- asya-router-loop-flow-line-19-if-5.yaml
- asya-router-loop-flow-line-20-seq-4.yaml
- asya-router-loop-flow-line-22-seq-3.yaml
- asya-router-loop-flow-line-26-if-2.yaml
- asya-start-loop-flow.yaml
- configmap-routers.yaml
