apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: technical-agent
  namespace: default
  labels:
    asya.sh/flow: routing-classifier
spec:
  actor: technical-agent
  image: examples.asya.sh/technical-agent:latest
  handler: technical_agent
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
