apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-account-agent.yaml
- asyncactor-billing-agent.yaml
- asyncactor-classifier.yaml
- asyncactor-format-reply.yaml
- asyncactor-general-agent.yaml
- asyncactor-router-routing-classifier-line-46-if-3.yaml
- asyncactor-router-routing-classifier-line-48-if-2.yaml
- asyncactor-router-routing-classifier-line-50-if-1.yaml
- asyncactor-start-routing-classifier.yaml
- asyncactor-technical-agent.yaml
- configmap-routers.yaml
