apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-account-agent.yaml
- asya-actor-billing-agent.yaml
- asya-actor-classifier.yaml
- asya-actor-format-reply.yaml
- asya-actor-general-agent.yaml
- asya-actor-technical-agent.yaml
- asya-router-routing-classifier-line-46-if-3.yaml
- asya-router-routing-classifier-line-48-if-2.yaml
- asya-router-routing-classifier-line-50-if-1.yaml
- asya-start-routing-classifier.yaml
- configmap-routers.yaml
