apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-account-agent.yaml
- asya-actor-billing-agent.yaml
- asya-actor-classifier.yaml
- asya-actor-format-reply.yaml
- asya-actor-general-agent.yaml
- asya-actor-technical-agent.yaml
- asya-router-routing-classifier-if-category-eq-account.yaml
- asya-router-routing-classifier-if-category-eq-billing.yaml
- asya-router-routing-classifier-if-category-eq-technical.yaml
- asya-start-routing-classifier.yaml
- configmap-routers.yaml
