apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: team-a
build:
  artifacts:
  - image: skaffold-sentiment-actors
    context: ..
    docker:
      dockerfile: team-a/actors/sentiment/Dockerfile
  - image: skaffold-summarizer
    context: actors/summarizer
    docker:
      dockerfile: Dockerfile
