apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: start-if-empty-branches-flow
  namespace: default
  labels:
    asya.sh/flow: if-empty-branches-flow
    asya.sh/role: start
    asya.sh/generated: 'true'
spec:
  actor: start-if-empty-branches-flow
  image: python:3.13-slim
  handler: routers.start_if_empty_branches_flow
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLER_FINALIZE
    value: handler_finalize
  - name: ASYA_HANDLER_ACTOR_HANDLER_SETUP
    value: handler_setup
  - name: ASYA_HANDLER_ROUTER_IF_EMPTY_BRANCHES_FLOW_LINE_13_IF_1
    value: routers.router_if_empty_branches_flow_line_13_if_1
