apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-hierarchical-delegation-if-subtask-eq-api
  namespace: default
  labels:
    asya.sh/flow: hierarchical-delegation
    asya.sh/generated: 'true'
spec:
  actor: router-hierarchical-delegation-if-subtask-eq-api
  image: python:3.13-slim
  handler: routers.router_hierarchical_delegation_if_subtask_eq_api
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_API_SPECIALIST
    value: hierarchical_delegation.api_specialist
  - name: ASYA_HANDLER_ACTOR_CONTENT_GENERALIST
    value: hierarchical_delegation.content_generalist
  - name: ASYA_HANDLER_ACTOR_CONTENT_TEAM_LEAD
    value: hierarchical_delegation.content_team_lead
  - name: ASYA_HANDLER_ACTOR_DATA_GENERALIST
    value: hierarchical_delegation.data_generalist
  - name: ASYA_HANDLER_ACTOR_DATA_TEAM_LEAD
    value: hierarchical_delegation.data_team_lead
  - name: ASYA_HANDLER_ACTOR_EDITOR
    value: hierarchical_delegation.editor
  - name: ASYA_HANDLER_ACTOR_FINAL_ASSEMBLER
    value: hierarchical_delegation.final_assembler
  - name: ASYA_HANDLER_ACTOR_GENERALIST
    value: hierarchical_delegation.generalist
  - name: ASYA_HANDLER_ACTOR_ROOT_AGENT
    value: hierarchical_delegation.root_agent
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_DOMAIN_EQ_CONTENT
    value: routers.router_hierarchical_delegation_if_domain_eq_content
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_DOMAIN_EQ_DATA
    value: routers.router_hierarchical_delegation_if_domain_eq_data
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_SUBTASK_EQ_API
    value: routers.router_hierarchical_delegation_if_subtask_eq_api
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_SUBTASK_EQ_EDIT
    value: routers.router_hierarchical_delegation_if_subtask_eq_edit
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_SUBTASK_EQ_SQL
    value: routers.router_hierarchical_delegation_if_subtask_eq_sql
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_SUBTASK_EQ_WRITE
    value: routers.router_hierarchical_delegation_if_subtask_eq_write
  - name: ASYA_HANDLER_ACTOR_SQL_SPECIALIST
    value: hierarchical_delegation.sql_specialist
  - name: ASYA_HANDLER_ACTOR_WRITER
    value: hierarchical_delegation.writer
  volumes:
  - name: routers
    configMap:
      name: hierarchical-delegation-routers
  volumeMounts:
  - name: routers
    mountPath: /opt/asya/routers.py
    subPath: routers.py
    readOnly: true
