apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-hierarchical-delegation-if-domain-eq-data
  namespace: default
  labels:
    asya.sh/flow: hierarchical-delegation
    asya.sh/generated: 'true'
spec:
  actor: router-hierarchical-delegation-if-domain-eq-data
  image: python:3.13-slim
  handler: routers.router_hierarchical_delegation_if_domain_eq_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_API_SPECIALIST
    value: api_specialist
  - name: ASYA_HANDLER_ACTOR_CONTENT_GENERALIST
    value: content_generalist
  - name: ASYA_HANDLER_ACTOR_CONTENT_TEAM_LEAD
    value: content_team_lead
  - name: ASYA_HANDLER_ACTOR_DATA_GENERALIST
    value: data_generalist
  - name: ASYA_HANDLER_ACTOR_DATA_TEAM_LEAD
    value: data_team_lead
  - name: ASYA_HANDLER_ACTOR_EDITOR
    value: editor
  - name: ASYA_HANDLER_ACTOR_FINAL_ASSEMBLER
    value: final_assembler
  - name: ASYA_HANDLER_ACTOR_GENERALIST
    value: generalist
  - name: ASYA_HANDLER_ACTOR_ROOT_AGENT
    value: root_agent
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_DOMAIN_EQ_CONTENT
    value: routers.router_hierarchical_delegation_if_domain_eq_content
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_DOMAIN_EQ_DATA
    value: routers.router_hierarchical_delegation_if_domain_eq_data
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_SUBTASK_EQ_API
    value: routers.router_hierarchical_delegation_if_subtask_eq_api
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_SUBTASK_EQ_EDIT
    value: routers.router_hierarchical_delegation_if_subtask_eq_edit
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_SUBTASK_EQ_SQL
    value: routers.router_hierarchical_delegation_if_subtask_eq_sql
  - name: ASYA_HANDLER_ROUTER_HIERARCHICAL_DELEGATION_IF_SUBTASK_EQ_WRITE
    value: routers.router_hierarchical_delegation_if_subtask_eq_write
  - name: ASYA_HANDLER_ACTOR_SQL_SPECIALIST
    value: sql_specialist
  - name: ASYA_HANDLER_ACTOR_WRITER
    value: writer
