apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: final-assembler
  namespace: default
  labels:
    asya.sh/flow: hierarchical-delegation
    asya.sh/role: end
spec:
  actor: final-assembler
  image: examples.asya.sh/final-assembler:latest
  handler: final_assembler
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: '5'
  env: []
