apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-api-specialist.yaml
- asya-actor-content-generalist.yaml
- asya-actor-content-team-lead.yaml
- asya-actor-data-generalist.yaml
- asya-actor-data-team-lead.yaml
- asya-actor-editor.yaml
- asya-actor-final-assembler.yaml
- asya-actor-generalist.yaml
- asya-actor-root-agent.yaml
- asya-actor-sql-specialist.yaml
- asya-actor-writer.yaml
- asya-router-hierarchical-delegation-line-60-if-6.yaml
- asya-router-hierarchical-delegation-line-64-if-2.yaml
- asya-router-hierarchical-delegation-line-66-if-1.yaml
- asya-router-hierarchical-delegation-line-71-if-5.yaml
- asya-router-hierarchical-delegation-line-75-if-4.yaml
- asya-router-hierarchical-delegation-line-77-if-3.yaml
- asya-start-hierarchical-delegation.yaml
- configmap-routers.yaml
