apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-api-specialist.yaml
- asya-actor-content-generalist.yaml
- asya-actor-content-team-lead.yaml
- asya-actor-data-generalist.yaml
- asya-actor-data-team-lead.yaml
- asya-actor-editor.yaml
- asya-actor-final-assembler.yaml
- asya-actor-generalist.yaml
- asya-actor-root-agent.yaml
- asya-actor-sql-specialist.yaml
- asya-actor-writer.yaml
- asya-router-hierarchical-delegation-if-domain-eq-content.yaml
- asya-router-hierarchical-delegation-if-domain-eq-data.yaml
- asya-router-hierarchical-delegation-if-subtask-eq-api.yaml
- asya-router-hierarchical-delegation-if-subtask-eq-edit.yaml
- asya-router-hierarchical-delegation-if-subtask-eq-sql.yaml
- asya-router-hierarchical-delegation-if-subtask-eq-write.yaml
- asya-start-hierarchical-delegation.yaml
- configmap-routers.yaml
