apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: router-data-pipeline-except-valueerror
  namespace: default
  labels:
    asya.sh/flow: data-pipeline
    asya.sh/generated: 'true'
spec:
  actor: router-data-pipeline-except-valueerror
  image: python:3.13-slim
  handler: routers.router_data_pipeline_except_valueerror
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 2
  env:
  - name: ASYA_HANDLER_ACTOR_HANDLE_RUNTIME_ERROR
    value: handle_runtime_error
  - name: ASYA_HANDLER_ACTOR_HANDLE_TYPE_ERROR
    value: handle_type_error
  - name: ASYA_HANDLER_ACTOR_HANDLE_VALIDATION_ERROR
    value: handle_validation_error
  - name: ASYA_HANDLER_ACTOR_PARSE_INPUT
    value: parse_input
  - name: ASYA_HANDLER_ACTOR_TRANSFORM_DATA
    value: transform_data
