apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: actor-transform-data
  namespace: default
  labels:
    asya.sh/flow: data-pipeline
spec:
  actor: actor-transform-data
  image: examples.asya.sh/transform-data:latest
  handler: transform_data
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
  resiliency:
    policies:
      except_valueerror:
        maxAttempts: 1
        thenRoute:
        - router-data-pipeline-except-valueerror
      except_typeerror:
        maxAttempts: 1
        thenRoute:
        - router-data-pipeline-except-typeerror
      except_runtimeerror:
        maxAttempts: 1
        thenRoute:
        - router-data-pipeline-except-runtimeerror
    rules:
    - errors:
      - ValueError
      policy: except_valueerror
    - errors:
      - TypeError
      policy: except_typeerror
    - errors:
      - RuntimeError
      policy: except_runtimeerror
