apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handle-runtime-error.yaml
- asya-actor-handle-type-error.yaml
- asya-actor-handle-validation-error.yaml
- asya-actor-parse-input.yaml
- asya-actor-transform-data.yaml
- asya-router-try-except-multiple-handlers-except-runtimeerror.yaml
- asya-router-try-except-multiple-handlers-except-typeerror.yaml
- asya-router-try-except-multiple-handlers-except-valueerror.yaml
- asya-start-try-except-multiple-handlers.yaml
- configmap-routers.yaml
