apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handle-runtime-error.yaml
- asya-actor-handle-type-error.yaml
- asya-actor-handle-validation-error.yaml
- asya-actor-parse-input.yaml
- asya-actor-transform-data.yaml
- asya-router-data-pipeline-line-12-except-2.yaml
- asya-router-data-pipeline-line-15-except-3.yaml
- asya-router-data-pipeline-line-9-except-1.yaml
- asya-start-data-pipeline.yaml
- configmap-routers.yaml
