apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asyncactor-handle-runtime-error.yaml
- asyncactor-handle-type-error.yaml
- asyncactor-handle-validation-error.yaml
- asyncactor-parse-input.yaml
- asyncactor-router-data-pipeline-line-10-seq-1.yaml
- asyncactor-router-data-pipeline-line-12-except-4.yaml
- asyncactor-router-data-pipeline-line-13-seq-3.yaml
- asyncactor-router-data-pipeline-line-15-except-6.yaml
- asyncactor-router-data-pipeline-line-16-seq-5.yaml
- asyncactor-router-data-pipeline-line-9-except-2.yaml
- asyncactor-start-data-pipeline.yaml
- asyncactor-transform-data.yaml
- configmap-routers.yaml
