apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: analyze
  namespace: demo-skaffold
  labels:
    asya.sh/flow: pipeline
spec:
  actor: analyze
  image: skaffold-sentiment-actors
  handler: sentiment_actors.handler.analyze
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
