apiVersion: asya.sh/v1alpha1
kind: AsyncActor
metadata:
  name: generator
  namespace: asya-demo
  labels:
    asya.sh/flow: text-improver
    asya.sh/flow-role: handler
spec:
  actor: generator
  image: asya-demo:latest
  handler: demo_actors.generator.generator
  scaling:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 5
  env: []
