apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-handler-check.yaml
- asya-actor-handler-finalize.yaml
- asya-actor-handler-init.yaml
- asya-actor-handler-process.yaml
- asya-router-while-break-continue-flow-if-skip.yaml
- asya-router-while-break-continue-flow-if-stop.yaml
- asya-router-while-break-continue-flow-seq-set-i-2.yaml
- asya-router-while-break-continue-flow-seq-set-i.yaml
- asya-router-while-break-continue-flow-while-i-lt-max-iterations.yaml
- asya-start-while-break-continue-flow.yaml
- configmap-routers.yaml
