flowchart TD
    %% Flow: decorator_callsite_flow

    enricher[enricher]
    start_decorator_callsite_flow([start_decorator_callsite_flow])
    validator[validator]
    __end__((( )))

    start_decorator_callsite_flow --> validator
    validator --> enricher
    enricher --> __end__