apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment
  labels:
    app: sentiment
    team: team-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
        team: team-a
    spec:
      containers:
      - name: sentiment
        image: skaffold-sentiment-actors
        ports:
        - containerPort: 8080
