flowchart TD
    %% Flow: multi_stage_flow

    fanin_multi_stage_flow_research[fanin_multi_stage_flow_research]
    fanin_multi_stage_flow_reviews[fanin_multi_stage_flow_reviews]
    research_agent[research_agent]
    review_agent[review_agent]
    router_multi_stage_flow_fanout_research{{router_multi_stage_flow_fanout_research}}
    router_multi_stage_flow_fanout_reviews{{router_multi_stage_flow_fanout_reviews}}
    start_multi_stage_flow([start_multi_stage_flow])
    summarizer[summarizer]
    __end__((( )))

    start_multi_stage_flow --> router_multi_stage_flow_fanout_research
    router_multi_stage_flow_fanout_reviews -->|"fanout: p['research']"| fanin_multi_stage_flow_reviews
    fanin_multi_stage_flow_reviews --> summarizer
    router_multi_stage_flow_fanout_reviews --> review_agent
    review_agent --> fanin_multi_stage_flow_reviews
    router_multi_stage_flow_fanout_research -->|"fanout: p['topics']"| fanin_multi_stage_flow_research
    fanin_multi_stage_flow_research --> router_multi_stage_flow_fanout_reviews
    router_multi_stage_flow_fanout_research --> research_agent
    research_agent --> fanin_multi_stage_flow_research
    summarizer --> __end__

    classDef start fill:#98FB98,stroke:#333
    classDef endnode fill:#FFA07A,stroke:#333
    classDef router fill:#F5DEB3,stroke:#333
    classDef handler fill:#ADD8E6,stroke:#333
    classDef endpoint fill:#000,stroke:#333,color:#fff
    class start_multi_stage_flow start
    class summarizer,__end__ endnode
    class router_multi_stage_flow_fanout_research,router_multi_stage_flow_fanout_reviews router
    class fanin_multi_stage_flow_research,fanin_multi_stage_flow_reviews,research_agent,review_agent handler
    linkStyle 1,5 stroke:#7B68EE