# Actor with custom sidecar configuration
# Demonstrates all sidecar customization options

apiVersion: asya.io/v1alpha1
kind: AsyncActor
metadata:
  name: custom-sidecar-actor
  namespace: default
spec:
  queueName: custom-queue

  transport:
    type: rabbitmq
    rabbitmq:
      host: rabbitmq.rabbitmq.svc.cluster.local
      port: 5672
      username: admin
      passwordSecretRef:
        name: rabbitmq-secret
        key: password

  # Custom sidecar configuration
  sidecar:
    # Use a specific version
    image: asya-sidecar:v2.1.0
    imagePullPolicy: Always

    # Custom resource limits
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 128Mi

    # Additional environment variables for the sidecar
    env:
    - name: ASYA_LOG_LEVEL
      value: debug
    - name: ENABLE_TRACING
      value: "true"
    - name: JAEGER_ENDPOINT
      value: http://jaeger-collector:14268/api/traces
    - name: CUSTOM_TIMEOUT
      value: "30"

  # Custom socket configuration
  socket:
    path: /custom/path/app.sock
    maxSize: "20971520"  # 20MB

  # Custom timeouts
  timeout:
    processing: 600
    gracefulShutdown: 60

  scaling:
    enabled: true
    minReplicas: 0
    maxReplicas: 10
    queueLength: 5

  workload:
    type: Deployment
    template:
      spec:
        containers:
        - name: runtime
          image: custom-runtime:latest
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
