# Simple Actor example with RabbitMQ transport
# This is the minimal configuration needed to create an actor

apiVersion: asya.io/v1alpha1
kind: AsyncActor
metadata:
  name: hello-actor
  namespace: default
spec:
  # Queue to consume from
  queueName: hello-queue

  # Use RabbitMQ transport
  transport:
    type: rabbitmq
    rabbitmq:
      host: rabbitmq.rabbitmq.svc.cluster.local
      port: 5672
      username: admin
      passwordSecretRef:
        name: rabbitmq-secret
        key: password

  # Your runtime container
  workload:
    type: Deployment
    template:
      spec:
        containers:
        - name: runtime
          image: python:3.13-slim
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
