flowchart TD
    %% Flow: sequential_flow

    handler_a[handler_a]
    handler_b[handler_b]
    handler_c([handler_c])
    start_sequential_flow([start_sequential_flow])

    start_sequential_flow --> handler_a
    handler_a --> handler_b
    handler_b --> handler_c