{{- if .Values.providers.gcp.enabled }}
apiVersion: apiextensions.crossplane.io/v1
kind: EnvironmentConfig
metadata:
  name: asya-pubsub
  labels:
    {{- include "asya-crossplane.labels" . | nindent 4 }}
data:
  gcpProject: {{ .Values.gcpProviderConfig.projectId | quote }}
  gcpProviderConfig: {{ .Values.gcpProviderConfig.name }}
{{- end }}
