apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asya-e2e
resources:
- ../../common
images:
- name: europe-west1-docker.pkg.dev/foodsci-img-gen-dev-1407-1448/asya-demo/demo-kubecon
  newName: demo-kubecon
  newTag: latest
patches:
- path: patch-actor-evaluate.yaml
- path: patch-actor-generate.yaml
- path: patch-actor-research.yaml
- path: patch-start-text-improver.yaml
- path: patch-router-text-improver-if-iteration-ge-max-iterations.yaml
- path: patch-router-text-improver-if-score-ge-threshold.yaml
- path: patch-router-text-improver-seq-set-iteration.yaml
- path: patch-router-text-improver-while-loop.yaml
