apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- asya-actor-finalize-loop-i.yaml
- asya-actor-finalize-loop-j.yaml
- asya-actor-initialize.yaml
- asya-actor-process-item.yaml
- asya-router-nested-loop-flow-seq-set-i-2.yaml
- asya-router-nested-loop-flow-seq-set-i.yaml
- asya-router-nested-loop-flow-seq-set-j.yaml
- asya-router-nested-loop-flow-while-i-lt-max-i.yaml
- asya-router-nested-loop-flow-while-j-lt-max-j.yaml
- asya-start-nested-loop-flow.yaml
- configmap-routers.yaml
