# fmt: off
# ruff: noqa
"""
Auto-generated by asya flow compiler
Source: ../../multi_agent_debate.py

DO NOT EDIT THIS FILE MANUALLY
Regenerate by running: asya flow compile ../../multi_agent_debate.py
"""

import copy


# ======================================================================
# Generated Routers (for kubernetes deployment)
# ======================================================================

async def start_multi_agent_debate(payload: dict):
    """Entrypoint for flow 'multi_agent_debate'"""
    _next = []
    _next.append(resolve("router_multi_agent_debate_line_55_seq_7"))
    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_multi_agent_debate_line_74_fanout_2(payload: dict):
    """Fan-out router: dispatches to sub-agents and aggregator (line 74)"""
    p = payload

    origin_id = yield "GET", ".id"
    _next_tail = yield "GET", ".route.next"

    _agg = resolve("fanin_multi_agent_debate_line_74")

    _slices = []
    _slices.append((resolve("revise_a"), p))
    _slices.append((resolve("revise_b"), p))
    _slices.append((resolve("revise_c"), p))

    _n = len(_slices) + 1
    _fan_in = {
        "actor": _agg,
        "origin_id": origin_id,
        "slice_count": _n,
        "aggregation_key": "/positions",
    }

    # Index 0: parent payload forwarded to aggregator
    yield "SET", ".route.next", [_agg] + _next_tail
    yield "SET", ".headers.x-asya-fan-in", {**_fan_in, "slice_index": 0}
    yield copy.deepcopy(p)

    for _i, (_actor, _payload) in enumerate(_slices):
        yield "SET", ".route.next", [_actor, _agg]
        yield "SET", ".headers.x-asya-fan-in", {**_fan_in, "slice_index": _i + 1}
        yield _payload

async def router_multi_agent_debate_line_71_if_3(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p['round'] >= 3:
        yield "SET", ".route.next", [resolve("final_judge")]
        yield p
        return
    else:
        _next.append(resolve("router_multi_agent_debate_line_74_fanout_2"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_multi_agent_debate_line_68_if_4(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    if p.get('converged'):
        yield "SET", ".route.next", [resolve("final_judge")]
        yield p
        return
    else:
        _next.append(resolve("router_multi_agent_debate_line_71_if_3"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_multi_agent_debate_line_64_seq_5(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['round'] += 1
    _next.append(resolve("convergence_checker"))
    _next.append(resolve("router_multi_agent_debate_line_68_if_4"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_multi_agent_debate_line_63_while_1(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    _next.append(resolve("router_multi_agent_debate_line_64_seq_5"))
    _next.append(resolve("router_multi_agent_debate_line_63_while_1"))

    yield "SET", ".route.next[:0]", _next
    yield payload

async def router_multi_agent_debate_line_57_fanout_6(payload: dict):
    """Fan-out router: dispatches to sub-agents and aggregator (line 57)"""
    p = payload

    origin_id = yield "GET", ".id"
    _next_tail = yield "GET", ".route.next"

    _agg = resolve("fanin_multi_agent_debate_line_57")

    _slices = []
    _slices.append((resolve("debater_a"), p['question']))
    _slices.append((resolve("debater_b"), p['question']))
    _slices.append((resolve("debater_c"), p['question']))

    _n = len(_slices) + 1
    _fan_in = {
        "actor": _agg,
        "origin_id": origin_id,
        "slice_count": _n,
        "aggregation_key": "/positions",
    }

    # Index 0: parent payload forwarded to aggregator
    yield "SET", ".route.next", [_agg, resolve("router_multi_agent_debate_line_63_while_1")] + _next_tail
    yield "SET", ".headers.x-asya-fan-in", {**_fan_in, "slice_index": 0}
    yield copy.deepcopy(p)

    for _i, (_actor, _payload) in enumerate(_slices):
        yield "SET", ".route.next", [_actor, _agg]
        yield "SET", ".headers.x-asya-fan-in", {**_fan_in, "slice_index": _i + 1}
        yield _payload

async def router_multi_agent_debate_line_55_seq_7(payload: dict):
    """Router for control flow and payload mutations"""
    p = payload
    _next = []
    p['round'] = 0
    _next.append(resolve("router_multi_agent_debate_line_57_fanout_6"))

    yield "SET", ".route.next[:0]", _next
    yield payload


# ======================================================================
# Handler Resolution
# ======================================================================

import os
import logging

_HANDLER_TO_ACTOR: dict[str, str] = {}
_SUFFIX_TO_HANDLERS: dict[str, list[str]] = {}

for _env_var, _handler_name in os.environ.items():
    if _env_var.startswith('ASYA_HANDLER_'):
        _actor_name = _env_var[len('ASYA_HANDLER_'):].lower().replace('_', '-')
        _HANDLER_TO_ACTOR[_handler_name] = _actor_name

        # Index all suffixes (e.g., "a.b.c" -> ["c", "b.c", "a.b.c"])
        _parts = _handler_name.split('.')
        for _i in range(len(_parts)):
            _suffix = '.'.join(_parts[_i:])
            if _suffix not in _SUFFIX_TO_HANDLERS:
                _SUFFIX_TO_HANDLERS[_suffix] = []
            _SUFFIX_TO_HANDLERS[_suffix].append(_handler_name)

logging.info(f"Loaded {len(_HANDLER_TO_ACTOR)} handler-to-actor mappings")


def resolve(handler_full_name: str) -> str:
    """
    Resolve handler name to actor name using suffix-based matching.

    Looks up handler in environment variables:
    - ASYA_HANDLER_<ACTOR_NAME>="full.module.path.ClassName.method"

    Supports flexible suffix matching - any suffix of the full path can be used if unambiguous:
    - "method" (shortest)
    - "ClassName.method" (class + method)
    - "module.ClassName.method" (partial path)
    - "full.module.path.ClassName.method" (full path)

    Args:
        handler_full_name: Any suffix of the full handler path

    Returns:
        Actor name for routing (kebab-case, lowercase)

    Raises:
        ValueError: If handler suffix not found or is ambiguous

    Examples:
        # Environment: ASYA_HANDLER_MY_ACTOR="class_instantiation.DataPreprocessor.clean"

        # All of these work (if unambiguous):
        resolve("clean")  # shortest suffix
        resolve("DataPreprocessor.clean")  # class + method
        resolve("class_instantiation.DataPreprocessor.clean")  # full path

        # Ambiguous suffix
        # Env: ASYA_HANDLER_A="module1.clean", ASYA_HANDLER_B="module2.clean"
        resolve("clean")  # raises ValueError: ambiguous, use longer suffix
    """
    if handler_full_name in _SUFFIX_TO_HANDLERS:
        candidates = _SUFFIX_TO_HANDLERS[handler_full_name]
        if len(candidates) == 1:
            return _HANDLER_TO_ACTOR[candidates[0]]
        else:
            raise ValueError(
                f"Handler suffix '{handler_full_name}' is ambiguous. "
                f"Found multiple matches: {candidates}. "
                f"Use a longer suffix to disambiguate."
            )

    raise ValueError(
        f"Handler '{handler_full_name}' not found in environment variables. "
        f'No handler ends with suffix "{handler_full_name}". '
        f"Available handlers: {list(_HANDLER_TO_ACTOR.keys())}"
    )
